-- profile_media tables. CREATE TABLE and COMMENT ON only.
-- Functions, policies, and privileges live in later layers.

SET LOCAL ROLE ple_data_owner;

-- Role-neutral Profile-image storage saga. A Profile image is private to its
-- owning Account; only the service records completed external object operations.
-- ASVS 2.2.1/2.2.2: the schema makes each avatar variant exclusive and binds
-- an image selection to an exact, self-owned delivery record.
CREATE TABLE ple_data.profile_image_delivery (
    object_delivery_id uuid PRIMARY KEY,
    object_record_id uuid NOT NULL REFERENCES ple_private.object_record,
    profile_image_id uuid NOT NULL UNIQUE,
    UNIQUE (object_delivery_id, object_record_id),
    UNIQUE (profile_image_id, object_delivery_id),
    FOREIGN KEY (object_delivery_id, object_record_id) REFERENCES ple_data.object_delivery (object_delivery_id, object_record_id),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.transaction_timestamp(),
    CHECK (updated_at >= created_at)
);


CREATE TABLE ple_data.provided_avatar (
    provided_avatar_id text PRIMARY KEY CHECK (
        provided_avatar_id = btrim(provided_avatar_id)
        AND provided_avatar_id ~ '^[a-z][a-z0-9-]{0,63}$'
    ),
    asset_sha256 text NOT NULL CHECK (
        asset_sha256 ~ '^[0-9a-f]{64}$'
    ),
    is_selectable boolean NOT NULL,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.transaction_timestamp()
);



-- C832 is the single literal catalog source.  It upserts catalog facts during
-- fresh installation and deliberately retains historical IDs so a retired
-- asset remains renderable for Accounts that already selected it.
-- inlined from provided_avatar_catalog.sql
-- Generated by devel/generate_avatar_catalog.py. Do not edit by hand.
-- This runs after ple_data.provided_avatar exists.
-- Removed manifest IDs remain rows with their recorded checksum and is_selectable = false.
INSERT INTO ple_data.provided_avatar
    (provided_avatar_id, asset_sha256, is_selectable)
VALUES
    ('amber-arch', 'cc199a8e914cf3cd96b6a5bcd04110fed70e332e9addf9a0008d7acf7e4cf227', true),
    ('berry-bloom', 'eeab13136999db047f7e4e01ccd3eeda6840315b488a1a98be872bfc3d103ada', true),
    ('cobalt-circuit', 'e0e5dcc64e4a37a5c6a379f4bb8c32e9df1eb668eae0155a72e3fed71bea23e7', true),
    ('coral-crossing', '07e74194c72e6cced43dbde4e1dbb385097379c8bb4aff32958d9a77e09aa3a2', true),
    ('fern-facet', '7004e480ee40cd24e52fb9e86ddec9a63d2369e7cc9fa8ecd4ff3d998777f2de', true),
    ('golden-garden', 'ac28141bdfddd1e5bf248337c63e7b5682d7f51629ec1571c04f97fa7052c635', true),
    ('indigo-island', '4566da9fdc624bf191b1333dc60eff0ebc509b006ade23ee9027c65c24502484', true),
    ('mint-mosaic', '4453aa78a9f97ac16fc28baada2dff7d3abbd728c0aa4f3bfac51f21e9998b27', true),
    ('plum-pulse', '618752449366b635d2f58848c921b72a7aab32abe2540b25eb8233a9577a38eb', true),
    ('saffron-spark', 'e2ff8a16d2ec89c5be7eac5078a5ff7ec254a363953746db818ff3cadc810a65', true),
    ('sky-stack', '0095a9c4edec2663eec7630935ce357cc50e712cabb1e0aa196abd240b01a3f8', true),
    ('teal-trail', 'dbe77cac735abeb52688026538f9e16602981fb138f2dd3ef66a0c01c3270c7c', true)
ON CONFLICT (provided_avatar_id) DO UPDATE
SET asset_sha256 = EXCLUDED.asset_sha256,
    is_selectable = EXCLUDED.is_selectable
WHERE ple_data.provided_avatar.asset_sha256 IS DISTINCT FROM EXCLUDED.asset_sha256
   OR ple_data.provided_avatar.is_selectable IS DISTINCT FROM EXCLUDED.is_selectable;

-- Retire omitted catalog IDs without deleting their historical identity or checksum.
UPDATE ple_data.provided_avatar
SET is_selectable = false
WHERE is_selectable
  AND provided_avatar_id NOT IN (
    'amber-arch',
    'berry-bloom',
    'cobalt-circuit',
    'coral-crossing',
    'fern-facet',
    'golden-garden',
    'indigo-island',
    'mint-mosaic',
    'plum-pulse',
    'saffron-spark',
    'sky-stack',
    'teal-trail'
);

SET LOCAL ROLE ple_private_owner;

CREATE TABLE ple_private.account_avatar (
    account_id ple_data.account_id PRIMARY KEY REFERENCES ple_private.account,
    avatar_kind ple_data.avatar_kind NOT NULL,
    provided_avatar_id text REFERENCES ple_data.provided_avatar,
    profile_image_id uuid,
    profile_image_delivery_id uuid,
    CHECK (
        (avatar_kind = 'provided' AND provided_avatar_id IS NOT NULL
            AND profile_image_id IS NULL AND profile_image_delivery_id IS NULL)
        OR
        (avatar_kind = 'profile-image' AND provided_avatar_id IS NULL
            AND profile_image_id IS NOT NULL AND profile_image_delivery_id IS NOT NULL)
    ),
    UNIQUE (profile_image_id),
    UNIQUE (profile_image_delivery_id),
    FOREIGN KEY (profile_image_id, profile_image_delivery_id)
        REFERENCES ple_data.profile_image_delivery (profile_image_id, object_delivery_id),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT pg_catalog.transaction_timestamp(),
    CHECK (updated_at >= created_at)
);



CREATE TABLE ple_private.profile_image_work (
    profile_image_work_id uuid PRIMARY KEY,
    account_id ple_data.account_id NOT NULL REFERENCES ple_private.account,
    profile_image_id uuid NOT NULL,
    object_delivery_id uuid NOT NULL,
    object_record_id uuid NOT NULL REFERENCES ple_private.object_record,
    operation_kind ple_data.object_work_operation NOT NULL,
    state ple_data.lease_state NOT NULL,
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    UNIQUE (profile_image_id, operation_kind),
    FOREIGN KEY (object_delivery_id, object_record_id)
        REFERENCES ple_data.profile_image_delivery (object_delivery_id, object_record_id)
);


SET LOCAL ROLE ple_data_owner;

SET LOCAL ROLE ple_data_owner;
COMMENT ON TABLE ple_data.profile_image_delivery IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_data.provided_avatar IS 'role: vocabulary, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;

SET LOCAL ROLE ple_private_owner;
COMMENT ON TABLE ple_private.account_avatar IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_private.profile_image_work IS 'role: event, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';



SET LOCAL ROLE ple_data_owner;

SET LOCAL ROLE ple_data_owner;
COMMENT ON TABLE ple_data.profile_image_delivery IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_data.provided_avatar IS 'role: vocabulary, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;

SET LOCAL ROLE ple_private_owner;
COMMENT ON TABLE ple_private.account_avatar IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_private.profile_image_work IS 'role: event, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';


SET LOCAL ROLE ple_data_owner;

SET LOCAL ROLE ple_data_owner;
COMMENT ON TABLE ple_data.profile_image_delivery IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_data.provided_avatar IS 'role: vocabulary, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;

SET LOCAL ROLE ple_private_owner;
COMMENT ON TABLE ple_private.account_avatar IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_private.profile_image_work IS 'role: event, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';



SET LOCAL ROLE ple_data_owner;

SET LOCAL ROLE ple_data_owner;
COMMENT ON TABLE ple_data.profile_image_delivery IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_data.provided_avatar IS 'role: vocabulary, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;

SET LOCAL ROLE ple_private_owner;
COMMENT ON TABLE ple_private.account_avatar IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_private.profile_image_work IS 'role: event, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';




SET LOCAL ROLE ple_data_owner;

SET LOCAL ROLE ple_data_owner;
COMMENT ON TABLE ple_data.profile_image_delivery IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_data.provided_avatar IS 'role: vocabulary, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;

SET LOCAL ROLE ple_private_owner;
COMMENT ON TABLE ple_private.account_avatar IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_private.profile_image_work IS 'role: event, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';



SET LOCAL ROLE ple_data_owner;

SET LOCAL ROLE ple_data_owner;
COMMENT ON TABLE ple_data.profile_image_delivery IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_data.provided_avatar IS 'role: vocabulary, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;

SET LOCAL ROLE ple_private_owner;
COMMENT ON TABLE ple_private.account_avatar IS 'role: current state, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

COMMENT ON TABLE ple_private.profile_image_work IS 'role: event, deleted by Account closure and object cleanup. HUMAN_GUIDANCE.md Account avatars.';

SET LOCAL ROLE ple_private_owner;
COMMENT ON COLUMN ple_private.account_avatar.provided_avatar_id IS 'NULL means this optional fact is absent.';
COMMENT ON COLUMN ple_private.account_avatar.profile_image_id IS 'NULL means this optional fact is absent.';
COMMENT ON COLUMN ple_private.account_avatar.profile_image_delivery_id IS 'NULL means this optional fact is absent.';
COMMENT ON COLUMN ple_private.profile_image_work.completed_at IS 'NULL means this optional fact is absent.';

