# Homebrew packages this repo needs beyond a stock developer machine.
#
# Install with: brew bundle
#
# Deliberately short. The WebAssembly toolchain is NOT here: the wasm32 target
# comes from rust-toolchain.toml, and the wasm-bindgen glue is generated by
# crates/xtask, which Cargo.lock pins to the same version as the wasm-bindgen
# crate compiled into the module. An externally installed generator could drift
# out of step after a system upgrade and fail at load time.
#
# Rust itself is installed through rustup (https://rustup.rs), not Homebrew.

# Container runtime for the api, postgres, and minio services (WP-F4).
# macOS setup: docs/MACOS_PODMAN.md
brew "podman"
