#!/usr/bin/env bash
# build_wasm.sh - compile crates/wasm to WebAssembly and generate the JS glue.
#
# Output goes to dist_wasm/, which .gitignore covers via the dist_*/ pattern.
# Two flavors are emitted from one compiled module:
#
#   dist_wasm/web/   ES module for the Solid client; pipeline/build.mjs copies
#                    it into dist/wasm/
#   dist_wasm/node/  CommonJS for tests/e2e/e2e_wasm_bridge.mjs, the WP-F2
#                    proof that a Rust export is callable from Node
#
# The node flavor exists only for that test. Browsers get the web flavor.
#
# Why the glue is generated by the repository's `cargo tools` command rather
# than an installed `wasm-bindgen` binary: the generator and the wasm-bindgen crate compiled into
# the module must be the same version. Taking the generator from the workspace
# means Cargo.lock pins both, so they cannot drift. An externally installed CLI
# can silently fall out of step after a system upgrade, and the failure shows
# up as an unhelpful load-time error in the browser.
#
# Flags:
#   --debug   build the unoptimized profile (faster, much larger artifact)

set -euo pipefail
cd "$(git rev-parse --show-toplevel)"

CARGO_PROFILE="release"
PROFILE_DIR="release"
if [ "${1:-}" = "--debug" ]; then
	CARGO_PROFILE="dev"
	PROFILE_DIR="debug"
fi

if ! command -v cargo >/dev/null 2>&1; then
	echo "ERROR: cargo not found on PATH. Install Rust from https://rustup.rs" >&2
	exit 1
fi

echo "==> cargo build ($CARGO_PROFILE) for wasm32-unknown-unknown"
# The wasm32-unknown-unknown target is listed in rust-toolchain.toml, so rustup
# installs it automatically on first use. No manual `rustup target add` needed.
cargo build --profile "$CARGO_PROFILE" --target wasm32-unknown-unknown -p wasm_bridge

WASM_INPUT="target/wasm32-unknown-unknown/${PROFILE_DIR}/wasm_bridge.wasm"
if [ ! -f "$WASM_INPUT" ]; then
	echo "ERROR: expected artifact missing: $WASM_INPUT" >&2
	exit 1
fi

rm -rf dist_wasm
mkdir -p dist_wasm

# Pairs are "<flavor> <output directory>". Spelled out rather than derived so a
# reader can see both flavors at a glance.
for pair in "web dist_wasm/web" "node dist_wasm/node"; do
	set -- $pair
	flavor="$1"
	out_dir="$2"
	echo "==> bindgen --$flavor -> $out_dir"
	cargo tools bindgen "$WASM_INPUT" "$flavor" "$out_dir" ple_bridge
done

# The node flavor is CommonJS, but the repo-root package.json declares
# "type": "module", which makes Node parse every .js file as ESM and fail on
# the generated `exports.` assignments. A package.json in the output directory
# scopes the module system to that directory, which is the supported way to mix
# the two rather than renaming generated files after the fact.
echo '{"type":"commonjs"}' >dist_wasm/node/package.json

test -f dist_wasm/web/ple_bridge_bg.wasm || {
	echo "ERROR: web flavor missing its .wasm" >&2
	exit 1
}
test -f dist_wasm/node/ple_bridge.js || {
	echo "ERROR: node flavor missing its entry module" >&2
	exit 1
}

echo "Built dist_wasm/ (web + node) from $WASM_INPUT"
