// Generated by devel/generate_avatar_catalog.py. Do not edit by hand.

export interface ProvidedAvatarCatalogEntry {
  readonly id: string;
  readonly name: string;
  readonly description: string;
  readonly assetPath: string;
  readonly assetSha256: string;
  readonly isSelectable: boolean;
}

export const PROVIDED_AVATAR_CATALOG = [
  {
    id: "amber-arch",
    name: "Amber arch",
    description: "Amber arch with two blue dots.",
    assetPath: "/assets/avatar_catalog/svg/amber-arch.svg",
    assetSha256: "cc199a8e914cf3cd96b6a5bcd04110fed70e332e9addf9a0008d7acf7e4cf227",
    isSelectable: true,
  },
  {
    id: "berry-bloom",
    name: "Berry bloom",
    description: "Berry circles around a bright center.",
    assetPath: "/assets/avatar_catalog/svg/berry-bloom.svg",
    assetSha256: "eeab13136999db047f7e4e01ccd3eeda6840315b488a1a98be872bfc3d103ada",
    isSelectable: true,
  },
  {
    id: "cobalt-circuit",
    name: "Cobalt circuit",
    description: "Cobalt blocks joined by a curved line.",
    assetPath: "/assets/avatar_catalog/svg/cobalt-circuit.svg",
    assetSha256: "e0e5dcc64e4a37a5c6a379f4bb8c32e9df1eb668eae0155a72e3fed71bea23e7",
    isSelectable: true,
  },
  {
    id: "coral-crossing",
    name: "Coral reef",
    description: "Branching coral reef with a small fish in ocean water.",
    assetPath: "/assets/avatar_catalog/svg/coral-crossing.svg",
    assetSha256: "07e74194c72e6cced43dbde4e1dbb385097379c8bb4aff32958d9a77e09aa3a2",
    isSelectable: true,
  },
  {
    id: "fern-facet",
    name: "Fern facet",
    description: "Green facets in a rounded tile.",
    assetPath: "/assets/avatar_catalog/svg/fern-facet.svg",
    assetSha256: "7004e480ee40cd24e52fb9e86ddec9a63d2369e7cc9fa8ecd4ff3d998777f2de",
    isSelectable: true,
  },
  {
    id: "golden-garden",
    name: "Golden garden",
    description: "Golden petals with green leaves.",
    assetPath: "/assets/avatar_catalog/svg/golden-garden.svg",
    assetSha256: "ac28141bdfddd1e5bf248337c63e7b5682d7f51629ec1571c04f97fa7052c635",
    isSelectable: true,
  },
  {
    id: "indigo-island",
    name: "Indigo island",
    description: "Indigo oval above a small wave.",
    assetPath: "/assets/avatar_catalog/svg/indigo-island.svg",
    assetSha256: "4566da9fdc624bf191b1333dc60eff0ebc509b006ade23ee9027c65c24502484",
    isSelectable: true,
  },
  {
    id: "mint-mosaic",
    name: "Mint mosaic",
    description: "Mint and blue mosaic squares.",
    assetPath: "/assets/avatar_catalog/svg/mint-mosaic.svg",
    assetSha256: "4453aa78a9f97ac16fc28baada2dff7d3abbd728c0aa4f3bfac51f21e9998b27",
    isSelectable: true,
  },
  {
    id: "plum-pulse",
    name: "Plum pulse",
    description: "Plum rings around a warm dot.",
    assetPath: "/assets/avatar_catalog/svg/plum-pulse.svg",
    assetSha256: "618752449366b635d2f58848c921b72a7aab32abe2540b25eb8233a9577a38eb",
    isSelectable: true,
  },
  {
    id: "saffron-spark",
    name: "Saffron spark",
    description: "Saffron star shapes on navy.",
    assetPath: "/assets/avatar_catalog/svg/saffron-spark.svg",
    assetSha256: "e2ff8a16d2ec89c5be7eac5078a5ff7ec254a363953746db818ff3cadc810a65",
    isSelectable: true,
  },
  {
    id: "sky-stack",
    name: "Sky stack",
    description: "Blue blocks stacked in balance.",
    assetPath: "/assets/avatar_catalog/svg/sky-stack.svg",
    assetSha256: "0095a9c4edec2663eec7630935ce357cc50e712cabb1e0aa196abd240b01a3f8",
    isSelectable: true,
  },
  {
    id: "teal-trail",
    name: "Teal trail",
    description: "Teal path through peach circles.",
    assetPath: "/assets/avatar_catalog/svg/teal-trail.svg",
    assetSha256: "dbe77cac735abeb52688026538f9e16602981fb138f2dd3ef66a0c01c3270c7c",
    isSelectable: true,
  },
] as const satisfies readonly ProvidedAvatarCatalogEntry[];
