//! Generates TypeScript definitions from the Rust question model.
//!
//! Why this is hand-written rather than a codegen dependency:
//!
//! - `question_model` stays free of build tooling. A derive macro from a
//!   codegen crate would sit on every boundary type in the product's root
//!   contract.
//! - We control the emitted formatting. The generated files must pass
//!   `prettier --check` unchanged, and a third-party generator gives no say
//!   over line width or quote style, which forces a reformat pass that then
//!   checks output nobody generated.
//! - The mapping rules are the contract. Writing them out means a reader can
//!   see exactly how a Rust type becomes a TypeScript type.
//!
//! What is exported: every `pub` struct or enum in the model crate that derives
//! `Serialize` or `Deserialize`. That rule is the definition of a boundary
//! type -- if it crosses the wire it needs a TypeScript shape, and if it must
//! not cross the wire it must not be serializable.
//!
//! Supported shapes, and the reason each is enough:
//!
//! | Rust | TypeScript |
//! | --- | --- |
//! | unit-only enum | string union |
//! | externally tagged enum with data | string/object union |
//! | enum with data, `#[serde(tag = "...")]` | discriminated union |
//! | struct with named fields | object type |
//! | newtype struct | alias to the inner type |
//!
//! Untagged data enums use serde's externally tagged form. Unit variants stay
//! strings, while data variants become a one-key object (`{ variant: value }`).
//! This preserves established scalar variants when an additive safe payload is
//! introduced without forcing a wire-breaking enum migration.

use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};
use syn::{Attribute, Expr, Fields, Item, Lit, Meta, Type};

/// Prettier's print width, which the emitted lines must respect.
const PRINT_WIDTH: usize = 100;

/// Marker proving that a stale TypeScript file is owned by this generator.
const GENERATED_HEADER: &str = "// Generated by crates/project-tools from the Rust question model.";
/// Exact marker emitted before the project-tools package rename.
const LEGACY_GENERATED_HEADER: &str = "// Generated by crates/xtask from the Rust question model.";

/// One TypeScript declaration ready to be written out.
struct Generated {
    /// Type name, which is also the file stem.
    name: String,
    /// Names of other generated types this one references.
    dependencies: BTreeSet<String>,
    /// Doc comment lines, already stripped of the Rust `///` marker.
    docs: Vec<String>,
    /// The right-hand side of `export type <name> = ...`.
    body: String,
}

/// Reads every `.rs` file under `model_dir` and writes TypeScript into
/// `out_dir`.
///
/// Returns the number of types generated.
pub fn run(model_dir: &Path, out_dir: &Path) -> Result<usize> {
    let mut generated: Vec<Generated> = Vec::new();

    let mut source_paths: Vec<_> = fs::read_dir(model_dir)
        .with_context(|| format!("reading {}", model_dir.display()))?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "rs"))
        .collect();
    // Sorted so the output is identical run to run; generated files that
    // reorder themselves produce noisy diffs and hide real changes.
    source_paths.sort();

    for path in &source_paths {
        let source =
            fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
        let parsed =
            syn::parse_file(&source).with_context(|| format!("parsing {}", path.display()))?;

        for item in parsed.items {
            match item {
                Item::Struct(item) if is_exported(&item.vis, &item.attrs) => {
                    generated.push(
                        generate_struct(&item)
                            .with_context(|| format!("generating {}", item.ident))?,
                    );
                }
                Item::Enum(item) if is_exported(&item.vis, &item.attrs) => {
                    generated.push(
                        generate_enum(&item)
                            .with_context(|| format!("generating {}", item.ident))?,
                    );
                }
                Item::Const(item)
                    if matches!(item.vis, syn::Visibility::Public(_))
                        && matches!(*item.ty, syn::Type::Path(ref path) if path.path.is_ident("usize"))
                        && matches!(
                            &*item.expr,
                            syn::Expr::Lit(syn::ExprLit {
                                lit: syn::Lit::Int(_),
                                ..
                            })
                        ) =>
                {
                    let syn::Expr::Lit(syn::ExprLit {
                        lit: syn::Lit::Int(value),
                        ..
                    }) = &*item.expr
                    else {
                        unreachable!()
                    };
                    generated.push(Generated {
                        name: item.ident.to_string(),
                        dependencies: BTreeSet::new(),
                        docs: doc_lines(&item.attrs),
                        body: format!("__CONST__ {}", value.base10_digits()),
                    });
                }
                _ => {}
            }
        }
    }

    prepare_out_dir(out_dir)?;

    for type_definition in &generated {
        let path = out_dir.join(format!("{}.ts", type_definition.name));
        fs::write(&path, render(type_definition))
            .with_context(|| format!("writing {}", path.display()))?;
    }

    Ok(generated.len())
}

/// Removes stale owned TypeScript before writing the current complete set.
///
/// A dedicated output directory makes deletion safe, but the marker remains a
/// backstop: a hand-authored `.ts` file causes a loud failure instead of being
/// erased. Non-TypeScript files are left for their own generators.
fn prepare_out_dir(out_dir: &Path) -> Result<()> {
    fs::create_dir_all(out_dir).with_context(|| format!("creating {}", out_dir.display()))?;
    let entries =
        fs::read_dir(out_dir).with_context(|| format!("reading {}", out_dir.display()))?;

    for entry in entries {
        let path = entry
            .with_context(|| format!("reading an entry in {}", out_dir.display()))?
            .path();
        if path.extension().is_none_or(|extension| extension != "ts") {
            continue;
        }
        let source = fs::read_to_string(&path)
            .with_context(|| format!("checking generated marker in {}", path.display()))?;
        if !source.starts_with(GENERATED_HEADER) && !source.starts_with(LEGACY_GENERATED_HEADER) {
            bail!(
                "refusing to replace unowned TypeScript in generated output: {}",
                path.display()
            );
        }
        fs::remove_file(&path).with_context(|| format!("removing stale {}", path.display()))?;
    }

    Ok(())
}

/// Whether an item is a boundary type: public and serde-serializable.
fn is_exported(visibility: &syn::Visibility, attrs: &[Attribute]) -> bool {
    matches!(visibility, syn::Visibility::Public(_)) && derives_serde(attrs)
}

/// Whether the item derives `Serialize` or `Deserialize`.
fn derives_serde(attrs: &[Attribute]) -> bool {
    for attr in attrs {
        if !attr.path().is_ident("derive") {
            continue;
        }
        let mut found = false;
        // parse_nested_meta walks the comma-separated derive list.
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("Serialize") || meta.path.is_ident("Deserialize") {
                found = true;
            }
            Ok(())
        });
        if found {
            return true;
        }
    }
    false
}

/// Extracts `#[doc = "..."]` lines, stopping at a Rust example section.
///
/// Rust doc examples are Rust code. Copying them into a TypeScript file would
/// show a client developer `assert!` and `use` statements, so the text is cut
/// at the `# Examples` heading.
fn doc_lines(attrs: &[Attribute]) -> Vec<String> {
    let mut lines = Vec::new();
    for attr in attrs {
        if !attr.path().is_ident("doc") {
            continue;
        }
        let Meta::NameValue(name_value) = &attr.meta else {
            continue;
        };
        let Expr::Lit(literal) = &name_value.value else {
            continue;
        };
        let Lit::Str(text) = &literal.lit else {
            continue;
        };
        let line = text.value();
        let trimmed = line.trim();
        if trimmed.starts_with("# Examples") || trimmed.starts_with("# Example") {
            break;
        }
        lines.push(line.trim_end().to_string());
    }
    while lines.last().is_some_and(|line| line.trim().is_empty()) {
        lines.pop();
    }
    lines
}

/// Reads `#[serde(rename_all = "...")]` from a container's attributes.
///
/// On an enum this renames the *variants*. Fields inside variants follow
/// `rename_all_fields`, which serde treats as a separate rule.
fn rename_all(attrs: &[Attribute]) -> Option<String> {
    serde_string_value(attrs, "rename_all")
}

/// Reads `#[serde(rename_all_fields = "...")]` from an enum's attributes.
///
/// Reading this separately is what keeps the generated TypeScript agreeing
/// with the JSON serde actually produces. Applying the container's
/// `rename_all` to variant fields would emit camelCase names for fields serde
/// leaves in snake_case.
fn rename_all_fields(attrs: &[Attribute]) -> Option<String> {
    serde_string_value(attrs, "rename_all_fields")
}

/// Reads `#[serde(tag = "...")]` from an enum's attributes.
fn serde_tag(attrs: &[Attribute]) -> Option<String> {
    serde_string_value(attrs, "tag")
}

/// Reads one `#[serde(<key> = "<value>")]` string value.
fn serde_string_value(attrs: &[Attribute], key: &str) -> Option<String> {
    let mut found = None;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            // Consume the `= "..."` of every entry, whether or not it is the
            // one being looked for. Skipping it leaves the parser sitting on an
            // unexpected `=`, which ends the walk early: a `rename_all` that
            // follows `tag` would then be invisible.
            let is_target = meta.path.is_ident(key);
            if let Ok(value) = meta.value()
                && let Ok(syn::Lit::Str(text)) = value.parse::<syn::Lit>()
                && is_target
            {
                found = Some(text.value());
            }
            Ok(())
        });
        if found.is_some() {
            break;
        }
    }
    found
}

/// Whether a field or variant carries `#[serde(skip)]`.
fn is_skipped(attrs: &[Attribute]) -> bool {
    let mut skipped = false;
    for attr in attrs {
        if !attr.path().is_ident("serde") {
            continue;
        }
        let _ = attr.parse_nested_meta(|meta| {
            if meta.path.is_ident("skip") || meta.path.is_ident("skip_serializing") {
                skipped = true;
            }
            Ok(())
        });
    }
    skipped
}

/// Whether serde omits a field when its value is `None`.
///
/// The generated TypeScript must model this as an optional property rather
/// than `T | null`: the public JSON contract intentionally proves restricted
/// feedback fields are absent, not merely null.
fn skips_when_none(attrs: &[Attribute]) -> bool {
    serde_string_value(attrs, "skip_serializing_if").is_some_and(|value| value == "Option::is_none")
}

/// Applies a serde `rename_all` rule to one identifier.
///
/// Only the cases this repo uses are implemented. An unrecognized rule is an
/// error rather than a silent pass-through, because a silently unrenamed field
/// would produce TypeScript that does not match the JSON on the wire.
fn apply_rename(name: &str, rule: Option<&str>) -> Result<String> {
    match rule {
        None => Ok(name.to_string()),
        Some("camelCase") => Ok(to_camel_case(name)),
        Some("snake_case") => Ok(to_snake_case(name)),
        Some(other) => bail!("unsupported serde rename_all rule: {other}"),
    }
}

/// Converts `snake_case` or `UpperCamelCase` to `camelCase`.
fn to_camel_case(name: &str) -> String {
    let snake = to_snake_case(name);
    let mut out = String::with_capacity(snake.len());
    let mut capitalize_next = false;
    for character in snake.chars() {
        if character == '_' {
            capitalize_next = true;
        } else if capitalize_next {
            out.extend(character.to_uppercase());
            capitalize_next = false;
        } else {
            out.push(character);
        }
    }
    out
}

/// Converts `UpperCamelCase` to `snake_case`, leaving `snake_case` untouched.
fn to_snake_case(name: &str) -> String {
    let mut out = String::with_capacity(name.len() + 4);
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() {
            if index != 0 {
                out.push('_');
            }
            out.extend(character.to_lowercase());
        } else {
            out.push(character);
        }
    }
    out
}

/// Maps a Rust type to a TypeScript type, collecting referenced type names.
fn map_type(rust_type: &Type, dependencies: &mut BTreeSet<String>) -> Result<String> {
    let Type::Path(path) = rust_type else {
        bail!("unsupported type shape: only path types are mapped");
    };
    let Some(segment) = path.path.segments.last() else {
        bail!("type path with no segments");
    };
    let name = segment.ident.to_string();

    let arguments: Vec<&Type> = match &segment.arguments {
        syn::PathArguments::AngleBracketed(bracketed) => bracketed
            .args
            .iter()
            .filter_map(|arg| match arg {
                syn::GenericArgument::Type(inner) => Some(inner),
                _ => None,
            })
            .collect(),
        _ => Vec::new(),
    };

    let mapped = match name.as_str() {
        "String" | "str" | "Uuid" | "PathBuf" => "string".to_string(),
        "bool" => "boolean".to_string(),
        "u8" | "u16" | "u32" | "u64" | "usize" | "i8" | "i16" | "i32" | "i64" | "isize" | "f32"
        | "f64" | "NonZeroU64" => "number".to_string(),
        // Option<T> becomes `T | null`: serde writes `null` for None, so the
        // client sees null rather than a missing key.
        "Option" => {
            let inner = first_argument(&arguments, "Option", dependencies)?;
            format!("{inner} | null")
        }
        "Vec" | "BTreeSet" | "HashSet" | "VecDeque" => {
            let inner = first_argument(&arguments, &name, dependencies)?;
            format!("Array<{inner}>")
        }
        "BTreeMap" | "HashMap" => {
            if arguments.len() != 2 {
                bail!("{name} needs two type arguments");
            }
            let key = map_type(arguments[0], dependencies)?;
            let value = map_type(arguments[1], dependencies)?;
            format!("Record<{key}, {value}>")
        }
        _ => {
            dependencies.insert(name.clone());
            name
        }
    };
    Ok(mapped)
}

/// Maps the single type argument of a generic container.
fn first_argument(
    arguments: &[&Type],
    container: &str,
    dependencies: &mut BTreeSet<String>,
) -> Result<String> {
    let Some(inner) = arguments.first() else {
        bail!("{container} needs one type argument");
    };
    map_type(inner, dependencies)
}

/// Generates the declaration for a struct.
fn generate_struct(item: &syn::ItemStruct) -> Result<Generated> {
    let mut dependencies = BTreeSet::new();
    let rule = rename_all(&item.attrs);

    let body = match &item.fields {
        Fields::Unnamed(fields)
            if fields.unnamed.len() == 1
                && serde_string_value(&item.attrs, "into").as_deref() == Some("String") =>
        {
            "string".to_string()
        }
        // A newtype is an alias to its inner type, matching serde, which
        // serializes it transparently.
        Fields::Unnamed(fields) if fields.unnamed.len() == 1 => {
            map_type(&fields.unnamed[0].ty, &mut dependencies)?
        }
        Fields::Named(fields) => {
            let mut lines = Vec::new();
            for field in &fields.named {
                if is_skipped(&field.attrs) {
                    continue;
                }
                let Some(ident) = &field.ident else {
                    bail!("named field without an identifier");
                };
                let name = apply_rename(&ident.to_string(), rule.as_deref())?;
                let mapped = map_type(&field.ty, &mut dependencies)?;
                let optional = skips_when_none(&field.attrs);
                let mapped = if optional {
                    option_inner_type(&field.ty, &mut dependencies)?
                } else {
                    mapped
                };
                let marker = if optional { "?" } else { "" };
                lines.push(format!("  {name}{marker}: {mapped};"));
            }
            format!("{{\n{}\n}}", lines.join("\n"))
        }
        Fields::Unit => "Record<string, never>".to_string(),
        Fields::Unnamed(_) => bail!("tuple structs with more than one field are not mapped"),
    };

    Ok(Generated {
        name: item.ident.to_string(),
        dependencies,
        docs: doc_lines(&item.attrs),
        body,
    })
}

/// Maps the inner type of `Option<T>` for an omitted JSON field.
fn option_inner_type(rust_type: &Type, dependencies: &mut BTreeSet<String>) -> Result<String> {
    let Type::Path(path) = rust_type else {
        bail!("skip_serializing_if Option::is_none needs Option<T>");
    };
    let Some(segment) = path.path.segments.last() else {
        bail!("type path with no segments");
    };
    if segment.ident != "Option" {
        bail!("skip_serializing_if Option::is_none needs Option<T>");
    }
    let arguments: Vec<&Type> = match &segment.arguments {
        syn::PathArguments::AngleBracketed(bracketed) => bracketed
            .args
            .iter()
            .filter_map(|arg| match arg {
                syn::GenericArgument::Type(inner) => Some(inner),
                _ => None,
            })
            .collect(),
        _ => Vec::new(),
    };
    first_argument(&arguments, "Option", dependencies)
}

/// Generates the declaration for an enum.
fn generate_enum(item: &syn::ItemEnum) -> Result<Generated> {
    let mut dependencies = BTreeSet::new();
    let rule = rename_all(&item.attrs);
    // Variant fields follow their own serde rule; see rename_all_fields.
    let field_rule = rename_all_fields(&item.attrs);
    let tag = serde_tag(&item.attrs);

    let mut members = Vec::new();
    for variant in &item.variants {
        if is_skipped(&variant.attrs) {
            continue;
        }
        let name = apply_rename(&variant.ident.to_string(), rule.as_deref())?;
        match (&variant.fields, &tag) {
            (Fields::Unit, None) => members.push(format!("\"{name}\"")),
            (Fields::Unnamed(fields), None) if fields.unnamed.len() == 1 => {
                let mapped = map_type(&fields.unnamed[0].ty, &mut dependencies)?;
                members.push(format!("{{ {name}: {mapped} }}"));
            }
            (Fields::Named(fields), None) => {
                let mut lines = Vec::new();
                for field in &fields.named {
                    if is_skipped(&field.attrs) {
                        continue;
                    }
                    let Some(ident) = &field.ident else {
                        bail!("named field without an identifier");
                    };
                    let field_name = apply_rename(&ident.to_string(), field_rule.as_deref())?;
                    let mapped = map_type(&field.ty, &mut dependencies)?;
                    lines.push(format!("    {field_name}: {mapped};"));
                }
                members.push(format!("{{ {name}: {{\n{}\n  }} }}", lines.join("\n")));
            }
            (Fields::Unit, Some(tag_name)) => {
                members.push(format!("{{ {tag_name}: \"{name}\" }}"));
            }
            (Fields::Named(fields), Some(tag_name)) => {
                // Prettier indents the members of an object inside a union
                // member by six spaces and closes the brace at four, so the
                // generated text matches what `prettier --check` expects.
                let mut lines = vec![format!("      {tag_name}: \"{name}\";")];
                for field in &fields.named {
                    if is_skipped(&field.attrs) {
                        continue;
                    }
                    let Some(ident) = &field.ident else {
                        bail!("named field without an identifier");
                    };
                    let field_name = apply_rename(&ident.to_string(), field_rule.as_deref())?;
                    let mapped = map_type(&field.ty, &mut dependencies)?;
                    lines.push(format!("      {field_name}: {mapped};"));
                }
                members.push(format!("{{\n{}\n    }}", lines.join("\n")));
            }
            _ => bail!(
                "variant {}::{} has an unsupported shape",
                item.ident,
                variant.ident
            ),
        }
    }

    Ok(Generated {
        name: item.ident.to_string(),
        dependencies,
        docs: doc_lines(&item.attrs),
        body: join_union(&item.ident.to_string(), &members),
    })
}

/// Joins union members, wrapping the way Prettier would.
///
/// Prettier keeps a union on one line when it fits inside the print width and
/// otherwise puts each member on its own line with a leading `|`. Matching that
/// here is what lets the generated files pass `prettier --check` unchanged
/// instead of needing a reformat pass.
fn join_union(type_name: &str, members: &[String]) -> String {
    let single_line = members.join(" | ");
    let declaration_width = "export type ".len() + type_name.len() + " = ".len() + 1;
    if single_line.len() + declaration_width <= PRINT_WIDTH && !single_line.contains('\n') {
        return single_line;
    }
    if single_line.len() + 3 <= PRINT_WIDTH && !single_line.contains('\n') {
        return format!("\n  {single_line}");
    }
    let mut out = String::new();
    for member in members {
        let _ = write!(out, "\n  | {member}");
    }
    out
}

/// Renders one declaration as a complete TypeScript file.
fn render(type_definition: &Generated) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// Do not edit by hand; run ./build.sh (or cargo tools tsgen).\n");

    let mut imports: Vec<&String> = type_definition
        .dependencies
        .iter()
        .filter(|name| **name != type_definition.name)
        .collect();
    imports.sort();
    if !imports.is_empty() {
        out.push('\n');
        for import in imports {
            let _ = writeln!(out, "import type {{ {import} }} from \"./{import}\";");
        }
    }

    out.push('\n');
    if !type_definition.docs.is_empty() {
        out.push_str("/**\n");
        for line in &type_definition.docs {
            if line.trim().is_empty() {
                out.push_str(" *\n");
            } else {
                let _ = writeln!(out, " *{line}");
            }
        }
        out.push_str(" */\n");
    }

    if let Some(value) = type_definition.body.strip_prefix("__CONST__ ") {
        let _ = writeln!(
            out,
            "export const {} = {value} as const;",
            type_definition.name
        );
        return out;
    }
    // A wrapped union already starts with its own newline, so the space after
    // `=` would be trailing whitespace. Prettier strips that, and a file it
    // would reformat is a file that fails `prettier --check`.
    if type_definition.body.starts_with('\n') {
        let _ = writeln!(
            out,
            "export type {} ={};",
            type_definition.name, type_definition.body
        );
    } else {
        let _ = writeln!(
            out,
            "export type {} = {};",
            type_definition.name, type_definition.body
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temporary_output_dir(label: &str) -> std::path::PathBuf {
        let nonce = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("test clock should be after the Unix epoch")
            .as_nanos();
        std::env::temp_dir().join(format!("ple-tsgen-{label}-{}-{nonce}", std::process::id()))
    }

    #[test]
    fn output_cleanup_removes_stale_owned_types_but_refuses_authored_types() {
        let out_dir = temporary_output_dir("cleanup");
        fs::create_dir_all(&out_dir).expect("temporary output should be created");
        let stale = out_dir.join("Stale.ts");
        fs::write(
            &stale,
            format!("{GENERATED_HEADER}\nexport type Stale = string;\n"),
        )
        .expect("stale generated type should be written");

        prepare_out_dir(&out_dir).expect("owned stale output should be removable");
        assert!(!stale.exists());

        let legacy = out_dir.join("Legacy.ts");
        fs::write(
            &legacy,
            format!("{LEGACY_GENERATED_HEADER}\nexport type Legacy = string;\n"),
        )
        .expect("legacy generated type should be written");
        prepare_out_dir(&out_dir).expect("exact legacy output should be migrated");
        assert!(!legacy.exists());

        let authored = out_dir.join("Authored.ts");
        fs::write(&authored, "export type Authored = string;\n")
            .expect("authored fixture should be written");
        assert!(prepare_out_dir(&out_dir).is_err());
        assert!(authored.exists());

        fs::remove_dir_all(out_dir).expect("temporary output should be removed");
    }

    #[test]
    fn unit_enums_become_string_unions() {
        let item: syn::ItemEnum = syn::parse_quote! {
            #[derive(Serialize)]
            #[serde(rename_all = "camelCase")]
            pub enum Colour {
                DeepRed,
                Blue,
            }
        };
        let generated = generate_enum(&item).expect("generation should succeed");
        assert_eq!(generated.body, "\"deepRed\" | \"blue\"");
    }

    #[test]
    fn union_wrapping_accounts_for_the_declared_type_name() {
        let members = vec![
            "\"immediateFull\"".to_string(),
            "\"immediateCorrectness\"".to_string(),
            "\"deferred\"".to_string(),
            "\"onRelease\"".to_string(),
        ];

        assert!(join_union("FeedbackDisclosure", &members).starts_with("\n  \"immediateFull\""));
    }

    #[test]
    fn option_maps_to_a_nullable_union() {
        let item: syn::ItemStruct = syn::parse_quote! {
            #[derive(Serialize)]
            pub struct Holder {
                pub label: Option<String>,
            }
        };
        let generated = generate_struct(&item).expect("generation should succeed");
        assert!(generated.body.contains("label: string | null;"));
    }

    #[test]
    fn transparent_nonzero_u64_newtypes_use_their_numeric_wire_type() {
        let item: syn::ItemStruct = syn::parse_quote! {
            #[derive(Serialize)]
            #[serde(transparent)]
            pub struct PublicId(NonZeroU64);
        };
        let generated = generate_struct(&item).expect("generation should succeed");
        assert_eq!(generated.body, "number");
        assert!(generated.dependencies.is_empty());
    }

    #[test]
    fn omitted_option_becomes_an_optional_property() {
        let item: syn::ItemStruct = syn::parse_quote! {
            #[derive(Serialize)]
            #[serde(rename_all = "camelCase")]
            pub struct Holder {
                #[serde(skip_serializing_if = "Option::is_none")]
                pub secret: Option<String>,
            }
        };
        let generated = generate_struct(&item).expect("generation should succeed");
        assert!(generated.body.contains("secret?: string;"));
        assert!(!generated.body.contains("null"));
    }

    #[test]
    fn nonserializable_server_contract_is_not_emitted_to_typescript() {
        let model_dir = temporary_output_dir("private-model");
        let out_dir = temporary_output_dir("private-output");
        fs::create_dir_all(&model_dir).expect("temporary model directory should be created");
        fs::write(
            model_dir.join("feedback.rs"),
            "pub struct FeedbackContent { pub hidden: String }\n",
        )
        .expect("private feedback fixture should be written");

        run(&model_dir, &out_dir).expect("generation should accept private Rust types");
        assert!(
            !out_dir.join("FeedbackContent.ts").exists(),
            "a non-serializable server contract must not become a browser type"
        );

        fs::remove_dir_all(model_dir).expect("temporary model directory should be removed");
        fs::remove_dir_all(out_dir).expect("temporary output directory should be removed");
    }

    #[test]
    fn an_externally_tagged_newtype_variant_preserves_scalar_siblings() {
        let item: syn::ItemEnum = syn::parse_quote! {
            #[derive(Serialize)]
            #[serde(rename_all = "camelCase")]
            pub enum Shape {
                Unavailable,
                Available(Statistics),
            }
        };
        let generated = generate_enum(&item).expect("generation should support external tagging");
        assert_eq!(
            generated.body,
            "\"unavailable\" | { available: Statistics }"
        );
        assert!(generated.dependencies.contains("Statistics"));
    }

    #[test]
    fn newtype_structs_alias_their_inner_type() {
        let item: syn::ItemStruct = syn::parse_quote! {
            #[derive(Serialize)]
            pub struct Tags(Vec<String>);
        };
        let generated = generate_struct(&item).expect("generation should succeed");
        assert_eq!(generated.body, "Array<string>");
    }

    #[test]
    fn serde_string_newtypes_use_their_wire_type() {
        let item: syn::ItemStruct = syn::parse_quote! {
            #[derive(Serialize)]
            #[serde(try_from = "String", into = "String")]
            pub struct ExactDecimal(i64);
        };
        let generated = generate_struct(&item).expect("generation should succeed");
        assert_eq!(generated.body, "string");
    }
}
