// Generated by devel/generate_avatar_catalog.py. Do not edit by hand.

/// One closed PLE-provided avatar with exact source-asset evidence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProvidedAvatarCatalogEntry {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub asset_path: &'static str,
    pub asset_sha256: &'static str,
    pub is_selectable: bool,
}

/// The manifest order is canonical and all source bytes are SHA-256 evidenced.
pub const PROVIDED_AVATAR_CATALOG: &[ProvidedAvatarCatalogEntry] = &[
    ProvidedAvatarCatalogEntry {
        id: "amber-arch",
        name: "Amber arch",
        description: "Amber arch with two blue dots.",
        asset_path: "/assets/avatar_catalog/svg/amber-arch.svg",
        asset_sha256: "cc199a8e914cf3cd96b6a5bcd04110fed70e332e9addf9a0008d7acf7e4cf227",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "berry-bloom",
        name: "Berry bloom",
        description: "Berry circles around a bright center.",
        asset_path: "/assets/avatar_catalog/svg/berry-bloom.svg",
        asset_sha256: "eeab13136999db047f7e4e01ccd3eeda6840315b488a1a98be872bfc3d103ada",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "cobalt-circuit",
        name: "Cobalt circuit",
        description: "Cobalt blocks joined by a curved line.",
        asset_path: "/assets/avatar_catalog/svg/cobalt-circuit.svg",
        asset_sha256: "e0e5dcc64e4a37a5c6a379f4bb8c32e9df1eb668eae0155a72e3fed71bea23e7",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "coral-crossing",
        name: "Coral crossing",
        description: "Coral crossing bands and small squares.",
        asset_path: "/assets/avatar_catalog/svg/coral-crossing.svg",
        asset_sha256: "3d0b1965b55749c7e011d738ba00389ad1be03516d8fff393546dc6ec8b16ddf",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "fern-facet",
        name: "Fern facet",
        description: "Green facets in a rounded tile.",
        asset_path: "/assets/avatar_catalog/svg/fern-facet.svg",
        asset_sha256: "7004e480ee40cd24e52fb9e86ddec9a63d2369e7cc9fa8ecd4ff3d998777f2de",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "golden-garden",
        name: "Golden garden",
        description: "Golden petals with green leaves.",
        asset_path: "/assets/avatar_catalog/svg/golden-garden.svg",
        asset_sha256: "ac28141bdfddd1e5bf248337c63e7b5682d7f51629ec1571c04f97fa7052c635",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "indigo-island",
        name: "Indigo island",
        description: "Indigo oval above a small wave.",
        asset_path: "/assets/avatar_catalog/svg/indigo-island.svg",
        asset_sha256: "4566da9fdc624bf191b1333dc60eff0ebc509b006ade23ee9027c65c24502484",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "mint-mosaic",
        name: "Mint mosaic",
        description: "Mint and blue mosaic squares.",
        asset_path: "/assets/avatar_catalog/svg/mint-mosaic.svg",
        asset_sha256: "4453aa78a9f97ac16fc28baada2dff7d3abbd728c0aa4f3bfac51f21e9998b27",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "plum-pulse",
        name: "Plum pulse",
        description: "Plum rings around a warm dot.",
        asset_path: "/assets/avatar_catalog/svg/plum-pulse.svg",
        asset_sha256: "618752449366b635d2f58848c921b72a7aab32abe2540b25eb8233a9577a38eb",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "saffron-spark",
        name: "Saffron spark",
        description: "Saffron star shapes on navy.",
        asset_path: "/assets/avatar_catalog/svg/saffron-spark.svg",
        asset_sha256: "e2ff8a16d2ec89c5be7eac5078a5ff7ec254a363953746db818ff3cadc810a65",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "sky-stack",
        name: "Sky stack",
        description: "Blue blocks stacked in balance.",
        asset_path: "/assets/avatar_catalog/svg/sky-stack.svg",
        asset_sha256: "0095a9c4edec2663eec7630935ce357cc50e712cabb1e0aa196abd240b01a3f8",
        is_selectable: true,
    },
    ProvidedAvatarCatalogEntry {
        id: "teal-trail",
        name: "Teal trail",
        description: "Teal path through peach circles.",
        asset_path: "/assets/avatar_catalog/svg/teal-trail.svg",
        asset_sha256: "dbe77cac735abeb52688026538f9e16602981fb138f2dd3ef66a0c01c3270c7c",
        is_selectable: true,
    },
];
