-- ENABLE / FORCE ROW LEVEL SECURITY and CREATE POLICY.

\ir 60_policies/accounts.sql
\ir 60_policies/authentication.sql
\ir 60_policies/content_classification.sql
\ir 60_policies/content_classification_operations.sql
\ir 60_policies/question_lineages.sql
\ir 60_policies/question_pools.sql
\ir 60_policies/question_stewardship.sql
\ir 60_policies/question_pool_stewardship.sql
\ir 60_policies/library_discussions.sql
\ir 60_policies/question_watch_notifications.sql
\ir 60_policies/object_records.sql
\ir 60_policies/question_authoring_state.sql
\ir 60_policies/draft_question_assets.sql
\ir 60_policies/question_assets.sql
\ir 60_policies/blueprints.sql
\ir 60_policies/blueprint_change_proposals.sql
\ir 60_policies/blueprint_stewardship.sql
\ir 60_policies/course_core.sql
\ir 60_policies/course_retention.sql
\ir 60_policies/course_membership.sql
\ir 60_policies/course_roster.sql
\ir 60_policies/support_repair_capability.sql
\ir 60_policies/course_operations.sql
\ir 60_policies/course_media.sql
\ir 60_policies/profile_media.sql
\ir 60_policies/assessments.sql
\ir 60_policies/question_bloom.sql
\ir 60_policies/assessment_templates.sql
\ir 60_policies/course_blueprint_publication.sql
\ir 60_policies/assessment_attempts.sql
\ir 60_policies/assessment_attempt_interaction.sql
\ir 60_policies/assessment_attempt_presentation.sql
\ir 60_policies/delivery_backends.sql
\ir 60_policies/jobs.sql
\ir 60_policies/grading.sql
\ir 60_policies/archived_student_work_recovery.sql
\ir 60_policies/statistics.sql
\ir 60_policies/course_retention_transitions.sql
\ir 60_policies/course_retention_notifications.sql
\ir 60_policies/corrections.sql
\ir 60_policies/unrelease.sql
