-- Table and routine privileges.

RESET ROLE;
\ir 70_grants/foundation_roles.sql
\ir 70_grants/public_references.sql
\ir 70_grants/accounts.sql
\ir 70_grants/authentication.sql
\ir 70_grants/authorization.sql
\ir 70_grants/content_classification.sql
\ir 70_grants/content_classification_operations.sql
\ir 70_grants/question_lineages.sql
\ir 70_grants/question_pools.sql
\ir 70_grants/question_stewardship.sql
\ir 70_grants/question_pool_stewardship.sql
\ir 70_grants/library_discussions.sql
\ir 70_grants/library_discussion_operations.sql
\ir 70_grants/question_watch_notifications.sql
\ir 70_grants/object_records.sql
\ir 70_grants/question_authoring_state.sql
\ir 70_grants/draft_question_assets.sql
\ir 70_grants/question_publication_operations.sql
\ir 70_grants/question_authoring_operations.sql
\ir 70_grants/published_question_metadata_operations.sql
\ir 70_grants/question_assets.sql
\ir 70_grants/blueprints.sql
\ir 70_grants/blueprint_operations.sql
\ir 70_grants/blueprint_history.sql
\ir 70_grants/blueprint_pools.sql
\ir 70_grants/blueprint_lineage.sql
\ir 70_grants/blueprint_change_proposals.sql
\ir 70_grants/blueprint_stewardship.sql
\ir 70_grants/blueprint_revision_integrity.sql
\ir 70_grants/course_core.sql
\ir 70_grants/course_retention.sql
\ir 70_grants/course_membership.sql
\ir 70_grants/course_roster.sql
\ir 70_grants/support_repair_capability.sql
\ir 70_grants/course_operations.sql
\ir 70_grants/course_media.sql
\ir 70_grants/profile_media.sql
\ir 70_grants/assessments.sql
\ir 70_grants/assessment_policy_snapshot.sql
\ir 70_grants/assessment_entry_snapshot.sql
\ir 70_grants/question_library_operations.sql
\ir 70_grants/question_bloom.sql
\ir 70_grants/assessment_creation.sql
\ir 70_grants/assessment_deadline_sync.sql
\ir 70_grants/assessment_templates.sql
\ir 70_grants/assessment_template_copy.sql
\ir 70_grants/assessment_release_validation.sql
\ir 70_grants/assessment_pool_forks.sql
\ir 70_grants/assessment_pool_selection.sql
\ir 70_grants/course_blueprint_adoption.sql
\ir 70_grants/course_blueprint_publication.sql
\ir 70_grants/assessment_operations.sql
\ir 70_grants/assessment_blueprint_updates.sql
\ir 70_grants/assessment_student_view.sql
\ir 70_grants/assessment_attempts.sql
\ir 70_grants/assessment_attempt_interaction.sql
\ir 70_grants/assessment_attempt_presentation.sql
\ir 70_grants/assessment_attempt_operations.sql
\ir 70_grants/assessment_attempt_operations_api.sql
\ir 70_grants/assessment_student_time_accommodation.sql
\ir 70_grants/assessment_attempt_access.sql
\ir 70_grants/delivery_backends.sql
\ir 70_grants/delivery.sql
\ir 70_grants/jobs.sql
\ir 70_grants/question_asset_operations.sql
\ir 70_grants/draft_asset_publication_operations.sql
\ir 70_grants/grading.sql
\ir 70_grants/grading_access.sql
\ir 70_grants/student_assessment_landing.sql
\ir 70_grants/assessment_attempt_history.sql
\ir 70_grants/archived_student_work_recovery.sql
\ir 70_grants/statistics.sql
\ir 70_grants/course_retention_transitions.sql
\ir 70_grants/course_retention_notifications.sql
\ir 70_grants/corrections.sql
\ir 70_grants/unrelease.sql
\ir 70_grants/api_compatibility.sql
