-- Canonical PLE structural installation manifest.
--
-- The administrator invokes this file with PostgreSQL 17 `psql -X`,
-- `--set=ON_ERROR_STOP=1`, and `--single-transaction`.  Keep this manifest
-- limited to ordered includes: each module owns its current DDL directly.
\set ON_ERROR_STOP on

\ir foundation_roles.sql
\ir public_references.sql
\ir accounts.sql
\ir authentication.sql
\ir authorization.sql
\ir content_classification.sql
\ir content_classification_operations.sql
\ir question_lineages.sql
\ir question_pools.sql
\ir question_stewardship.sql
\ir question_pool_stewardship.sql
\ir library_discussions.sql
\ir library_discussion_operations.sql
\ir question_watch_notifications.sql
\ir object_records.sql
\ir question_authoring_state.sql
\ir draft_question_assets.sql
\ir question_publication_operations.sql
\ir question_authoring_operations.sql
\ir published_question_metadata_operations.sql
\ir question_assets.sql
\ir blueprints.sql
\ir blueprint_operations.sql
\ir blueprint_history.sql
\ir blueprint_pools.sql
\ir blueprint_lineage.sql
\ir blueprint_change_proposals.sql
\ir blueprint_stewardship.sql
\ir blueprint_revision_integrity.sql
\ir course_core.sql
\ir course_retention.sql
\ir course_membership.sql
\ir course_roster.sql
\ir support_repair_capability.sql
\ir course_operations.sql
\ir course_media.sql
\ir profile_media.sql
\ir assessments.sql
\ir question_library_operations.sql
\ir question_bloom.sql
\ir assessment_creation.sql
\ir assessment_deadline_sync.sql
\ir assessment_templates.sql
\ir assessment_template_copy.sql
\ir assessment_release_validation.sql
\ir assessment_pool_forks.sql
\ir assessment_pool_selection.sql
\ir course_blueprint_adoption.sql
\ir course_blueprint_publication.sql
\ir assessment_operations.sql
\ir assessment_blueprint_updates.sql
\ir assessment_student_view.sql
\ir assessment_attempts.sql
\ir assessment_attempt_interaction.sql
\ir assessment_attempt_presentation.sql
\ir assessment_attempt_operations.sql
\ir assessment_attempt_finalization.sql
\ir assessment_attempt_operations_api.sql
\ir assessment_student_time_accommodation.sql
\ir assessment_attempt_access.sql
\ir delivery_backends.sql
\ir delivery.sql
\ir jobs.sql
\ir question_asset_operations.sql
\ir draft_asset_publication_operations.sql
\ir grading.sql
\ir grading_access.sql
\ir student_assessment_landing.sql
\ir assessment_attempt_history.sql
\ir archived_student_work_recovery.sql
\ir statistics.sql
\ir course_retention_transitions.sql
\ir course_retention_notifications.sql
\ir corrections.sql
\ir cross_domain_constraints.sql
\ir unrelease.sql
\ir api_compatibility.sql
