-- Canonical PLE structural installation manifest.
--
-- The administrator invokes this file with PostgreSQL `psql -X`,
-- `--set=ON_ERROR_STOP=1`, and `--single-transaction`. Keep this
-- manifest limited to ordered includes by kind, then domain.
\set ON_ERROR_STOP on

\ir 00_roles.sql
\ir 10_types.sql
\ir 15_table_check_functions.sql
\ir 20_tables/account.sql
\ir 20_tables/authentication.sql
\ir 20_tables/content_classification.sql
\ir 20_tables/published_question.sql
\ir 20_tables/question_pool.sql
\ir 20_tables/object_record.sql
\ir 20_tables/question_authoring.sql
\ir 20_tables/question_images.sql
\ir 20_tables/library_discussion.sql
\ir 20_tables/library_watch.sql
\ir 20_tables/blueprint_course.sql
\ir 20_tables/course_instance.sql
\ir 20_tables/course_membership.sql
\ir 20_tables/course_media.sql
\ir 20_tables/profile_media.sql
\ir 20_tables/assessment.sql
\ir 20_tables/assessment_template.sql
\ir 20_tables/assessment_attempt.sql
\ir 20_tables/statistics.sql
\ir 20_tables/retention.sql
\ir 20_tables/support_repair.sql
\ir 20_tables/jobs.sql
\ir 20_tables/corrections.sql
\ir 20_tables/audit.sql
\ir 22_reference_grants.sql
\ir 30_constraints.sql
\ir 40_indexes.sql
\ir 50_functions/public_ids.sql
\ir 50_functions/accounts.sql
\ir 50_functions/authentication.sql
\ir 50_functions/authorization.sql
\ir 50_functions/content_classification_operations.sql
\ir 50_functions/question_lineages.sql
\ir 50_functions/question_pools.sql
\ir 50_functions/question_stewardship.sql
\ir 50_functions/question_pool_stewardship.sql
\ir 50_functions/library_discussion_operations.sql
\ir 50_functions/question_watch_notifications.sql
\ir 50_functions/object_records.sql
\ir 50_functions/question_authoring_state.sql
\ir 50_functions/draft_question_images.sql
\ir 50_functions/question_publication_operations.sql
\ir 50_functions/question_authoring_operations.sql
\ir 50_functions/published_question_metadata_operations.sql
\ir 50_functions/question_images.sql
\ir 50_functions/blueprints.sql
\ir 50_functions/blueprint_operations.sql
\ir 50_functions/blueprint_history.sql
\ir 50_functions/blueprint_pools.sql
\ir 50_functions/blueprint_lineage.sql
\ir 50_functions/blueprint_change_proposals.sql
\ir 50_functions/blueprint_stewardship.sql
\ir 50_functions/blueprint_revision_integrity.sql
\ir 50_functions/course_core.sql
\ir 50_functions/course_retention.sql
\ir 50_functions/course_membership.sql
\ir 50_functions/course_roster.sql
\ir 50_functions/support_repair_capability.sql
\ir 50_functions/course_operations.sql
\ir 50_functions/course_media.sql
\ir 50_functions/profile_media.sql
\ir 50_functions/assessment_policy_snapshot.sql
\ir 50_functions/assessment_entry_snapshot.sql
\ir 50_functions/assessments.sql
\ir 50_functions/question_library_operations.sql
\ir 50_functions/question_bloom.sql
\ir 50_functions/assessment_creation.sql
\ir 50_functions/assessment_deadline_sync.sql
\ir 50_functions/assessment_templates.sql
\ir 50_functions/assessment_template_copy.sql
\ir 50_functions/assessment_release_validation.sql
\ir 50_functions/assessment_pool_forks.sql
\ir 50_functions/assessment_pool_selection.sql
\ir 50_functions/course_blueprint_adoption.sql
\ir 50_functions/course_blueprint_publication.sql
\ir 50_functions/assessment_operations.sql
\ir 50_functions/assessment_blueprint_updates.sql
\ir 50_functions/assessment_student_view.sql
\ir 50_functions/assessment_attempts.sql
\ir 50_functions/assessment_attempt_interaction.sql
\ir 50_functions/assessment_attempt_presentation.sql
\ir 50_functions/assessment_attempt_operations.sql
\ir 50_functions/assessment_attempt_start.sql
\ir 50_functions/assessment_attempt_finalization.sql
\ir 50_functions/assessment_attempt_operations_api.sql
\ir 50_functions/assessment_student_time_accommodation.sql
\ir 50_functions/assessment_attempt_access.sql
\ir 50_functions/delivery_backends.sql
\ir 50_functions/delivery.sql
\ir 50_functions/jobs.sql
\ir 50_functions/question_image_operations.sql
\ir 50_functions/draft_question_image_publication_operations.sql
\ir 50_functions/grading.sql
\ir 50_functions/grading_access.sql
\ir 50_functions/student_assessment_landing.sql
\ir 50_functions/student_course_attempt_history.sql
\ir 50_functions/student_course_response_stats.sql
\ir 50_functions/assessment_attempt_history.sql
\ir 50_functions/archived_student_work_recovery.sql
\ir 50_functions/statistics.sql
\ir 50_functions/course_retention_transitions.sql
\ir 50_functions/course_retention_notifications.sql
\ir 50_functions/corrections.sql
\ir 50_functions/unrelease.sql
\ir 50_functions/api_compatibility.sql
\ir 60_policies.sql
\ir 70_grants.sql
