-- Generated by devel/generate_avatar_catalog.py. Do not edit by hand.
-- This runs after ple_data.provided_avatar exists.
-- Removed manifest IDs remain rows with their recorded checksum and is_selectable = false.
SET LOCAL ROLE ple_data_owner;
INSERT INTO ple_data.provided_avatar
    (provided_avatar_id, asset_sha256, is_selectable)
VALUES
    ('amber-arch', 'cc199a8e914cf3cd96b6a5bcd04110fed70e332e9addf9a0008d7acf7e4cf227', true),
    ('berry-bloom', 'eeab13136999db047f7e4e01ccd3eeda6840315b488a1a98be872bfc3d103ada', true),
    ('cobalt-circuit', 'e0e5dcc64e4a37a5c6a379f4bb8c32e9df1eb668eae0155a72e3fed71bea23e7', true),
    ('coral-crossing', '3d0b1965b55749c7e011d738ba00389ad1be03516d8fff393546dc6ec8b16ddf', true),
    ('fern-facet', '7004e480ee40cd24e52fb9e86ddec9a63d2369e7cc9fa8ecd4ff3d998777f2de', true),
    ('golden-garden', 'ac28141bdfddd1e5bf248337c63e7b5682d7f51629ec1571c04f97fa7052c635', true),
    ('indigo-island', '4566da9fdc624bf191b1333dc60eff0ebc509b006ade23ee9027c65c24502484', true),
    ('mint-mosaic', '4453aa78a9f97ac16fc28baada2dff7d3abbd728c0aa4f3bfac51f21e9998b27', true),
    ('plum-pulse', '618752449366b635d2f58848c921b72a7aab32abe2540b25eb8233a9577a38eb', true),
    ('saffron-spark', 'e2ff8a16d2ec89c5be7eac5078a5ff7ec254a363953746db818ff3cadc810a65', true),
    ('sky-stack', '0095a9c4edec2663eec7630935ce357cc50e712cabb1e0aa196abd240b01a3f8', true),
    ('teal-trail', 'dbe77cac735abeb52688026538f9e16602981fb138f2dd3ef66a0c01c3270c7c', true)
ON CONFLICT (provided_avatar_id) DO UPDATE
SET asset_sha256 = EXCLUDED.asset_sha256,
    is_selectable = EXCLUDED.is_selectable
WHERE ple_data.provided_avatar.asset_sha256 IS DISTINCT FROM EXCLUDED.asset_sha256
   OR ple_data.provided_avatar.is_selectable IS DISTINCT FROM EXCLUDED.is_selectable;

-- Retire omitted catalog IDs without deleting their historical identity or checksum.
UPDATE ple_data.provided_avatar
SET is_selectable = false
WHERE is_selectable
  AND provided_avatar_id NOT IN (
    'amber-arch',
    'berry-bloom',
    'cobalt-circuit',
    'coral-crossing',
    'fern-facet',
    'golden-garden',
    'indigo-island',
    'mint-mosaic',
    'plum-pulse',
    'saffron-spark',
    'sky-stack',
    'teal-trail'
);
