-- WP-PROF-T4 instructor-owned rehearsal archive; Rust verifies canonical hashes.
BEGIN;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ple_rehearsal_broker') THEN
        CREATE ROLE ple_rehearsal_broker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
            NOINHERIT NOBYPASSRLS;
    END IF;
END
$$;
ALTER ROLE ple_rehearsal_broker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE
    NOINHERIT NOBYPASSRLS;
REVOKE ALL ON SCHEMA public FROM ple_rehearsal_broker;
GRANT USAGE ON SCHEMA public TO ple_rehearsal_broker;
-- Rehearsal evidence is canonical Unix milliseconds, selected by PostgreSQL.
CREATE FUNCTION public.ple_rehearsal_now() RETURNS timestamp with time zone LANGUAGE sql STABLE SET search_path TO 'pg_catalog', 'public', pg_temp AS $$ SELECT date_trunc('milliseconds', transaction_timestamp()) $$;
-- App-facing milliseconds use this broker-owned definer capability; the inner timestamp stays broker-private.
CREATE FUNCTION public.ple_rehearsal_now_millis() RETURNS bigint
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$ SELECT (extract(epoch FROM public.ple_rehearsal_now()) * 1000)::bigint $$;
CREATE FUNCTION public.ple_rehearsal_timestamp_from_millis(p_millis bigint)
    RETURNS timestamp with time zone LANGUAGE sql IMMUTABLE STRICT SET search_path TO 'pg_catalog', 'public', pg_temp AS $$ SELECT timestamptz 'epoch' + p_millis * interval '1 millisecond' $$;
-- v1 JSONB admission uses PostgreSQL's deterministic canonical text representation.
CREATE FUNCTION public.ple_rehearsal_jsonb_bytes(p_value jsonb) RETURNS bigint LANGUAGE sql IMMUTABLE STRICT SET search_path TO 'pg_catalog', 'public', pg_temp AS $$ SELECT octet_length(p_value::text) $$;
CREATE TABLE public.rehearsal_run (
    tenant_id uuid NOT NULL,
    rehearsal_run_id uuid NOT NULL,
    rehearsal_reference bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    course_id uuid NOT NULL,
    assignment_id uuid NOT NULL,
    assignment_reference integer NOT NULL,
    direct_instructor_membership_id uuid NOT NULL,
    actor_id uuid NOT NULL,
    assignment_revision bigint NOT NULL,
    subject_payload jsonb NOT NULL,
    subject_fingerprint bytea NOT NULL,
    lifecycle text NOT NULL DEFAULT 'active',
    started_at timestamp with time zone NOT NULL DEFAULT public.ple_rehearsal_now(),
    updated_at timestamp with time zone NOT NULL DEFAULT public.ple_rehearsal_now(),
    terminal_at timestamp with time zone,
    evidence_head_digest bytea NOT NULL,
    evidence_length bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (tenant_id, rehearsal_run_id),
    UNIQUE (tenant_id, rehearsal_reference),
    CONSTRAINT rehearsal_run_reference_check CHECK (rehearsal_reference BETWEEN 1 AND 2147483647),
    CONSTRAINT rehearsal_run_assignment_reference_check CHECK (assignment_reference > 0),
    CONSTRAINT rehearsal_run_assignment_revision_check CHECK (assignment_revision > 0),
    CONSTRAINT rehearsal_run_subject_shape_check CHECK (jsonb_typeof(subject_payload) = 'object' AND public.ple_rehearsal_jsonb_bytes(subject_payload) <= 65536),
    CONSTRAINT rehearsal_run_subject_fingerprint_check CHECK (octet_length(subject_fingerprint) = 32),
    CONSTRAINT rehearsal_run_evidence_head_check CHECK (octet_length(evidence_head_digest) = 32),
    CONSTRAINT rehearsal_run_evidence_length_check CHECK (evidence_length BETWEEN 0 AND 4294967295),
    CONSTRAINT rehearsal_run_lifecycle_check CHECK (lifecycle IN (
        'active', 'completed', 'discardedByInstructor', 'discardedByNewSubject',
        'discardedStaleRevision', 'discardedSourceContextRemoved'
    )),
    CONSTRAINT rehearsal_run_terminal_shape_check CHECK (
        (lifecycle = 'active' AND terminal_at IS NULL)
        OR (lifecycle <> 'active' AND terminal_at IS NOT NULL)
    )
);
CREATE UNIQUE INDEX rehearsal_run_one_active_owner_key
    ON public.rehearsal_run (tenant_id, course_id, assignment_id, direct_instructor_membership_id)
    WHERE lifecycle = 'active';
CREATE INDEX rehearsal_run_assignment_active_idx
    ON public.rehearsal_run (tenant_id, assignment_id, rehearsal_run_id)
    WHERE lifecycle = 'active';
CREATE INDEX rehearsal_run_course_active_idx
    ON public.rehearsal_run (tenant_id, course_id, rehearsal_run_id)
    WHERE lifecycle = 'active';
CREATE INDEX rehearsal_run_active_membership_idx
    ON public.rehearsal_run (tenant_id, direct_instructor_membership_id, rehearsal_run_id)
    WHERE lifecycle = 'active';
CREATE TABLE public.rehearsal_frozen_item (
    tenant_id uuid NOT NULL,
    rehearsal_run_id uuid NOT NULL,
    attempt_id uuid NOT NULL,
    problem_id uuid NOT NULL,
    version_id uuid NOT NULL,
    response_definition jsonb NOT NULL,
    response_schema_digest bytea NOT NULL,
    canonical_content_digest bytea NOT NULL,
    frozen_at timestamp with time zone NOT NULL,
    PRIMARY KEY (tenant_id, rehearsal_run_id, attempt_id),
    FOREIGN KEY (tenant_id, rehearsal_run_id)
        REFERENCES public.rehearsal_run (tenant_id, rehearsal_run_id) ON DELETE RESTRICT,
    CONSTRAINT rehearsal_frozen_item_response_shape_check CHECK (jsonb_typeof(response_definition) = 'object' AND public.ple_rehearsal_jsonb_bytes(response_definition) <= 262144),
    CONSTRAINT rehearsal_frozen_item_schema_digest_check CHECK (octet_length(response_schema_digest) = 32),
    CONSTRAINT rehearsal_frozen_item_content_digest_check CHECK (octet_length(canonical_content_digest) = 32)
);
CREATE TABLE public.rehearsal_evidence (
    tenant_id uuid NOT NULL,
    rehearsal_run_id uuid NOT NULL,
    sequence bigint NOT NULL,
    kind text NOT NULL,
    previous_digest bytea NOT NULL,
    entry_digest bytea NOT NULL,
    payload jsonb NOT NULL,
    payload_digest bytea NOT NULL,
    recorded_at timestamp with time zone NOT NULL,
    PRIMARY KEY (tenant_id, rehearsal_run_id, sequence),
    UNIQUE (tenant_id, rehearsal_run_id, entry_digest),
    UNIQUE (tenant_id, rehearsal_run_id, sequence, entry_digest),
    FOREIGN KEY (tenant_id, rehearsal_run_id)
        REFERENCES public.rehearsal_run (tenant_id, rehearsal_run_id) ON DELETE RESTRICT,
    CONSTRAINT rehearsal_evidence_sequence_check CHECK (sequence BETWEEN 1 AND 4294967295),
    CONSTRAINT rehearsal_evidence_kind_check CHECK (kind IN ('frozenItem', 'acceptedSubmission')),
    CONSTRAINT rehearsal_evidence_previous_digest_check CHECK (octet_length(previous_digest) = 32),
    CONSTRAINT rehearsal_evidence_entry_digest_check CHECK (octet_length(entry_digest) = 32),
    CONSTRAINT rehearsal_evidence_payload_shape_check CHECK (jsonb_typeof(payload) = 'object' AND public.ple_rehearsal_jsonb_bytes(payload) <= (CASE kind WHEN 'frozenItem' THEN 263168 WHEN 'acceptedSubmission' THEN 395264 ELSE 0 END)),
    CONSTRAINT rehearsal_evidence_payload_digest_check CHECK (octet_length(payload_digest) = 32)
);
CREATE TABLE public.rehearsal_submission_claim_root (
    tenant_id uuid NOT NULL,
    rehearsal_run_id uuid NOT NULL,
    claim_id uuid NOT NULL,
    idempotency_key text NOT NULL,
    attempt_id uuid NOT NULL,
    request_fingerprint bytea NOT NULL,
    sealed_request jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT public.ple_rehearsal_now(),
    PRIMARY KEY (tenant_id, rehearsal_run_id, claim_id),
    UNIQUE (tenant_id, rehearsal_run_id, idempotency_key),
    UNIQUE (tenant_id, rehearsal_run_id, claim_id, attempt_id),
    FOREIGN KEY (tenant_id, rehearsal_run_id)
        REFERENCES public.rehearsal_run (tenant_id, rehearsal_run_id) ON DELETE RESTRICT,
    CONSTRAINT rehearsal_claim_root_key_check CHECK (
        char_length(idempotency_key) BETWEEN 1 AND 128
        AND idempotency_key !~ '[[:cntrl:]]'
    ),
    CONSTRAINT rehearsal_claim_root_fingerprint_check CHECK (octet_length(request_fingerprint) = 32),
    CONSTRAINT rehearsal_claim_root_sealed_shape_check CHECK (jsonb_typeof(sealed_request) = 'object' AND public.ple_rehearsal_jsonb_bytes(sealed_request) <= 393728)
);
CREATE TABLE public.rehearsal_submission_claim_event (
    tenant_id uuid NOT NULL,
    rehearsal_run_id uuid NOT NULL,
    claim_id uuid NOT NULL,
    sequence bigint NOT NULL,
    operation_id uuid NOT NULL,
    generation bigint NOT NULL,
    phase text NOT NULL,
    abandonment_reason text,
    accepted_evidence_sequence bigint,
    accepted_evidence_digest bytea,
    receipt_digest bytea,
    recorded_at timestamp with time zone NOT NULL DEFAULT public.ple_rehearsal_now(),
    PRIMARY KEY (tenant_id, rehearsal_run_id, claim_id, sequence),
    FOREIGN KEY (tenant_id, rehearsal_run_id, claim_id)
        REFERENCES public.rehearsal_submission_claim_root (tenant_id, rehearsal_run_id, claim_id)
        ON DELETE RESTRICT,
    FOREIGN KEY (tenant_id, rehearsal_run_id, accepted_evidence_sequence, accepted_evidence_digest)
        REFERENCES public.rehearsal_evidence (tenant_id, rehearsal_run_id, sequence, entry_digest)
        ON DELETE RESTRICT,
    CONSTRAINT rehearsal_claim_event_sequence_check CHECK (sequence BETWEEN 1 AND 4294967295),
    CONSTRAINT rehearsal_claim_event_generation_check CHECK (generation BETWEEN 1 AND 4294967295),
    CONSTRAINT rehearsal_claim_event_phase_check CHECK (phase IN (
        'prepared', 'gradingDispatched', 'completed', 'abandonedBeforeDispatch',
        'revokedTerminalLifecycle', 'revokedStaleRevision', 'revokedSourceContextRemoved'
    )),
    CONSTRAINT rehearsal_claim_event_completion_material_check CHECK (
        (phase = 'completed' AND abandonment_reason IS NULL
         AND accepted_evidence_sequence IS NOT NULL AND accepted_evidence_digest IS NOT NULL
         AND receipt_digest IS NOT NULL AND octet_length(accepted_evidence_digest) = 32
         AND octet_length(receipt_digest) = 32)
        OR (phase = 'abandonedBeforeDispatch' AND abandonment_reason IN (
            'localPreparationFailed', 'nativeBackendAdmissionRejected',
            'trustedRendererAdmissionRejected'
        )
            AND accepted_evidence_sequence IS NULL AND accepted_evidence_digest IS NULL
            AND receipt_digest IS NULL)
        OR (phase NOT IN ('completed', 'abandonedBeforeDispatch') AND abandonment_reason IS NULL
            AND accepted_evidence_sequence IS NULL AND accepted_evidence_digest IS NULL
            AND receipt_digest IS NULL)
    )
);
CREATE TABLE public.rehearsal_submission_receipt (
    tenant_id uuid NOT NULL,
    rehearsal_run_id uuid NOT NULL,
    claim_id uuid NOT NULL,
    outcome_projection jsonb NOT NULL,
    receipt_digest bytea NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT public.ple_rehearsal_now(),
    PRIMARY KEY (tenant_id, rehearsal_run_id, claim_id),
    FOREIGN KEY (tenant_id, rehearsal_run_id, claim_id)
        REFERENCES public.rehearsal_submission_claim_root (tenant_id, rehearsal_run_id, claim_id)
        ON DELETE RESTRICT,
    CONSTRAINT rehearsal_receipt_projection_shape_check CHECK (jsonb_typeof(outcome_projection) = 'object' AND public.ple_rehearsal_jsonb_bytes(outcome_projection) <= 394240),
    CONSTRAINT rehearsal_receipt_digest_check CHECK (octet_length(receipt_digest) = 32)
);
-- Aggregate head makes a complete rehash visible to Store verification.
CREATE FUNCTION public.ple_reject_rehearsal_append_only_mutation() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
BEGIN
    RAISE EXCEPTION 'rehearsal evidence and claim records are append-only' USING ERRCODE = '55000';
END
$$;
CREATE FUNCTION public.ple_guard_rehearsal_run_update() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
BEGIN
    IF (NEW.tenant_id, NEW.rehearsal_run_id, NEW.rehearsal_reference, NEW.course_id,
        NEW.assignment_id, NEW.assignment_reference, NEW.direct_instructor_membership_id,
        NEW.actor_id, NEW.assignment_revision, NEW.subject_payload, NEW.subject_fingerprint,
        NEW.started_at) IS DISTINCT FROM
       (OLD.tenant_id, OLD.rehearsal_run_id, OLD.rehearsal_reference, OLD.course_id,
        OLD.assignment_id, OLD.assignment_reference, OLD.direct_instructor_membership_id,
        OLD.actor_id, OLD.assignment_revision, OLD.subject_payload, OLD.subject_fingerprint,
        OLD.started_at) THEN
        RAISE EXCEPTION 'rehearsal provenance is immutable' USING ERRCODE = '55000';
    END IF;
    IF current_user <> 'ple_rehearsal_broker' THEN
        RAISE EXCEPTION 'rehearsal run mutation requires broker capability' USING ERRCODE = '42501';
    END IF;
    IF NEW.updated_at <> public.ple_rehearsal_now() THEN
        RAISE EXCEPTION 'rehearsal timestamps are database controlled' USING ERRCODE = '22023';
    END IF;
    IF OLD.lifecycle <> 'active' AND NEW.lifecycle IS DISTINCT FROM OLD.lifecycle THEN
        RAISE EXCEPTION 'terminal rehearsal lifecycle is immutable' USING ERRCODE = '55000';
    END IF;
    IF OLD.lifecycle = 'active' AND NEW.lifecycle = 'active'
       AND (NEW.terminal_at IS DISTINCT FROM OLD.terminal_at OR NEW.terminal_at IS NOT NULL) THEN
        RAISE EXCEPTION 'active rehearsal cannot have a terminal timestamp' USING ERRCODE = '22023';
    END IF;
    IF OLD.lifecycle = 'active' AND NEW.lifecycle <> 'active'
       AND NEW.terminal_at <> public.ple_rehearsal_now() THEN
        RAISE EXCEPTION 'terminal rehearsal timestamp is database controlled' USING ERRCODE = '22023';
    END IF;
    IF NEW.evidence_length < OLD.evidence_length THEN
        RAISE EXCEPTION 'rehearsal evidence head cannot regress' USING ERRCODE = '55000';
    END IF;
    IF NEW.evidence_length = OLD.evidence_length
       AND NEW.evidence_head_digest IS DISTINCT FROM OLD.evidence_head_digest THEN
        RAISE EXCEPTION 'rehearsal evidence head cannot change without an append' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END
$$;
CREATE TRIGGER rehearsal_frozen_item_append_only
    BEFORE UPDATE OR DELETE ON public.rehearsal_frozen_item
    FOR EACH ROW EXECUTE FUNCTION public.ple_reject_rehearsal_append_only_mutation();
CREATE TRIGGER rehearsal_evidence_append_only
    BEFORE UPDATE OR DELETE ON public.rehearsal_evidence
    FOR EACH ROW EXECUTE FUNCTION public.ple_reject_rehearsal_append_only_mutation();
CREATE TRIGGER rehearsal_claim_root_append_only
    BEFORE UPDATE OR DELETE ON public.rehearsal_submission_claim_root
    FOR EACH ROW EXECUTE FUNCTION public.ple_reject_rehearsal_append_only_mutation();
CREATE TRIGGER rehearsal_claim_event_append_only
    BEFORE UPDATE OR DELETE ON public.rehearsal_submission_claim_event
    FOR EACH ROW EXECUTE FUNCTION public.ple_reject_rehearsal_append_only_mutation();
CREATE TRIGGER rehearsal_receipt_append_only
    BEFORE UPDATE OR DELETE ON public.rehearsal_submission_receipt
    FOR EACH ROW EXECUTE FUNCTION public.ple_reject_rehearsal_append_only_mutation();
CREATE TRIGGER rehearsal_run_guarded_update
    BEFORE UPDATE ON public.rehearsal_run
    FOR EACH ROW EXECUTE FUNCTION public.ple_guard_rehearsal_run_update();
ALTER TABLE public.rehearsal_run ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_run FORCE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_frozen_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_frozen_item FORCE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_evidence FORCE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_submission_claim_root ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_submission_claim_root FORCE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_submission_claim_event ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_submission_claim_event FORCE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_submission_receipt ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rehearsal_submission_receipt FORCE ROW LEVEL SECURITY;
CREATE POLICY rehearsal_run_app_tenant ON public.rehearsal_run TO ple_app
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_frozen_item_app_tenant ON public.rehearsal_frozen_item TO ple_app
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_evidence_app_tenant ON public.rehearsal_evidence TO ple_app
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_claim_root_app_tenant ON public.rehearsal_submission_claim_root TO ple_app
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_claim_event_app_tenant ON public.rehearsal_submission_claim_event TO ple_app
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_receipt_app_tenant ON public.rehearsal_submission_receipt TO ple_app
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_run_broker_tenant ON public.rehearsal_run TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_frozen_item_broker_tenant ON public.rehearsal_frozen_item TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_evidence_broker_tenant ON public.rehearsal_evidence TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_claim_root_broker_tenant ON public.rehearsal_submission_claim_root TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_claim_event_broker_tenant ON public.rehearsal_submission_claim_event TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_receipt_broker_tenant ON public.rehearsal_submission_receipt TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_broker_course_member_tenant ON public.course_member TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY rehearsal_broker_assignment_tenant ON public.assignment TO ple_rehearsal_broker
    USING (tenant_id = public.ple_current_tenant());
-- Exact live instructor and assignment binding.  Callers provide locators, not
-- authority: the relation is locked and proves actor, membership, course, and
-- current revision together.
CREATE FUNCTION public.ple_rehearsal_authorize_current(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint
) RETURNS uuid
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE membership uuid;
BEGIN
    IF p_tenant IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant()
       OR p_actor IS NULL OR p_course IS NULL OR p_assignment IS NULL OR p_revision <= 0 THEN
        RETURN NULL;
    END IF;
    PERFORM 1 FROM public.assignment AS assignment_record
     WHERE assignment_record.tenant_id = p_tenant AND assignment_record.course_id = p_course
       AND assignment_record.assignment_id = p_assignment AND assignment_record.revision = p_revision
     FOR UPDATE;
    IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT member.course_membership_id INTO membership
      FROM public.course_member AS member
     WHERE member.tenant_id = p_tenant AND member.course_id = p_course
       AND member.user_id = p_actor AND member.role = 'instructor' AND member.status = 'active'
     FOR UPDATE;
    IF membership IS NULL THEN RETURN NULL; END IF;
    RETURN membership;
END
$$;
CREATE FUNCTION public.ple_rehearsal_start(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_assignment_reference integer,
    p_revision bigint, p_subject_payload jsonb, p_subject_fingerprint bytea,
    p_genesis_digest bytea, p_run uuid
) RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE membership uuid; reference bigint; active_run public.rehearsal_run%ROWTYPE;
BEGIN
    membership := public.ple_rehearsal_authorize_current(
        p_tenant, p_actor, p_course, p_assignment, p_revision
    );
    IF membership IS NULL OR p_run IS NULL OR p_assignment_reference <= 0
       OR jsonb_typeof(p_subject_payload) <> 'object'
       OR public.ple_rehearsal_jsonb_bytes(p_subject_payload) > 65536
       OR octet_length(p_subject_fingerprint) <> 32 OR octet_length(p_genesis_digest) <> 32 THEN
        RETURN NULL;
    END IF;
    SELECT * INTO active_run
      FROM public.rehearsal_run
     WHERE tenant_id = p_tenant AND course_id = p_course AND assignment_id = p_assignment
       AND direct_instructor_membership_id = membership AND lifecycle = 'active'
     FOR UPDATE;
    IF FOUND THEN
        IF active_run.assignment_revision <> p_revision THEN
            RETURN NULL;
        END IF;
        IF active_run.subject_fingerprint = p_subject_fingerprint
           AND active_run.actor_id = p_actor THEN
            RETURN active_run.rehearsal_reference;
        END IF;
        INSERT INTO public.rehearsal_submission_claim_event (
            tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase
        )
        SELECT root.tenant_id, root.rehearsal_run_id, root.claim_id, latest.sequence + 1,
               latest.operation_id, latest.generation, 'revokedTerminalLifecycle'
          FROM public.rehearsal_submission_claim_root root
          CROSS JOIN LATERAL (
              SELECT event.sequence, event.operation_id, event.generation, event.phase
                FROM public.rehearsal_submission_claim_event event
               WHERE event.tenant_id = root.tenant_id
                 AND event.rehearsal_run_id = root.rehearsal_run_id
                 AND event.claim_id = root.claim_id
               ORDER BY event.sequence DESC LIMIT 1
          ) latest
         WHERE root.tenant_id = p_tenant AND root.rehearsal_run_id = active_run.rehearsal_run_id
           AND latest.phase IN ('prepared', 'gradingDispatched');
        UPDATE public.rehearsal_run
           SET lifecycle = 'discardedByNewSubject', terminal_at = public.ple_rehearsal_now(),
               updated_at = public.ple_rehearsal_now()
         WHERE tenant_id = p_tenant AND rehearsal_run_id = active_run.rehearsal_run_id
           AND lifecycle = 'active';
        IF NOT FOUND THEN
            RAISE EXCEPTION 'active rehearsal changed during replacement' USING ERRCODE = '55000';
        END IF;
    END IF;
    INSERT INTO public.rehearsal_run (
        tenant_id, rehearsal_run_id, course_id, assignment_id, assignment_reference,
        direct_instructor_membership_id, actor_id, assignment_revision, subject_payload,
        subject_fingerprint, evidence_head_digest, evidence_length
    ) VALUES (
        p_tenant, p_run, p_course, p_assignment, p_assignment_reference, membership, p_actor,
        p_revision, p_subject_payload, p_subject_fingerprint, p_genesis_digest, 0
    ) RETURNING rehearsal_reference INTO reference;
    RETURN reference;
END
$$;
-- The caller must already have assembled canonical private evidence. This
-- function deliberately does not reimplement Rust hashing; it serializes the
-- checked payload and only accepts the next Store-owned chain position.
CREATE FUNCTION public.ple_rehearsal_append_evidence(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint,
    p_run uuid, p_old_digest bytea, p_old_length bigint, p_kind text, p_entry_digest bytea,
    p_payload jsonb, p_payload_digest bytea, p_recorded_at_millis bigint
) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE membership uuid; locked_run public.rehearsal_run%ROWTYPE; next_sequence bigint;
BEGIN
    membership := public.ple_rehearsal_authorize_current(p_tenant, p_actor, p_course, p_assignment, p_revision);
    IF membership IS NULL OR p_run IS NULL OR p_old_length NOT BETWEEN 0 AND 4294967295
       OR p_kind NOT IN ('frozenItem', 'acceptedSubmission') OR jsonb_typeof(p_payload) <> 'object'
       OR public.ple_rehearsal_jsonb_bytes(p_payload) > (CASE p_kind WHEN 'frozenItem' THEN 263168 WHEN 'acceptedSubmission' THEN 395264 ELSE 0 END)
       OR octet_length(p_old_digest) <> 32 OR octet_length(p_entry_digest) <> 32
       OR octet_length(p_payload_digest) <> 32
       OR p_recorded_at_millis <> public.ple_rehearsal_now_millis() THEN RETURN false; END IF;
    SELECT * INTO locked_run FROM public.rehearsal_run
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run
       AND course_id = p_course AND assignment_id = p_assignment AND actor_id = p_actor
       AND direct_instructor_membership_id = membership AND assignment_revision = p_revision
       AND lifecycle = 'active' FOR UPDATE;
    IF NOT FOUND OR locked_run.evidence_head_digest IS DISTINCT FROM p_old_digest
       OR locked_run.evidence_length <> p_old_length THEN RETURN false; END IF;
    next_sequence := p_old_length + 1;
    INSERT INTO public.rehearsal_evidence (
        tenant_id, rehearsal_run_id, sequence, kind, previous_digest, entry_digest,
        payload, payload_digest, recorded_at
    ) VALUES (p_tenant, p_run, next_sequence, p_kind, p_old_digest, p_entry_digest,
              p_payload, p_payload_digest, public.ple_rehearsal_timestamp_from_millis(p_recorded_at_millis));
    UPDATE public.rehearsal_run SET evidence_head_digest = p_entry_digest,
        evidence_length = next_sequence, updated_at = public.ple_rehearsal_now()
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run
       AND evidence_head_digest = p_old_digest AND evidence_length = p_old_length;
    IF NOT FOUND THEN RAISE EXCEPTION 'rehearsal evidence head compare-and-swap failed' USING ERRCODE = '55000'; END IF;
    RETURN true;
END
$$;
CREATE FUNCTION public.ple_rehearsal_terminalize(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint,
    p_run uuid, p_lifecycle text
) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE membership uuid;
BEGIN
    membership := public.ple_rehearsal_authorize_current(p_tenant, p_actor, p_course, p_assignment, p_revision);
    IF membership IS NULL OR p_lifecycle NOT IN ('completed', 'discardedByInstructor', 'discardedByNewSubject') THEN
        RETURN false;
    END IF;
    PERFORM 1 FROM public.rehearsal_run
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run AND course_id = p_course
       AND assignment_id = p_assignment AND actor_id = p_actor
       AND direct_instructor_membership_id = membership AND assignment_revision = p_revision
       AND lifecycle = 'active' FOR UPDATE;
    IF NOT FOUND THEN RETURN false; END IF;
    INSERT INTO public.rehearsal_submission_claim_event (
        tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase
    )
    SELECT root.tenant_id, root.rehearsal_run_id, root.claim_id, latest.sequence + 1,
           latest.operation_id, latest.generation, 'revokedTerminalLifecycle'
      FROM public.rehearsal_submission_claim_root root
      CROSS JOIN LATERAL (
          SELECT event.sequence, event.operation_id, event.generation, event.phase
            FROM public.rehearsal_submission_claim_event event
           WHERE event.tenant_id = root.tenant_id AND event.rehearsal_run_id = root.rehearsal_run_id
             AND event.claim_id = root.claim_id ORDER BY event.sequence DESC LIMIT 1
      ) latest
     WHERE root.tenant_id = p_tenant AND root.rehearsal_run_id = p_run
       AND latest.phase IN ('prepared', 'gradingDispatched');
    UPDATE public.rehearsal_run SET lifecycle = p_lifecycle, terminal_at = public.ple_rehearsal_now(),
        updated_at = public.ple_rehearsal_now()
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run AND course_id = p_course
       AND assignment_id = p_assignment AND actor_id = p_actor
       AND direct_instructor_membership_id = membership AND assignment_revision = p_revision
       AND lifecycle = 'active';
    RETURN FOUND;
END
$$;
CREATE FUNCTION public.ple_rehearsal_append_frozen_item(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint,
    p_run uuid, p_old_digest bytea, p_old_length bigint, p_entry_digest bytea,
    p_evidence_payload jsonb, p_evidence_payload_digest bytea, p_recorded_at_millis bigint,
    p_attempt uuid, p_problem uuid, p_version uuid, p_response_definition jsonb,
    p_response_schema_digest bytea, p_content_digest bytea, p_frozen_at_millis bigint
) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
BEGIN
    IF p_attempt IS NULL OR p_problem IS NULL OR p_version IS NULL
       OR p_frozen_at_millis <> public.ple_rehearsal_now_millis()
       OR p_frozen_at_millis <> p_recorded_at_millis
       OR jsonb_typeof(p_response_definition) <> 'object'
       OR public.ple_rehearsal_jsonb_bytes(p_response_definition) > 262144
       OR octet_length(p_response_schema_digest) <> 32 OR octet_length(p_content_digest) <> 32
       OR NOT public.ple_rehearsal_append_evidence(
           p_tenant, p_actor, p_course, p_assignment, p_revision, p_run, p_old_digest,
           p_old_length, 'frozenItem', p_entry_digest, p_evidence_payload,
           p_evidence_payload_digest, p_recorded_at_millis
       ) THEN
        RETURN false;
    END IF;
    INSERT INTO public.rehearsal_frozen_item (
        tenant_id, rehearsal_run_id, attempt_id, problem_id, version_id, response_definition,
        response_schema_digest, canonical_content_digest, frozen_at
    ) VALUES (
        p_tenant, p_run, p_attempt, p_problem, p_version, p_response_definition,
        p_response_schema_digest, p_content_digest,
        public.ple_rehearsal_timestamp_from_millis(p_frozen_at_millis)
    );
    RETURN true;
END
$$;
CREATE FUNCTION public.ple_rehearsal_create_claim(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint, p_run uuid,
    p_claim uuid, p_operation uuid, p_idempotency_key text, p_attempt uuid,
    p_request_fingerprint bytea, p_sealed_request jsonb
) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE membership uuid;
BEGIN
    membership := public.ple_rehearsal_authorize_current(p_tenant, p_actor, p_course, p_assignment, p_revision);
    IF membership IS NULL OR p_run IS NULL OR p_claim IS NULL OR p_operation IS NULL OR p_attempt IS NULL
       OR octet_length(p_request_fingerprint) <> 32 OR jsonb_typeof(p_sealed_request) <> 'object'
       OR public.ple_rehearsal_jsonb_bytes(p_sealed_request) > 393728 THEN
        RETURN false;
    END IF;
    PERFORM 1 FROM public.rehearsal_run
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run AND course_id = p_course
       AND assignment_id = p_assignment AND actor_id = p_actor
       AND direct_instructor_membership_id = membership AND assignment_revision = p_revision
       AND lifecycle = 'active' FOR UPDATE;
    IF NOT FOUND THEN RETURN false; END IF;
    INSERT INTO public.rehearsal_submission_claim_root (
        tenant_id, rehearsal_run_id, claim_id, idempotency_key, attempt_id, request_fingerprint, sealed_request
    ) VALUES (p_tenant, p_run, p_claim, p_idempotency_key, p_attempt, p_request_fingerprint, p_sealed_request);
    INSERT INTO public.rehearsal_submission_claim_event (
        tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase
    ) VALUES (p_tenant, p_run, p_claim, 1, p_operation, 1, 'prepared');
    RETURN true;
EXCEPTION WHEN unique_violation THEN
    RETURN false;
END
$$;
CREATE FUNCTION public.ple_rehearsal_append_claim_event(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint, p_run uuid,
    p_claim uuid, p_operation uuid, p_phase text, p_abandonment_reason text DEFAULT NULL
) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE membership uuid; latest record; next_generation bigint;
BEGIN
    membership := public.ple_rehearsal_authorize_current(p_tenant, p_actor, p_course, p_assignment, p_revision);
    IF membership IS NULL OR p_run IS NULL OR p_claim IS NULL OR p_operation IS NULL THEN RETURN false; END IF;
    PERFORM 1 FROM public.rehearsal_submission_claim_root root
      JOIN public.rehearsal_run run ON run.tenant_id = root.tenant_id AND run.rehearsal_run_id = root.rehearsal_run_id
     WHERE root.tenant_id = p_tenant AND root.rehearsal_run_id = p_run AND root.claim_id = p_claim
       AND run.course_id = p_course AND run.assignment_id = p_assignment AND run.actor_id = p_actor
       AND run.direct_instructor_membership_id = membership AND run.assignment_revision = p_revision
       AND run.lifecycle = 'active' FOR UPDATE OF run;
    IF NOT FOUND THEN RETURN false; END IF;
    SELECT sequence, operation_id, generation, phase INTO latest
      FROM public.rehearsal_submission_claim_event
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run AND claim_id = p_claim
     ORDER BY sequence DESC LIMIT 1;
    IF NOT FOUND THEN RETURN false; END IF;
    IF p_phase = 'gradingDispatched' AND latest.phase = 'prepared'
       AND p_operation = latest.operation_id AND p_abandonment_reason IS NULL THEN
        next_generation := latest.generation;
    ELSIF p_phase = 'abandonedBeforeDispatch' AND latest.phase = 'prepared'
       AND p_operation = latest.operation_id
       AND p_abandonment_reason IN (
           'localPreparationFailed', 'nativeBackendAdmissionRejected',
           'trustedRendererAdmissionRejected'
       ) THEN
        next_generation := latest.generation;
    ELSIF p_phase = 'prepared' AND latest.phase = 'abandonedBeforeDispatch'
       AND p_abandonment_reason IS NULL AND latest.generation < 4294967295
       AND NOT EXISTS (
           SELECT 1 FROM public.rehearsal_submission_claim_event event
            WHERE event.tenant_id = p_tenant AND event.rehearsal_run_id = p_run
              AND event.claim_id = p_claim AND event.operation_id = p_operation
       ) THEN
        next_generation := latest.generation + 1;
    ELSE
        RETURN false;
    END IF;
    INSERT INTO public.rehearsal_submission_claim_event (
        tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase, abandonment_reason
    ) VALUES (
        p_tenant, p_run, p_claim, latest.sequence + 1, p_operation, next_generation, p_phase,
        p_abandonment_reason
    );
    RETURN true;
END
$$;
CREATE FUNCTION public.ple_rehearsal_complete_claim(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_revision bigint, p_run uuid,
    p_claim uuid, p_operation uuid, p_old_digest bytea, p_old_length bigint, p_entry_digest bytea,
    p_evidence_payload jsonb, p_evidence_payload_digest bytea, p_recorded_at_millis bigint,
    p_receipt_projection jsonb, p_receipt_digest bytea
) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE latest record; membership uuid;
BEGIN
    membership := public.ple_rehearsal_authorize_current(
        p_tenant, p_actor, p_course, p_assignment, p_revision
    );
    IF membership IS NULL OR p_claim IS NULL OR p_operation IS NULL
       OR p_recorded_at_millis <> public.ple_rehearsal_now_millis()
       OR jsonb_typeof(p_receipt_projection) <> 'object'
       OR public.ple_rehearsal_jsonb_bytes(p_receipt_projection) > 394240
       OR octet_length(p_receipt_digest) <> 32 THEN RETURN false; END IF;
    PERFORM 1 FROM public.rehearsal_submission_claim_root root
      JOIN public.rehearsal_run run ON run.tenant_id = root.tenant_id AND run.rehearsal_run_id = root.rehearsal_run_id
     WHERE root.tenant_id = p_tenant AND root.rehearsal_run_id = p_run AND root.claim_id = p_claim
       AND run.course_id = p_course AND run.assignment_id = p_assignment AND run.actor_id = p_actor
       AND run.direct_instructor_membership_id = membership AND run.assignment_revision = p_revision
       AND run.lifecycle = 'active' FOR UPDATE OF run;
    IF NOT FOUND THEN RETURN false; END IF;
    SELECT sequence, operation_id, generation, phase INTO latest FROM public.rehearsal_submission_claim_event
     WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run AND claim_id = p_claim
     ORDER BY sequence DESC LIMIT 1;
    IF NOT FOUND OR latest.phase <> 'gradingDispatched' OR p_operation <> latest.operation_id THEN
        RETURN false;
    END IF;
    IF NOT public.ple_rehearsal_append_evidence(
        p_tenant, p_actor, p_course, p_assignment, p_revision, p_run, p_old_digest, p_old_length,
        'acceptedSubmission', p_entry_digest, p_evidence_payload, p_evidence_payload_digest, p_recorded_at_millis
    ) THEN RETURN false; END IF;
    INSERT INTO public.rehearsal_submission_receipt (
        tenant_id, rehearsal_run_id, claim_id, outcome_projection, receipt_digest
    ) VALUES (p_tenant, p_run, p_claim, p_receipt_projection, p_receipt_digest);
    INSERT INTO public.rehearsal_submission_claim_event (
        tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase,
        accepted_evidence_sequence, accepted_evidence_digest, receipt_digest
    ) VALUES (
        p_tenant, p_run, p_claim, latest.sequence + 1, p_operation, latest.generation, 'completed',
        p_old_length + 1, p_entry_digest, p_receipt_digest
    );
    RETURN true;
END
$$;
CREATE FUNCTION public.ple_rehearsal_evidence_is_contiguous(
    p_tenant uuid, p_run uuid, p_expected_length bigint
) RETURNS boolean
    LANGUAGE sql STABLE
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
SELECT CASE
    WHEN p_tenant IS NULL OR p_run IS NULL
      OR p_expected_length NOT BETWEEN 0 AND 4294967295 THEN false
    WHEN p_expected_length = 0 THEN NOT EXISTS (
        SELECT 1 FROM public.rehearsal_evidence
         WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run
    )
    ELSE (SELECT COUNT(*) = p_expected_length AND MIN(sequence) = 1
                    AND MAX(sequence) = p_expected_length
            FROM public.rehearsal_evidence
           WHERE tenant_id = p_tenant AND rehearsal_run_id = p_run)
END
$$;
CREATE FUNCTION public.ple_invalidate_rehearsals_for_assignment(
    p_tenant uuid, p_actor uuid, p_course uuid, p_assignment uuid, p_old_revision bigint, p_new_revision bigint
) RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE changed bigint;
BEGIN
    IF p_old_revision <= 0 OR p_new_revision <> p_old_revision + 1
       OR public.ple_rehearsal_authorize_current(
        p_tenant, p_actor, p_course, p_assignment, p_new_revision
    ) IS NULL THEN
        RAISE EXCEPTION 'invalid rehearsal revision invalidation' USING ERRCODE = '22023';
    END IF;
    PERFORM 1 FROM public.rehearsal_run
     WHERE tenant_id = p_tenant AND assignment_id = p_assignment
       AND assignment_revision = p_old_revision AND lifecycle = 'active'
     ORDER BY rehearsal_run_id FOR UPDATE;
    -- Rust performs the stronger canonical hash verification after this SQL shape guard.
    IF EXISTS (
        SELECT 1 FROM public.rehearsal_run run
         WHERE run.tenant_id = p_tenant AND run.assignment_id = p_assignment
           AND run.assignment_revision = p_old_revision AND run.lifecycle = 'active'
           AND NOT public.ple_rehearsal_evidence_is_contiguous(
               run.tenant_id, run.rehearsal_run_id, run.evidence_length)
    ) THEN RAISE EXCEPTION 'rehearsal aggregate structural verification failed' USING ERRCODE = '55000'; END IF;
    INSERT INTO public.rehearsal_submission_claim_event (
        tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase
    )
    SELECT root.tenant_id, root.rehearsal_run_id, root.claim_id,
           latest.sequence + 1, latest.operation_id, latest.generation, 'revokedStaleRevision'
      FROM public.rehearsal_submission_claim_root root
      JOIN public.rehearsal_run run ON run.tenant_id = root.tenant_id AND run.rehearsal_run_id = root.rehearsal_run_id
      CROSS JOIN LATERAL (
          SELECT event.sequence, event.operation_id, event.generation, event.phase
            FROM public.rehearsal_submission_claim_event event
           WHERE event.tenant_id = root.tenant_id AND event.rehearsal_run_id = root.rehearsal_run_id
             AND event.claim_id = root.claim_id ORDER BY event.sequence DESC LIMIT 1
      ) latest
     WHERE root.tenant_id = p_tenant AND run.assignment_id = p_assignment
       AND run.assignment_revision = p_old_revision AND run.lifecycle = 'active'
       AND latest.phase IN ('prepared', 'gradingDispatched');
    UPDATE public.rehearsal_run SET lifecycle = 'discardedStaleRevision', terminal_at = public.ple_rehearsal_now(),
        updated_at = public.ple_rehearsal_now()
     WHERE tenant_id = p_tenant AND assignment_id = p_assignment
       AND assignment_revision = p_old_revision AND lifecycle = 'active';
    GET DIAGNOSTICS changed = ROW_COUNT;
    RETURN changed;
END
$$;
CREATE FUNCTION public.ple_rehearsal_fence_source_context(
    p_tenant uuid, p_course uuid, p_assignment uuid, p_membership uuid
) RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE fenced bigint; source_course uuid;
BEGIN
    IF p_tenant IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant()
       OR ((p_course IS NOT NULL)::integer + (p_assignment IS NOT NULL)::integer
           + (p_membership IS NOT NULL)::integer) <> 1 THEN
        RAISE EXCEPTION 'invalid rehearsal source-removal capability' USING ERRCODE = '42501';
    END IF;
    IF p_course IS NOT NULL THEN
        PERFORM 1 FROM public.assignment assignment_record
         WHERE assignment_record.tenant_id = p_tenant AND assignment_record.course_id = p_course
         ORDER BY assignment_record.assignment_id FOR UPDATE;
        PERFORM 1 FROM public.course_member membership
         WHERE membership.tenant_id = p_tenant AND membership.course_id = p_course
           AND membership.role = 'instructor' AND membership.status = 'active'
         ORDER BY membership.course_membership_id FOR UPDATE;
    ELSIF p_assignment IS NOT NULL THEN
        SELECT assignment_record.course_id INTO source_course
          FROM public.assignment assignment_record
         WHERE assignment_record.tenant_id = p_tenant
           AND assignment_record.assignment_id = p_assignment
         ;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'assignment source is already absent' USING ERRCODE = '55000';
        END IF;
        PERFORM 1 FROM public.assignment assignment_record
         WHERE assignment_record.tenant_id = p_tenant AND assignment_record.course_id = source_course
           AND assignment_record.assignment_id = p_assignment FOR UPDATE;
        PERFORM 1 FROM public.course_member membership
         WHERE membership.tenant_id = p_tenant AND membership.course_id = source_course
           AND membership.role = 'instructor' AND membership.status = 'active'
         ORDER BY membership.course_membership_id FOR UPDATE;
    ELSE
        SELECT membership.course_id INTO source_course
          FROM public.course_member membership
         WHERE membership.tenant_id = p_tenant
           AND membership.course_membership_id = p_membership
         FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'membership source is already absent' USING ERRCODE = '55000';
        END IF;
    END IF;
    PERFORM 1 FROM public.rehearsal_run run
     WHERE run.tenant_id = p_tenant AND run.lifecycle = 'active'
       AND ((p_course IS NOT NULL AND run.course_id = p_course)
         OR (p_assignment IS NOT NULL AND run.assignment_id = p_assignment)
         OR (p_membership IS NOT NULL AND run.direct_instructor_membership_id = p_membership))
     ORDER BY run.rehearsal_run_id FOR UPDATE;
    IF EXISTS (
        SELECT 1 FROM public.rehearsal_run run
         WHERE run.tenant_id = p_tenant AND run.lifecycle = 'active'
           AND ((p_course IS NOT NULL AND run.course_id = p_course)
             OR (p_assignment IS NOT NULL AND run.assignment_id = p_assignment)
             OR (p_membership IS NOT NULL AND run.direct_instructor_membership_id = p_membership))
           AND NOT public.ple_rehearsal_evidence_is_contiguous(
               run.tenant_id, run.rehearsal_run_id, run.evidence_length)
    ) THEN RAISE EXCEPTION 'rehearsal aggregate structural verification failed' USING ERRCODE = '55000'; END IF;
    INSERT INTO public.rehearsal_submission_claim_event (
        tenant_id, rehearsal_run_id, claim_id, sequence, operation_id, generation, phase
    )
    SELECT root.tenant_id, root.rehearsal_run_id, root.claim_id, latest.sequence + 1,
           latest.operation_id, latest.generation, 'revokedSourceContextRemoved'
      FROM public.rehearsal_submission_claim_root root
      JOIN public.rehearsal_run run ON run.tenant_id = root.tenant_id AND run.rehearsal_run_id = root.rehearsal_run_id
      CROSS JOIN LATERAL (
          SELECT event.sequence, event.operation_id, event.generation, event.phase
            FROM public.rehearsal_submission_claim_event event
           WHERE event.tenant_id = root.tenant_id AND event.rehearsal_run_id = root.rehearsal_run_id
             AND event.claim_id = root.claim_id ORDER BY event.sequence DESC LIMIT 1
      ) latest
     WHERE root.tenant_id = p_tenant AND run.lifecycle = 'active'
       AND ((p_course IS NOT NULL AND run.course_id = p_course)
         OR (p_assignment IS NOT NULL AND run.assignment_id = p_assignment)
         OR (p_membership IS NOT NULL AND run.direct_instructor_membership_id = p_membership))
       AND latest.phase IN ('prepared', 'gradingDispatched');
    UPDATE public.rehearsal_run SET lifecycle = 'discardedSourceContextRemoved',
        terminal_at = public.ple_rehearsal_now(), updated_at = public.ple_rehearsal_now()
     WHERE tenant_id = p_tenant AND lifecycle = 'active'
       AND ((p_course IS NOT NULL AND course_id = p_course)
         OR (p_assignment IS NOT NULL AND assignment_id = p_assignment)
         OR (p_membership IS NOT NULL AND direct_instructor_membership_id = p_membership));
    GET DIAGNOSTICS fenced = ROW_COUNT;
    RETURN fenced;
END
$$;
CREATE FUNCTION public.ple_fence_rehearsals_for_source_removal(
    p_tenant uuid, p_course uuid, p_assignment uuid, p_membership uuid,
    p_job uuid, p_lease_token uuid, p_reason text
) RETURNS bigint
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
DECLARE fenced bigint;
BEGIN
    IF p_tenant IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant()
       OR p_reason <> 'sourceContextRemoved'
       OR ((p_course IS NOT NULL)::integer + (p_assignment IS NOT NULL)::integer
           + (p_membership IS NOT NULL)::integer) <> 1 THEN
        RAISE EXCEPTION 'invalid rehearsal source-removal capability' USING ERRCODE = '42501';
    END IF;
    PERFORM 1 FROM public.worker_job job
      JOIN public.course_retention_dispatch dispatch ON dispatch.tenant_id = job.tenant_id
       AND dispatch.job_id = job.job_id
      JOIN public.course_retention_stage stage ON stage.tenant_id = dispatch.tenant_id
       AND stage.course_id = dispatch.course_id AND stage.generation = dispatch.generation
       AND stage.stage = dispatch.stage
     WHERE job.job_id = p_job AND job.tenant_id = p_tenant AND job.state = 'leased'
       AND job.lease_token = p_lease_token AND job.lease_expires_at > transaction_timestamp()
       AND dispatch.stage = 'deleteStudentRecords' AND stage.state = 'started'
       AND stage.job_id = p_job AND stage.lease_token = p_lease_token
       AND (
            (p_course IS NOT NULL AND dispatch.course_id = p_course)
            OR (p_assignment IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.assignment assignment_record
                 WHERE assignment_record.tenant_id = p_tenant
                   AND assignment_record.course_id = dispatch.course_id
                   AND assignment_record.assignment_id = p_assignment
            ))
            OR (p_membership IS NOT NULL AND EXISTS (
                SELECT 1 FROM public.course_member membership
                 WHERE membership.tenant_id = p_tenant
                   AND membership.course_id = dispatch.course_id
                   AND membership.course_membership_id = p_membership
            ))
       )
     FOR UPDATE OF job, stage;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'retention lease is not authorized for rehearsal fence' USING ERRCODE = '42501';
    END IF;
    SELECT public.ple_rehearsal_fence_source_context(p_tenant, p_course, p_assignment, p_membership)
      INTO fenced;
    RETURN fenced;
END
$$;
CREATE FUNCTION public.ple_fence_rehearsals_for_direct_instructor_removal(
    p_tenant uuid, p_actor uuid, p_course uuid, p_membership uuid
) RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE fenced bigint;
BEGIN
    IF p_tenant IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant()
       OR p_actor IS NULL OR p_course IS NULL OR p_membership IS NULL THEN RETURN NULL; END IF;
    PERFORM 1 FROM public.course_member actor_membership
     WHERE actor_membership.tenant_id = p_tenant AND actor_membership.course_id = p_course
       AND actor_membership.user_id = p_actor AND actor_membership.role = 'instructor'
       AND actor_membership.status = 'active';
    IF NOT FOUND THEN RETURN NULL; END IF;
    PERFORM 1 FROM public.course_member target_membership
     WHERE target_membership.tenant_id = p_tenant AND target_membership.course_id = p_course
       AND target_membership.course_membership_id = p_membership
       AND target_membership.role = 'instructor' AND target_membership.status = 'active' FOR UPDATE;
    IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT public.ple_rehearsal_fence_source_context(p_tenant, NULL, NULL, p_membership) INTO fenced;
    RETURN fenced;
END
$$;
CREATE OR REPLACE FUNCTION public.ple_commit_delete_retention_work(
    p_tenant uuid, p_job uuid, p_token uuid, p_course uuid, p_stage text, p_generation bigint
) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE committed boolean; disposition text; incoming_tenant uuid;
BEGIN
    incoming_tenant := public.ple_current_tenant();
    IF incoming_tenant IS NULL OR p_tenant IS NULL OR incoming_tenant <> p_tenant THEN
        RAISE EXCEPTION 'retention tenant authority mismatch' USING ERRCODE = '42501';
    END IF;
    SELECT assignment_disposition INTO disposition FROM public.course_retention
     WHERE tenant_id = p_tenant AND course_id = p_course AND generation = p_generation FOR UPDATE;
    IF disposition = 'delete' THEN
        BEGIN
            PERFORM public.ple_fence_rehearsals_for_source_removal(
                p_tenant, p_course, NULL, NULL, p_job, p_token, 'sourceContextRemoved'
            );
            committed := public.ple_commit_delete_retention_work_before_passwordless_identity(
                p_tenant, p_job, p_token, p_course, p_stage, p_generation
            );
            IF NOT committed THEN RAISE EXCEPTION 'retention delete did not commit' USING ERRCODE = 'P1T04'; END IF;
        EXCEPTION WHEN SQLSTATE 'P1T04' THEN RETURN false;
        END;
    ELSE
        committed := public.ple_commit_delete_retention_work_before_passwordless_identity(
            p_tenant, p_job, p_token, p_course, p_stage, p_generation
        );
        IF NOT committed THEN RETURN false; END IF;
    END IF;
    DELETE FROM public.course_total_export_audit WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_grade_category_assignment WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_grade_letter_band WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_grade_category WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_grade_scheme WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_grade_export_audit WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_roster_import WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.course_invitation WHERE tenant_id = p_tenant AND course_id = p_course;
    DELETE FROM public.tenant_learner_identity learner WHERE learner.tenant_id = p_tenant
      AND NOT EXISTS (SELECT 1 FROM public.course_member membership WHERE membership.tenant_id = learner.tenant_id AND membership.user_id = learner.user_id AND membership.role = 'student')
      AND NOT EXISTS (SELECT 1 FROM public.enrollment enrollment WHERE enrollment.tenant_id = learner.tenant_id AND enrollment.user_id = learner.user_id);
    RETURN NOT EXISTS (
        SELECT 1 FROM public.course_invitation WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_roster_profile WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_grade_export_audit WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_total_export_audit WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_grade_category_assignment WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_grade_letter_band WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_grade_category WHERE tenant_id = p_tenant AND course_id = p_course
        UNION ALL SELECT 1 FROM public.course_grade_scheme WHERE tenant_id = p_tenant AND course_id = p_course
    );
END
$$;
CREATE FUNCTION public.ple_assert_tenant_rehearsal_erasure_allowed(p_tenant uuid) RETURNS boolean
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public', pg_temp
    AS $$
BEGIN
    IF p_tenant IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant()
       OR EXISTS (SELECT 1 FROM public.rehearsal_run WHERE tenant_id = p_tenant) THEN
        RAISE EXCEPTION 'tenant deletion is blocked by retained rehearsal evidence' USING ERRCODE = '55000';
    END IF;
    RETURN true;
END
$$;
ALTER FUNCTION public.ple_rehearsal_authorize_current(uuid, uuid, uuid, uuid, bigint) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_now() OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_now_millis() OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_evidence_is_contiguous(uuid, uuid, bigint) OWNER TO ple_rehearsal_broker;
ALTER FUNCTION public.ple_rehearsal_start(uuid, uuid, uuid, uuid, integer, bigint, jsonb, bytea, bytea, uuid) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_append_evidence(uuid, uuid, uuid, uuid, bigint, uuid, bytea, bigint, text, bytea, jsonb, bytea, bigint) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_append_frozen_item(uuid, uuid, uuid, uuid, bigint, uuid, bytea, bigint, bytea, jsonb, bytea, bigint, uuid, uuid, uuid, jsonb, bytea, bytea, bigint) OWNER TO ple_rehearsal_broker;
ALTER FUNCTION public.ple_rehearsal_create_claim(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, text, uuid, bytea, jsonb) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_append_claim_event(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, text, text) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_complete_claim(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, bytea, bigint, bytea, jsonb, bytea, bigint, jsonb, bytea) OWNER TO ple_rehearsal_broker;
ALTER FUNCTION public.ple_rehearsal_terminalize(uuid, uuid, uuid, uuid, bigint, uuid, text) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_invalidate_rehearsals_for_assignment(uuid, uuid, uuid, uuid, bigint, bigint) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_rehearsal_fence_source_context(uuid, uuid, uuid, uuid) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_fence_rehearsals_for_source_removal(uuid, uuid, uuid, uuid, uuid, uuid, text) OWNER TO ple_retention_broker; ALTER FUNCTION public.ple_fence_rehearsals_for_direct_instructor_removal(uuid, uuid, uuid, uuid) OWNER TO ple_rehearsal_broker; ALTER FUNCTION public.ple_commit_delete_retention_work(uuid, uuid, uuid, uuid, text, bigint) OWNER TO ple_retention_broker; ALTER FUNCTION public.ple_assert_tenant_rehearsal_erasure_allowed(uuid) OWNER TO ple_rehearsal_broker;
GRANT SELECT, INSERT, UPDATE ON public.rehearsal_run TO ple_rehearsal_broker;
GRANT USAGE, SELECT ON SEQUENCE public.rehearsal_run_rehearsal_reference_seq TO ple_rehearsal_broker;
GRANT SELECT, INSERT ON public.rehearsal_frozen_item, public.rehearsal_evidence,
    public.rehearsal_submission_claim_root, public.rehearsal_submission_claim_event,
    public.rehearsal_submission_receipt TO ple_rehearsal_broker;
GRANT SELECT ON public.rehearsal_run, public.rehearsal_frozen_item, public.rehearsal_evidence,
    public.rehearsal_submission_claim_root, public.rehearsal_submission_claim_event,
    public.rehearsal_submission_receipt TO ple_app;
GRANT SELECT ON public.course_member, public.assignment TO ple_rehearsal_broker;
GRANT UPDATE (course_membership_id) ON public.course_member TO ple_rehearsal_broker;
GRANT UPDATE (assignment_id) ON public.assignment TO ple_rehearsal_broker;
GRANT EXECUTE ON FUNCTION public.ple_current_tenant() TO ple_rehearsal_broker;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_now(), public.ple_rehearsal_now_millis(), public.ple_rehearsal_timestamp_from_millis(bigint) TO ple_rehearsal_broker;
REVOKE ALL ON FUNCTION public.ple_rehearsal_authorize_current(uuid, uuid, uuid, uuid, bigint), public.ple_rehearsal_evidence_is_contiguous(uuid, uuid, bigint), public.ple_reject_rehearsal_append_only_mutation(), public.ple_guard_rehearsal_run_update(), public.ple_rehearsal_now(), public.ple_rehearsal_now_millis(), public.ple_rehearsal_timestamp_from_millis(bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_rehearsal_start(uuid, uuid, uuid, uuid, integer, bigint, jsonb, bytea, bytea, uuid), public.ple_rehearsal_append_evidence(uuid, uuid, uuid, uuid, bigint, uuid, bytea, bigint, text, bytea, jsonb, bytea, bigint), public.ple_rehearsal_append_frozen_item(uuid, uuid, uuid, uuid, bigint, uuid, bytea, bigint, bytea, jsonb, bytea, bigint, uuid, uuid, uuid, jsonb, bytea, bytea, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_rehearsal_create_claim(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, text, uuid, bytea, jsonb), public.ple_rehearsal_append_claim_event(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, text, text), public.ple_rehearsal_complete_claim(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, bytea, bigint, bytea, jsonb, bytea, bigint, jsonb, bytea), public.ple_rehearsal_terminalize(uuid, uuid, uuid, uuid, bigint, uuid, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_invalidate_rehearsals_for_assignment(uuid, uuid, uuid, uuid, bigint, bigint), public.ple_rehearsal_fence_source_context(uuid, uuid, uuid, uuid), public.ple_fence_rehearsals_for_source_removal(uuid, uuid, uuid, uuid, uuid, uuid, text), public.ple_fence_rehearsals_for_direct_instructor_removal(uuid, uuid, uuid, uuid), public.ple_assert_tenant_rehearsal_erasure_allowed(uuid), public.ple_commit_delete_retention_work(uuid, uuid, uuid, uuid, text, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_now_millis() TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_start(uuid, uuid, uuid, uuid, integer, bigint, jsonb, bytea, bytea, uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_append_frozen_item(uuid, uuid, uuid, uuid, bigint, uuid, bytea, bigint, bytea, jsonb, bytea, bigint, uuid, uuid, uuid, jsonb, bytea, bytea, bigint) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_create_claim(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, text, uuid, bytea, jsonb) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_append_claim_event(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, text, text) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_complete_claim(uuid, uuid, uuid, uuid, bigint, uuid, uuid, uuid, bytea, bigint, bytea, jsonb, bytea, bigint, jsonb, bytea) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_terminalize(uuid, uuid, uuid, uuid, bigint, uuid, text) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_fence_rehearsals_for_direct_instructor_removal(uuid, uuid, uuid, uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_rehearsal_fence_source_context(uuid, uuid, uuid, uuid) TO ple_retention_broker;
GRANT EXECUTE ON FUNCTION public.ple_fence_rehearsals_for_source_removal(uuid, uuid, uuid, uuid, uuid, uuid, text) TO ple_retention_broker;
GRANT EXECUTE ON FUNCTION public.ple_assert_tenant_rehearsal_erasure_allowed(uuid) TO ple_retention_broker;
DO $$
DECLARE
    millis_proc pg_proc%ROWTYPE;
    now_proc pg_proc%ROWTYPE;
BEGIN
    SELECT * INTO millis_proc
      FROM pg_proc
     WHERE oid = 'public.ple_rehearsal_now_millis()'::regprocedure;
    SELECT * INTO now_proc
      FROM pg_proc
     WHERE oid = 'public.ple_rehearsal_now()'::regprocedure;
    IF NOT millis_proc.prosecdef
       OR millis_proc.proowner::regrole::text <> 'ple_rehearsal_broker'
       OR coalesce(array_to_string(millis_proc.proconfig, ','), '')
            NOT LIKE '%search_path=pg_catalog, public, pg_temp%'
       OR has_function_privilege('public', millis_proc.oid, 'EXECUTE')
       OR NOT has_function_privilege('ple_app', millis_proc.oid, 'EXECUTE')
       OR now_proc.prosecdef
       OR now_proc.proowner::regrole::text <> 'ple_rehearsal_broker'
       OR has_function_privilege('public', now_proc.oid, 'EXECUTE')
       OR has_function_privilege('ple_app', now_proc.oid, 'EXECUTE') THEN
        RAISE EXCEPTION 'rehearsal database-clock capability inventory is unsafe'
            USING ERRCODE = '42501';
    END IF;
END
$$;
COMMIT;
