-- WP-PROF-B1: reusable assignment Blueprints and shared Alpha curricula.
-- Curriculum aggregates are deliberately separate from teaching courses:
-- learners, enrollment, issued work, and course lifecycle never cross here.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE public.course_blueprint (
    tenant_id uuid NOT NULL,
    blueprint_id uuid NOT NULL DEFAULT gen_random_uuid(),
    blueprint_reference integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.course_blueprint_reference_seq),
    owner_user_id uuid NOT NULL,
    definition_json jsonb NOT NULL,
    semantic_sha256 bytea NOT NULL,
    revision bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    PRIMARY KEY (tenant_id, blueprint_id), UNIQUE (blueprint_reference),
    FOREIGN KEY (owner_user_id) REFERENCES public.ple_account(user_id) ON DELETE RESTRICT,
    CHECK (blueprint_reference > 0), CHECK (jsonb_typeof(definition_json) = 'object'),
    CHECK (octet_length(semantic_sha256) = 32), CHECK (revision > 0)
);
CREATE TABLE public.course_blueprint_entry (
    tenant_id uuid NOT NULL, blueprint_id uuid NOT NULL, position integer NOT NULL, kind text NOT NULL,
    PRIMARY KEY (tenant_id, blueprint_id, position),
    FOREIGN KEY (tenant_id, blueprint_id) REFERENCES public.course_blueprint ON DELETE CASCADE,
    CHECK (position >= 0), CHECK (kind IN ('fixed', 'pool'))
);
CREATE TABLE public.course_blueprint_fixed (
    tenant_id uuid NOT NULL, blueprint_id uuid NOT NULL, position integer NOT NULL,
    problem_id uuid NOT NULL, version_id uuid NOT NULL, points_possible numeric(16, 4) NOT NULL,
    scoring_mode text NOT NULL,
    PRIMARY KEY (tenant_id, blueprint_id, position),
    FOREIGN KEY (tenant_id, blueprint_id, position) REFERENCES public.course_blueprint_entry ON DELETE CASCADE,
    FOREIGN KEY (problem_id, version_id) REFERENCES public.problem_version ON DELETE RESTRICT,
    CHECK (points_possible >= 0), CHECK (scoring_mode IN ('normal', 'fullCredit', 'extraCredit', 'excluded'))
);
CREATE TABLE public.course_blueprint_pool (
    tenant_id uuid NOT NULL, blueprint_id uuid NOT NULL, position integer NOT NULL,
    draw_count integer NOT NULL, points_per_item numeric(16, 4) NOT NULL,
    ordering_policy text NOT NULL, algorithm_version smallint NOT NULL,
    PRIMARY KEY (tenant_id, blueprint_id, position),
    FOREIGN KEY (tenant_id, blueprint_id, position) REFERENCES public.course_blueprint_entry ON DELETE CASCADE,
    CHECK (draw_count > 0), CHECK (points_per_item >= 0),
    CHECK (ordering_policy IN ('candidateOrder', 'randomized')), CHECK (algorithm_version = 1)
);
CREATE TABLE public.course_blueprint_pool_candidate (
    tenant_id uuid NOT NULL, blueprint_id uuid NOT NULL, pool_position integer NOT NULL,
    position integer NOT NULL, problem_id uuid NOT NULL, version_id uuid NOT NULL,
    PRIMARY KEY (tenant_id, blueprint_id, pool_position, position),
    UNIQUE (tenant_id, blueprint_id, pool_position, problem_id, version_id),
    FOREIGN KEY (tenant_id, blueprint_id, pool_position) REFERENCES public.course_blueprint_pool ON DELETE CASCADE,
    FOREIGN KEY (problem_id, version_id) REFERENCES public.problem_version ON DELETE RESTRICT,
    CHECK (position >= 0)
);

CREATE TABLE public.alpha_course (
    alpha_course_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    alpha_course_reference integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.alpha_course_reference_seq),
    creator_tenant_id uuid NOT NULL, creator_user_id uuid NOT NULL, title text NOT NULL,
    creator_public_byline text[] NOT NULL, semantic_sha256 bytea NOT NULL,
    revision bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    UNIQUE (alpha_course_reference),
    FOREIGN KEY (creator_user_id) REFERENCES public.ple_account(user_id) ON DELETE RESTRICT,
    CHECK (alpha_course_reference > 0), CHECK (char_length(title) BETWEEN 1 AND 200 AND title = btrim(title)),
    CHECK (public.ple_valid_public_byline(creator_public_byline)),
    CHECK (octet_length(semantic_sha256) = 32), CHECK (revision > 0)
);
CREATE TABLE public.alpha_course_module (
    alpha_course_id uuid NOT NULL, position integer NOT NULL, label text NOT NULL,
    PRIMARY KEY (alpha_course_id, position), FOREIGN KEY (alpha_course_id) REFERENCES public.alpha_course ON DELETE CASCADE,
    CHECK (position >= 0), CHECK (char_length(label) BETWEEN 1 AND 200 AND label = btrim(label))
);
CREATE TABLE public.alpha_course_definition (
    alpha_course_id uuid NOT NULL, module_position integer NOT NULL, position integer NOT NULL,
    definition_json jsonb NOT NULL,
    PRIMARY KEY (alpha_course_id, module_position, position),
    FOREIGN KEY (alpha_course_id, module_position) REFERENCES public.alpha_course_module ON DELETE CASCADE,
    CHECK (position >= 0), CHECK (jsonb_typeof(definition_json) = 'object')
);
CREATE TABLE public.alpha_course_entry (
    alpha_course_id uuid NOT NULL, module_position integer NOT NULL, definition_position integer NOT NULL,
    position integer NOT NULL, kind text NOT NULL,
    PRIMARY KEY (alpha_course_id, module_position, definition_position, position),
    FOREIGN KEY (alpha_course_id, module_position, definition_position)
        REFERENCES public.alpha_course_definition ON DELETE CASCADE,
    CHECK (position >= 0), CHECK (kind IN ('fixed', 'pool'))
);
CREATE TABLE public.alpha_course_fixed (
    alpha_course_id uuid NOT NULL, module_position integer NOT NULL, definition_position integer NOT NULL,
    position integer NOT NULL, problem_id uuid NOT NULL, version_id uuid NOT NULL,
    points_possible numeric(16, 4) NOT NULL, scoring_mode text NOT NULL,
    PRIMARY KEY (alpha_course_id, module_position, definition_position, position),
    FOREIGN KEY (alpha_course_id, module_position, definition_position, position)
        REFERENCES public.alpha_course_entry ON DELETE CASCADE,
    FOREIGN KEY (problem_id, version_id) REFERENCES public.problem_version ON DELETE RESTRICT,
    CHECK (points_possible >= 0), CHECK (scoring_mode IN ('normal', 'fullCredit', 'extraCredit', 'excluded'))
);
CREATE TABLE public.alpha_course_pool (
    alpha_course_id uuid NOT NULL, module_position integer NOT NULL, definition_position integer NOT NULL,
    position integer NOT NULL, draw_count integer NOT NULL, points_per_item numeric(16, 4) NOT NULL,
    ordering_policy text NOT NULL, algorithm_version smallint NOT NULL,
    PRIMARY KEY (alpha_course_id, module_position, definition_position, position),
    FOREIGN KEY (alpha_course_id, module_position, definition_position, position)
        REFERENCES public.alpha_course_entry ON DELETE CASCADE,
    CHECK (draw_count > 0), CHECK (points_per_item >= 0),
    CHECK (ordering_policy IN ('candidateOrder', 'randomized')), CHECK (algorithm_version = 1)
);
CREATE TABLE public.alpha_course_pool_candidate (
    alpha_course_id uuid NOT NULL, module_position integer NOT NULL, definition_position integer NOT NULL,
    pool_position integer NOT NULL, position integer NOT NULL, problem_id uuid NOT NULL, version_id uuid NOT NULL,
    PRIMARY KEY (alpha_course_id, module_position, definition_position, pool_position, position),
    UNIQUE (alpha_course_id, module_position, definition_position, pool_position, problem_id, version_id),
    FOREIGN KEY (alpha_course_id, module_position, definition_position, pool_position)
        REFERENCES public.alpha_course_pool ON DELETE CASCADE,
    FOREIGN KEY (problem_id, version_id) REFERENCES public.problem_version ON DELETE RESTRICT,
    CHECK (position >= 0)
);

-- Exact qmodel input shape.  JSONB retains only title, instructions, defaults,
-- and relative schedule; normalized rows retain the interleaved entries/pins.
CREATE FUNCTION public.ple_reusable_definition_v1_is_valid(p_definition jsonb)
RETURNS boolean LANGUAGE plpgsql IMMUTABLE PARALLEL SAFE SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE entry_value jsonb; moment_value jsonb; candidate_count integer;
BEGIN
    IF jsonb_typeof(p_definition) <> 'object'
       OR NOT p_definition ?& ARRAY['title', 'instructions', 'entries', 'defaults', 'schedule']
       OR (SELECT count(*) FROM jsonb_object_keys(p_definition)) <> 5
       OR jsonb_typeof(p_definition->'title') <> 'string'
       OR char_length(p_definition->>'title') NOT BETWEEN 1 AND 200
       OR p_definition->>'title' <> btrim(p_definition->>'title')
       OR jsonb_typeof(p_definition->'instructions') <> 'string'
       OR jsonb_typeof(p_definition->'entries') <> 'array'
       OR jsonb_array_length(p_definition->'entries') NOT BETWEEN 1 AND 1024
       OR jsonb_typeof(p_definition->'defaults') <> 'object'
       OR NOT p_definition->'defaults' ?& ARRAY['timeLimitSeconds', 'attemptLimit', 'lateSubmission', 'deadlineBehavior', 'runPolicies', 'learnerDisclosure']
       OR (SELECT count(*) FROM jsonb_object_keys(p_definition->'defaults')) <> 6
       OR p_definition->'defaults'->>'lateSubmission' NOT IN ('accept', 'markLate', 'reject')
       OR p_definition->'defaults'->>'deadlineBehavior' <> 'autoSubmit'
       OR jsonb_typeof(p_definition->'defaults'->'runPolicies') <> 'object'
       OR jsonb_typeof(p_definition->'defaults'->'learnerDisclosure') <> 'object'
       OR jsonb_typeof(p_definition->'schedule') <> 'object'
       OR NOT p_definition->'schedule' ?& ARRAY['availableAt', 'dueAt', 'closesAt']
       OR (SELECT count(*) FROM jsonb_object_keys(p_definition->'schedule')) <> 3 THEN RETURN false; END IF;
    FOR moment_value IN SELECT value FROM jsonb_each(p_definition->'schedule') LOOP
        IF moment_value <> 'null'::jsonb AND (jsonb_typeof(moment_value) <> 'object' OR NOT moment_value ?& ARRAY['dayOffset', 'localTime'] OR (SELECT count(*) FROM jsonb_object_keys(moment_value)) <> 2 OR jsonb_typeof(moment_value->'dayOffset') <> 'number' OR (moment_value->>'dayOffset')::numeric <> trunc((moment_value->>'dayOffset')::numeric) OR (moment_value->>'dayOffset')::numeric NOT BETWEEN -2147483648 AND 2147483647 OR moment_value->>'localTime' !~ '^([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\\.[0-9]{3}$') THEN RETURN false; END IF;
    END LOOP;
    FOR entry_value IN SELECT value FROM jsonb_array_elements(p_definition->'entries') LOOP
        IF jsonb_typeof(entry_value) <> 'object' OR entry_value->>'kind' NOT IN ('fixed', 'pool') THEN RETURN false; END IF;
        IF entry_value->>'kind' = 'fixed' AND (NOT entry_value ?& ARRAY['kind','questionId','pointsPossible','scoringMode'] OR (SELECT count(*) FROM jsonb_object_keys(entry_value)) <> 4 OR entry_value->>'questionId' !~ '^[0-9A-HJKMNP-TV-Z]{3}-[0-9A-HJKMNP-TV-Z]{4}$' OR jsonb_typeof(entry_value->'pointsPossible') <> 'string' OR entry_value->>'pointsPossible' !~ '^[0-9]{1,10}(\.[0-9]{1,4})?$' OR (entry_value->>'pointsPossible')::numeric > 1000000000.9999 OR entry_value->>'scoringMode' NOT IN ('normal','fullCredit','extraCredit','excluded')) THEN RETURN false; END IF;
        IF entry_value->>'kind' = 'pool' THEN
            SELECT count(*) INTO candidate_count FROM jsonb_array_elements_text(entry_value->'candidates');
            IF NOT entry_value ?& ARRAY['kind','candidates','drawCount','pointsPerItem','ordering','algorithm'] OR (SELECT count(*) FROM jsonb_object_keys(entry_value)) <> 6 OR jsonb_typeof(entry_value->'candidates') <> 'array' OR candidate_count NOT BETWEEN 1 AND 1024 OR (entry_value->>'drawCount')::integer NOT BETWEEN 1 AND candidate_count OR jsonb_typeof(entry_value->'pointsPerItem') <> 'string' OR entry_value->>'pointsPerItem' !~ '^[0-9]{1,10}(\.[0-9]{1,4})?$' OR (entry_value->>'pointsPerItem')::numeric > 1000000000.9999 OR entry_value->>'ordering' NOT IN ('candidateOrder','randomized') OR entry_value->>'algorithm' <> 'v1' OR EXISTS (SELECT 1 FROM jsonb_array_elements_text(entry_value->'candidates') AS candidate(question_id) WHERE candidate.question_id !~ '^[0-9A-HJKMNP-TV-Z]{3}-[0-9A-HJKMNP-TV-Z]{4}$') OR (SELECT count(DISTINCT candidate.question_id) FROM jsonb_array_elements_text(entry_value->'candidates') AS candidate(question_id)) <> candidate_count THEN RETURN false; END IF;
        END IF;
    END LOOP;
    RETURN true;
END $$;
CREATE FUNCTION public.ple_reusable_alpha_v1_is_valid(p_alpha jsonb)
RETURNS boolean LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT coalesce(jsonb_typeof(p_alpha) = 'object' AND p_alpha ?& ARRAY['title','modules']
      AND (SELECT count(*) FROM jsonb_object_keys(p_alpha)) = 2 AND jsonb_typeof(p_alpha->'title') = 'string'
      AND char_length(p_alpha->>'title') BETWEEN 1 AND 200 AND p_alpha->>'title' = btrim(p_alpha->>'title')
      AND jsonb_typeof(p_alpha->'modules') = 'array' AND jsonb_array_length(p_alpha->'modules') BETWEEN 1 AND 1024
      AND NOT EXISTS (SELECT 1 FROM jsonb_array_elements(p_alpha->'modules') AS module(value)
          WHERE jsonb_typeof(module.value) <> 'object' OR NOT module.value ?& ARRAY['label','definitions']
             OR (SELECT count(*) FROM jsonb_object_keys(module.value)) <> 2 OR jsonb_typeof(module.value->'label') <> 'string'
             OR char_length(module.value->>'label') NOT BETWEEN 1 AND 200 OR module.value->>'label' <> btrim(module.value->>'label')
             OR jsonb_typeof(module.value->'definitions') <> 'array' OR jsonb_array_length(module.value->'definitions') NOT BETWEEN 1 AND 1024
             OR EXISTS (SELECT 1 FROM jsonb_array_elements(module.value->'definitions') AS definition(value)
                        WHERE NOT public.ple_reusable_definition_v1_is_valid(definition.value))), false)
$$;

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ple_reusable_curriculum_broker') THEN
        CREATE ROLE ple_reusable_curriculum_broker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
    END IF;
END $$;
ALTER ROLE ple_reusable_curriculum_broker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
REVOKE ALL ON SCHEMA public FROM ple_reusable_curriculum_broker;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM ple_reusable_curriculum_broker;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM ple_reusable_curriculum_broker;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM ple_reusable_curriculum_broker;
GRANT USAGE ON SCHEMA public TO ple_reusable_curriculum_broker;
DO $$
DECLARE relation_name text;
BEGIN
    FOREACH relation_name IN ARRAY ARRAY[
        'course_blueprint', 'course_blueprint_entry', 'course_blueprint_fixed',
        'course_blueprint_pool', 'course_blueprint_pool_candidate', 'alpha_course',
        'alpha_course_module', 'alpha_course_definition', 'alpha_course_entry',
        'alpha_course_fixed', 'alpha_course_pool', 'alpha_course_pool_candidate'
    ] LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', relation_name);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', relation_name);
    END LOOP;
END $$;
CREATE POLICY reusable_blueprint_broker ON public.course_blueprint TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY reusable_blueprint_entry_broker ON public.course_blueprint_entry TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY reusable_blueprint_fixed_broker ON public.course_blueprint_fixed TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY reusable_blueprint_pool_broker ON public.course_blueprint_pool TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY reusable_blueprint_candidate_broker ON public.course_blueprint_pool_candidate TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant()) WITH CHECK (tenant_id = public.ple_current_tenant());
CREATE POLICY reusable_alpha_broker ON public.alpha_course TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_alpha_module_broker ON public.alpha_course_module TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_alpha_definition_broker ON public.alpha_course_definition TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_alpha_entry_broker ON public.alpha_course_entry TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_alpha_fixed_broker ON public.alpha_course_fixed TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_alpha_pool_broker ON public.alpha_course_pool TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_alpha_candidate_broker ON public.alpha_course_pool_candidate TO ple_reusable_curriculum_broker USING (true) WITH CHECK (true);
CREATE POLICY reusable_session_broker ON public.auth_session FOR SELECT TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant());
-- Alpha attribution is derived inside the broker.  This policy permits only
-- the display record of an active session actor in the current tenant; it is
-- not a general account-directory capability.
CREATE POLICY reusable_account_broker ON public.ple_account FOR SELECT TO ple_reusable_curriculum_broker
    USING (EXISTS (
        SELECT 1 FROM public.auth_session AS session
         WHERE session.user_id = ple_account.user_id
           AND session.tenant_id = public.ple_current_tenant()
           AND session.revoked_at IS NULL AND session.expires_at > transaction_timestamp()
    ));
CREATE POLICY reusable_catalog_broker ON public.catalog_search_document FOR SELECT TO ple_reusable_curriculum_broker
    USING (
        (lifecycle = 'published' AND (publication_scope = 'public' OR EXISTS (
            SELECT 1 FROM public.catalog_tenant_grant AS grant_row
             WHERE grant_row.tenant_id = public.ple_current_tenant()
               AND grant_row.problem_id = catalog_search_document.problem_id
               AND grant_row.version_id = catalog_search_document.version_id
        ))) OR EXISTS (
            SELECT 1 FROM public.course_blueprint_fixed AS fixed_row
             WHERE fixed_row.tenant_id = public.ple_current_tenant()
               AND fixed_row.problem_id = catalog_search_document.problem_id
               AND fixed_row.version_id = catalog_search_document.version_id
        ) OR EXISTS (
            SELECT 1 FROM public.course_blueprint_pool_candidate AS candidate
             WHERE candidate.tenant_id = public.ple_current_tenant()
               AND candidate.problem_id = catalog_search_document.problem_id
               AND candidate.version_id = catalog_search_document.version_id
        ) OR EXISTS (
            SELECT 1 FROM public.alpha_course_fixed AS fixed_row
             WHERE fixed_row.problem_id = catalog_search_document.problem_id
               AND fixed_row.version_id = catalog_search_document.version_id
        ) OR EXISTS (
            SELECT 1 FROM public.alpha_course_pool_candidate AS candidate
             WHERE candidate.problem_id = catalog_search_document.problem_id
               AND candidate.version_id = catalog_search_document.version_id
        )
    );
CREATE POLICY reusable_catalog_grant_broker ON public.catalog_tenant_grant FOR SELECT TO ple_reusable_curriculum_broker USING (tenant_id = public.ple_current_tenant());
CREATE POLICY reusable_catalog_evidence_broker ON public.catalog_discovery_evidence_revision
    FOR SELECT TO ple_reusable_curriculum_broker
    USING (
        EXISTS (SELECT 1 FROM public.course_blueprint_fixed AS fixed_row
                 WHERE fixed_row.tenant_id = public.ple_current_tenant()
                   AND fixed_row.problem_id = catalog_discovery_evidence_revision.problem_id
                   AND fixed_row.version_id = catalog_discovery_evidence_revision.version_id)
        OR EXISTS (SELECT 1 FROM public.course_blueprint_pool_candidate AS candidate
                   WHERE candidate.tenant_id = public.ple_current_tenant()
                     AND candidate.problem_id = catalog_discovery_evidence_revision.problem_id
                     AND candidate.version_id = catalog_discovery_evidence_revision.version_id)
        OR EXISTS (SELECT 1 FROM public.alpha_course_fixed AS fixed_row
                   WHERE fixed_row.problem_id = catalog_discovery_evidence_revision.problem_id
                     AND fixed_row.version_id = catalog_discovery_evidence_revision.version_id)
        OR EXISTS (SELECT 1 FROM public.alpha_course_pool_candidate AS candidate
                   WHERE candidate.problem_id = catalog_discovery_evidence_revision.problem_id
                     AND candidate.version_id = catalog_discovery_evidence_revision.version_id)
    );
GRANT SELECT, INSERT, UPDATE, DELETE ON public.course_blueprint, public.course_blueprint_entry, public.course_blueprint_fixed, public.course_blueprint_pool, public.course_blueprint_pool_candidate, public.alpha_course, public.alpha_course_module, public.alpha_course_definition, public.alpha_course_entry, public.alpha_course_fixed, public.alpha_course_pool, public.alpha_course_pool_candidate TO ple_reusable_curriculum_broker;
GRANT SELECT ON public.auth_session, public.catalog_search_document, public.catalog_tenant_grant, public.catalog_discovery_evidence_revision, public.ple_account, public.problem, public.problem_version TO ple_reusable_curriculum_broker;
GRANT USAGE ON SEQUENCE public.course_blueprint_reference_seq, public.alpha_course_reference_seq TO ple_reusable_curriculum_broker;
GRANT EXECUTE ON FUNCTION public.ple_current_tenant(), public.ple_catalog_discovery_actor(character, uuid), public.ple_catalog_discovery_evidence_at(uuid, uuid, bigint), public.ple_instructor_approval_eligible(uuid), public.ple_valid_public_byline(text[]) TO ple_reusable_curriculum_broker;

CREATE FUNCTION public.ple_reusable_curriculum_instructor_actor(p_session character(64), p_tenant uuid)
RETURNS TABLE (user_id uuid) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN RAISE EXCEPTION 'reusable curriculum request has a valid tenant and session' USING ERRCODE = '22023'; END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_catalog_discovery_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    IF NOT EXISTS (SELECT 1 FROM public.auth_session AS session WHERE session.user_id = v_actor AND session.tenant_id = p_tenant AND session.session_hash = p_session AND session.revoked_at IS NULL AND session.expires_at > transaction_timestamp() AND session.roles @> '["instructor"]'::jsonb) OR NOT public.ple_instructor_approval_eligible(v_actor) THEN RAISE EXCEPTION 'reusable curriculum requires approved Instructor authority' USING ERRCODE = '42501'; END IF;
    user_id := v_actor; RETURN NEXT;
END $$;
CREATE FUNCTION public.ple_reusable_curriculum_preflight_v1(p_tenant uuid, p_session character(64), p_capability text)
RETURNS boolean LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
BEGIN
    IF p_capability NOT IN ('blueprintPersonal', 'alphaRead', 'alphaCreatorWrite') THEN RAISE EXCEPTION 'reusable curriculum capability is recognized' USING ERRCODE = '22023'; END IF;
    RETURN EXISTS (SELECT 1 FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant));
END $$;
CREATE FUNCTION public.ple_reusable_resolve_definition_v1(p_tenant uuid, p_definition jsonb, p_public_only boolean)
RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_requested integer; v_resolved integer;
BEGIN
    SELECT count(*) INTO v_requested FROM jsonb_array_elements(p_definition->'entries') AS entry(value) CROSS JOIN LATERAL jsonb_array_elements_text(CASE WHEN entry.value->>'kind' = 'fixed' THEN jsonb_build_array(entry.value->>'questionId') ELSE entry.value->'candidates' END) AS question(question_id);
    SELECT count(*) INTO v_resolved FROM jsonb_array_elements(p_definition->'entries') AS entry(value) CROSS JOIN LATERAL jsonb_array_elements_text(CASE WHEN entry.value->>'kind' = 'fixed' THEN jsonb_build_array(entry.value->>'questionId') ELSE entry.value->'candidates' END) AS question(question_id) JOIN public.catalog_search_document AS document ON document.question_id = replace(question.question_id, '-', '') AND document.lifecycle = 'published' AND (NOT p_public_only OR document.publication_scope = 'public');
    IF v_requested <> v_resolved THEN RAISE EXCEPTION 'reusable definition resolves every visible published Question ID' USING ERRCODE = '22023'; END IF;
END $$;
CREATE FUNCTION public.ple_reusable_pinned_catalog_v1(p_problem_id uuid, p_version_id uuid)
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT jsonb_build_object(
        'questionId', document.question_id, 'selectionAvailable',
        document.lifecycle = 'published' AND (
            document.publication_scope = 'public' OR EXISTS (
                SELECT 1 FROM public.catalog_tenant_grant AS grant_row
                 WHERE grant_row.tenant_id = public.ple_current_tenant()
                   AND grant_row.problem_id = document.problem_id
                   AND grant_row.version_id = document.version_id
            )
        ),
        'backend', document.backend, 'responseFamily', document.response_family,
        'capabilities', document.capabilities, 'metadata', document.metadata,
        'byline', jsonb_build_object('names', document.public_byline),
        'scope', document.publication_scope,
        'lifecycle', CASE WHEN document.lifecycle = 'published' THEN
            jsonb_build_object('state', 'published')
        ELSE jsonb_build_object('state', document.lifecycle, 'reason', document.lifecycle_reason)
        END,
        'publishedAt', floor(extract(epoch FROM document.published_at) * 1000)::bigint,
        'evidence', CASE WHEN evidence.evidence_sequence IS NULL THEN
            jsonb_build_object('state', 'insufficientEvidence')
        ELSE jsonb_build_object(
            'state', 'available', 'formulaVersion', evidence.formula_version,
            'observedCourseCount', evidence.course_count,
            'independentLearnerObservationCount', evidence.first_attempt_count,
            'difficultyIndex', evidence.difficulty_index, 'attemptsMean', evidence.attempts_mean,
            'timeMedianSecondsEstimate', evidence.time_median_seconds_estimate,
            'discriminationIndex', evidence.discrimination_index,
            'evidenceAt', floor(extract(epoch FROM evidence.evidence_at) * 1000)::bigint
        ) END
    ) FROM public.catalog_search_document AS document
    LEFT JOIN LATERAL public.ple_catalog_discovery_evidence_at(
        document.problem_id, document.version_id,
        (SELECT coalesce(max(evidence_sequence), 0) FROM public.catalog_discovery_evidence_revision)
    ) AS evidence ON true
     WHERE document.problem_id = p_problem_id AND document.version_id = p_version_id
$$;

-- Replacement first validates and resolves every Question ID.  The parent lock,
-- digest comparison, and child delete/insert form one transaction boundary.
CREATE FUNCTION public.ple_replace_curriculum_blueprint_v1(p_tenant uuid, p_session character(64), p_reference integer, p_expected_revision bigint, p_definition jsonb)
RETURNS TABLE (blueprint_reference integer, revision bigint) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_blueprint public.course_blueprint%ROWTYPE; v_digest bytea; v_changed boolean;
BEGIN
    IF (p_expected_revision IS NOT NULL AND p_expected_revision < 1) OR NOT public.ple_reusable_definition_v1_is_valid(p_definition) THEN RAISE EXCEPTION 'Blueprint replacement carries one complete valid definition' USING ERRCODE = '22023'; END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN; END IF;
    PERFORM public.ple_reusable_resolve_definition_v1(p_tenant, p_definition, false); v_digest := digest(convert_to(p_definition::text, 'UTF8'), 'sha256');
    IF p_reference IS NULL THEN
        IF p_expected_revision IS NOT NULL THEN RAISE EXCEPTION 'new Blueprint uses no prior revision' USING ERRCODE = '55000'; END IF;
        INSERT INTO public.course_blueprint (tenant_id, owner_user_id, definition_json, semantic_sha256) VALUES (p_tenant, v_actor, p_definition - 'entries', v_digest) RETURNING * INTO v_blueprint; v_changed := true;
    ELSE
        SELECT blueprint.* INTO v_blueprint FROM public.course_blueprint AS blueprint WHERE blueprint.tenant_id = p_tenant AND blueprint.blueprint_reference = p_reference AND blueprint.owner_user_id = v_actor FOR UPDATE; IF NOT FOUND THEN RETURN; END IF;
        IF p_expected_revision IS NULL OR v_blueprint.revision <> p_expected_revision THEN RAISE EXCEPTION 'Blueprint revision is current before replacement' USING ERRCODE = '55000'; END IF;
        v_changed := v_blueprint.semantic_sha256 IS DISTINCT FROM v_digest;
        IF v_changed THEN DELETE FROM public.course_blueprint_entry WHERE tenant_id = p_tenant AND blueprint_id = v_blueprint.blueprint_id; UPDATE public.course_blueprint AS blueprint SET definition_json = p_definition - 'entries', semantic_sha256 = v_digest, revision = blueprint.revision + 1, updated_at = transaction_timestamp() WHERE blueprint.tenant_id = p_tenant AND blueprint.blueprint_id = v_blueprint.blueprint_id RETURNING blueprint.* INTO v_blueprint; END IF;
    END IF;
    IF v_changed THEN
        INSERT INTO public.course_blueprint_entry SELECT p_tenant, v_blueprint.blueprint_id, ordinal - 1, entry.value->>'kind' FROM jsonb_array_elements(p_definition->'entries') WITH ORDINALITY AS entry(value, ordinal);
        INSERT INTO public.course_blueprint_fixed SELECT p_tenant, v_blueprint.blueprint_id, ordinal - 1, document.problem_id, document.version_id, (entry.value->>'pointsPossible')::numeric, entry.value->>'scoringMode' FROM jsonb_array_elements(p_definition->'entries') WITH ORDINALITY AS entry(value, ordinal) JOIN public.catalog_search_document AS document ON document.question_id = replace(entry.value->>'questionId', '-', '') WHERE entry.value->>'kind' = 'fixed';
        INSERT INTO public.course_blueprint_pool SELECT p_tenant, v_blueprint.blueprint_id, ordinal - 1, (entry.value->>'drawCount')::integer, (entry.value->>'pointsPerItem')::numeric, entry.value->>'ordering', 1 FROM jsonb_array_elements(p_definition->'entries') WITH ORDINALITY AS entry(value, ordinal) WHERE entry.value->>'kind' = 'pool';
        INSERT INTO public.course_blueprint_pool_candidate SELECT p_tenant, v_blueprint.blueprint_id, entry.ordinal - 1, candidate.ordinal - 1, document.problem_id, document.version_id FROM jsonb_array_elements(p_definition->'entries') WITH ORDINALITY AS entry(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements_text(entry.value->'candidates') WITH ORDINALITY AS candidate(question_id, ordinal) JOIN public.catalog_search_document AS document ON document.question_id = replace(candidate.question_id, '-', '') WHERE entry.value->>'kind' = 'pool';
    END IF;
    blueprint_reference := v_blueprint.blueprint_reference; revision := v_blueprint.revision; RETURN NEXT;
END $$;
CREATE FUNCTION public.ple_delete_curriculum_blueprint_v1(p_tenant uuid, p_session character(64), p_reference integer, p_expected_revision bigint)
RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_blueprint public.course_blueprint%ROWTYPE;
BEGIN
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN false; END IF;
    SELECT * INTO v_blueprint FROM public.course_blueprint WHERE tenant_id = p_tenant AND blueprint_reference = p_reference AND owner_user_id = v_actor FOR UPDATE; IF NOT FOUND THEN RETURN false; END IF;
    IF p_expected_revision IS NULL OR p_expected_revision < 1 OR v_blueprint.revision <> p_expected_revision THEN RAISE EXCEPTION 'Blueprint deletion uses the current revision' USING ERRCODE = '55000'; END IF;
    DELETE FROM public.course_blueprint WHERE tenant_id = p_tenant AND blueprint_id = v_blueprint.blueprint_id; RETURN true;
END $$;
CREATE FUNCTION public.ple_list_curriculum_blueprints_v1(p_tenant uuid, p_session character(64), p_after_reference integer, p_limit integer)
RETURNS TABLE (blueprint_reference integer, title text, revision bigint) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_limit NOT BETWEEN 1 AND 101 OR (p_after_reference IS NOT NULL AND p_after_reference < 1) THEN RAISE EXCEPTION 'Blueprint page carries a bounded route cursor' USING ERRCODE = '22023'; END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY SELECT b.blueprint_reference, b.definition_json->>'title', b.revision FROM public.course_blueprint AS b WHERE b.tenant_id = p_tenant AND b.owner_user_id = v_actor AND (p_after_reference IS NULL OR b.blueprint_reference > p_after_reference) ORDER BY b.blueprint_reference LIMIT p_limit;
END $$;
CREATE FUNCTION public.ple_get_curriculum_blueprint_v1(p_tenant uuid, p_session character(64), p_reference integer)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid; v_blueprint public.course_blueprint%ROWTYPE;
BEGIN
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT * INTO v_blueprint FROM public.course_blueprint WHERE tenant_id = p_tenant AND owner_user_id = v_actor AND blueprint_reference = p_reference; IF NOT FOUND THEN RETURN NULL; END IF;
    RETURN jsonb_build_object(
        'blueprintId', v_blueprint.blueprint_id, 'reference', v_blueprint.blueprint_reference,
        'revision', v_blueprint.revision, 'access', 'owner', 'definition',
        v_blueprint.definition_json || jsonb_build_object('entries', coalesce((
            SELECT jsonb_agg(entry_document.document ORDER BY entry_document.position)
              FROM (
                SELECT entry_row.position, jsonb_build_object(
                    'kind', 'fixed', 'problemId', fixed_row.problem_id,
                    'versionId', fixed_row.version_id, 'catalog',
                    public.ple_reusable_pinned_catalog_v1(fixed_row.problem_id, fixed_row.version_id),
                    'pointsPossible', fixed_row.points_possible::text,
                    'scoringMode', fixed_row.scoring_mode
                ) AS document
                  FROM public.course_blueprint_entry AS entry_row
                  JOIN public.course_blueprint_fixed AS fixed_row
                    ON fixed_row.tenant_id = entry_row.tenant_id
                   AND fixed_row.blueprint_id = entry_row.blueprint_id
                   AND fixed_row.position = entry_row.position
                 WHERE entry_row.tenant_id = p_tenant AND entry_row.blueprint_id = v_blueprint.blueprint_id
                   AND entry_row.kind = 'fixed'
                UNION ALL
                SELECT entry_row.position, jsonb_build_object(
                    'kind', 'pool', 'drawCount', pool_row.draw_count,
                    'pointsPerItem', pool_row.points_per_item::text,
                    'ordering', pool_row.ordering_policy,
                    'algorithm', 'v1', 'candidates', coalesce((
                        SELECT jsonb_agg(jsonb_build_object(
                            'problemId', candidate.problem_id, 'versionId', candidate.version_id,
                            'catalog', public.ple_reusable_pinned_catalog_v1(candidate.problem_id, candidate.version_id)
                        ) ORDER BY candidate.position)
                          FROM public.course_blueprint_pool_candidate AS candidate
                         WHERE candidate.tenant_id = pool_row.tenant_id
                           AND candidate.blueprint_id = pool_row.blueprint_id
                           AND candidate.pool_position = pool_row.position
                    ), '[]'::jsonb)
                ) AS document
                  FROM public.course_blueprint_entry AS entry_row
                  JOIN public.course_blueprint_pool AS pool_row
                    ON pool_row.tenant_id = entry_row.tenant_id
                   AND pool_row.blueprint_id = entry_row.blueprint_id
                   AND pool_row.position = entry_row.position
                 WHERE entry_row.tenant_id = p_tenant AND entry_row.blueprint_id = v_blueprint.blueprint_id
                   AND entry_row.kind = 'pool'
            ) AS entry_document
        ), '[]'::jsonb))
    );
END $$;

-- Alpha creates/replaces its complete labelled tree under the creator's lock.
CREATE FUNCTION public.ple_replace_curriculum_alpha_v1(p_tenant uuid, p_session character(64), p_reference integer, p_expected_revision bigint, p_alpha jsonb)
RETURNS TABLE (alpha_course_reference integer, revision bigint) LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_alpha public.alpha_course%ROWTYPE; v_digest bytea; v_byline text[]; v_changed boolean;
BEGIN
    IF (p_expected_revision IS NOT NULL AND p_expected_revision < 1) OR NOT public.ple_reusable_alpha_v1_is_valid(p_alpha) THEN RAISE EXCEPTION 'Alpha replacement carries a complete valid curriculum' USING ERRCODE = '22023'; END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN; END IF;
    SELECT ARRAY[account.display_name] INTO v_byline FROM public.ple_account AS account WHERE account.user_id = v_actor; IF NOT FOUND OR NOT public.ple_valid_public_byline(v_byline) THEN RAISE EXCEPTION 'Alpha creator has a reviewed public byline' USING ERRCODE = '42501'; END IF;
    PERFORM public.ple_reusable_resolve_definition_v1(p_tenant, definition.value, true) FROM jsonb_array_elements(p_alpha->'modules') AS module(value) CROSS JOIN LATERAL jsonb_array_elements(module.value->'definitions') AS definition(value);
    v_digest := digest(convert_to(p_alpha::text, 'UTF8'), 'sha256');
    IF p_reference IS NULL THEN
        IF p_expected_revision IS NOT NULL THEN RAISE EXCEPTION 'new Alpha uses no prior revision' USING ERRCODE = '55000'; END IF;
        INSERT INTO public.alpha_course (creator_tenant_id, creator_user_id, title, creator_public_byline, semantic_sha256) VALUES (p_tenant, v_actor, p_alpha->>'title', v_byline, v_digest) RETURNING * INTO v_alpha; v_changed := true;
    ELSE
        SELECT alpha.* INTO v_alpha FROM public.alpha_course AS alpha WHERE alpha.alpha_course_reference = p_reference FOR UPDATE; IF NOT FOUND THEN RETURN; END IF;
        IF v_alpha.creator_tenant_id <> p_tenant OR v_alpha.creator_user_id <> v_actor THEN RAISE EXCEPTION 'Alpha replacement has creator authority' USING ERRCODE = '42501'; END IF;
        IF p_expected_revision IS NULL OR v_alpha.revision <> p_expected_revision THEN RAISE EXCEPTION 'Alpha revision is current before replacement' USING ERRCODE = '55000'; END IF;
        v_changed := v_alpha.semantic_sha256 IS DISTINCT FROM v_digest;
        IF v_changed THEN DELETE FROM public.alpha_course_module WHERE alpha_course_id = v_alpha.alpha_course_id; UPDATE public.alpha_course AS alpha SET title = p_alpha->>'title', semantic_sha256 = v_digest, revision = alpha.revision + 1, updated_at = transaction_timestamp() WHERE alpha.alpha_course_id = v_alpha.alpha_course_id RETURNING alpha.* INTO v_alpha; END IF;
    END IF;
    IF v_changed THEN
        INSERT INTO public.alpha_course_module SELECT v_alpha.alpha_course_id, module.ordinal - 1, module.value->>'label' FROM jsonb_array_elements(p_alpha->'modules') WITH ORDINALITY AS module(value, ordinal);
        INSERT INTO public.alpha_course_definition SELECT v_alpha.alpha_course_id, module.ordinal - 1, definition.ordinal - 1, definition.value - 'entries' FROM jsonb_array_elements(p_alpha->'modules') WITH ORDINALITY AS module(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(module.value->'definitions') WITH ORDINALITY AS definition(value, ordinal);
        INSERT INTO public.alpha_course_entry SELECT v_alpha.alpha_course_id, module.ordinal - 1, definition.ordinal - 1, entry.ordinal - 1, entry.value->>'kind' FROM jsonb_array_elements(p_alpha->'modules') WITH ORDINALITY AS module(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(module.value->'definitions') WITH ORDINALITY AS definition(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(definition.value->'entries') WITH ORDINALITY AS entry(value, ordinal);
        INSERT INTO public.alpha_course_fixed SELECT v_alpha.alpha_course_id, module.ordinal - 1, definition.ordinal - 1, entry.ordinal - 1, document.problem_id, document.version_id, (entry.value->>'pointsPossible')::numeric, entry.value->>'scoringMode' FROM jsonb_array_elements(p_alpha->'modules') WITH ORDINALITY AS module(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(module.value->'definitions') WITH ORDINALITY AS definition(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(definition.value->'entries') WITH ORDINALITY AS entry(value, ordinal) JOIN public.catalog_search_document AS document ON document.question_id = replace(entry.value->>'questionId', '-', '') WHERE entry.value->>'kind' = 'fixed';
        INSERT INTO public.alpha_course_pool SELECT v_alpha.alpha_course_id, module.ordinal - 1, definition.ordinal - 1, entry.ordinal - 1, (entry.value->>'drawCount')::integer, (entry.value->>'pointsPerItem')::numeric, entry.value->>'ordering', 1 FROM jsonb_array_elements(p_alpha->'modules') WITH ORDINALITY AS module(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(module.value->'definitions') WITH ORDINALITY AS definition(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(definition.value->'entries') WITH ORDINALITY AS entry(value, ordinal) WHERE entry.value->>'kind' = 'pool';
        INSERT INTO public.alpha_course_pool_candidate SELECT v_alpha.alpha_course_id, module.ordinal - 1, definition.ordinal - 1, entry.ordinal - 1, candidate.ordinal - 1, document.problem_id, document.version_id FROM jsonb_array_elements(p_alpha->'modules') WITH ORDINALITY AS module(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(module.value->'definitions') WITH ORDINALITY AS definition(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements(definition.value->'entries') WITH ORDINALITY AS entry(value, ordinal) CROSS JOIN LATERAL jsonb_array_elements_text(entry.value->'candidates') WITH ORDINALITY AS candidate(question_id, ordinal) JOIN public.catalog_search_document AS document ON document.question_id = replace(candidate.question_id, '-', '') WHERE entry.value->>'kind' = 'pool';
    END IF;
    alpha_course_reference := v_alpha.alpha_course_reference; revision := v_alpha.revision; RETURN NEXT;
END $$;
CREATE FUNCTION public.ple_list_curriculum_alpha_v1(p_tenant uuid, p_session character(64), p_after_reference integer, p_limit integer)
RETURNS TABLE (alpha_course_reference integer, title text, creator_public_byline text[], revision bigint, access text) LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_limit NOT BETWEEN 1 AND 101 OR (p_after_reference IS NOT NULL AND p_after_reference < 1) THEN RAISE EXCEPTION 'Alpha page carries a bounded route cursor' USING ERRCODE = '22023'; END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY SELECT a.alpha_course_reference, a.title, a.creator_public_byline, a.revision, CASE WHEN a.creator_tenant_id = p_tenant AND a.creator_user_id = v_actor THEN 'creator' ELSE 'approvedInstructor' END FROM public.alpha_course AS a WHERE p_after_reference IS NULL OR a.alpha_course_reference > p_after_reference ORDER BY a.alpha_course_reference LIMIT p_limit;
END $$;
CREATE FUNCTION public.ple_get_curriculum_alpha_v1(p_tenant uuid, p_session character(64), p_reference integer)
RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid; v_alpha public.alpha_course%ROWTYPE;
BEGIN
    SELECT actor.user_id INTO v_actor FROM public.ple_reusable_curriculum_instructor_actor(p_session, p_tenant) AS actor; IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT * INTO v_alpha FROM public.alpha_course WHERE alpha_course_reference = p_reference; IF NOT FOUND THEN RETURN NULL; END IF;
    RETURN jsonb_build_object(
        'alphaCourseId', v_alpha.alpha_course_id, 'reference', v_alpha.alpha_course_reference,
        'title', v_alpha.title, 'creatorByline', v_alpha.creator_public_byline,
        'revision', v_alpha.revision,
        'access', CASE WHEN v_alpha.creator_tenant_id = p_tenant AND v_alpha.creator_user_id = v_actor
            THEN 'creator' ELSE 'approvedInstructor' END,
        'modules', coalesce((
            SELECT jsonb_agg(jsonb_build_object('position', module_row.position, 'label', module_row.label,
                'definitions', coalesce((
                    SELECT jsonb_agg(jsonb_build_object(
                        'position', definition_row.position,
                        'definition', definition_row.definition_json || jsonb_build_object('entries', coalesce((
                            SELECT jsonb_agg(entry_document.document ORDER BY entry_document.position)
                              FROM (
                                SELECT entry_row.position, jsonb_build_object(
                                    'kind', 'fixed', 'problemId', fixed_row.problem_id,
                                    'versionId', fixed_row.version_id, 'catalog',
                                    public.ple_reusable_pinned_catalog_v1(fixed_row.problem_id, fixed_row.version_id),
                                    'pointsPossible', fixed_row.points_possible::text,
                                    'scoringMode', fixed_row.scoring_mode
                                ) AS document
                                  FROM public.alpha_course_entry AS entry_row
                                  JOIN public.alpha_course_fixed AS fixed_row
                                    ON (fixed_row.alpha_course_id, fixed_row.module_position,
                                        fixed_row.definition_position, fixed_row.position) =
                                       (entry_row.alpha_course_id, entry_row.module_position,
                                        entry_row.definition_position, entry_row.position)
                                 WHERE (entry_row.alpha_course_id, entry_row.module_position,
                                        entry_row.definition_position) =
                                       (definition_row.alpha_course_id, definition_row.module_position,
                                        definition_row.position)
                                   AND entry_row.kind = 'fixed'
                                UNION ALL
                                SELECT entry_row.position, jsonb_build_object(
                                    'kind', 'pool', 'drawCount', pool_row.draw_count,
                                    'pointsPerItem', pool_row.points_per_item::text,
                                    'ordering', pool_row.ordering_policy, 'algorithm', 'v1',
                                    'candidates', coalesce((
                                        SELECT jsonb_agg(jsonb_build_object(
                                            'problemId', candidate.problem_id,
                                            'versionId', candidate.version_id, 'catalog',
                                            public.ple_reusable_pinned_catalog_v1(candidate.problem_id, candidate.version_id)
                                        ) ORDER BY candidate.position)
                                          FROM public.alpha_course_pool_candidate AS candidate
                                         WHERE (candidate.alpha_course_id, candidate.module_position,
                                                candidate.definition_position, candidate.pool_position) =
                                               (pool_row.alpha_course_id, pool_row.module_position,
                                                pool_row.definition_position, pool_row.position)
                                    ), '[]'::jsonb)
                                ) AS document
                                  FROM public.alpha_course_entry AS entry_row
                                  JOIN public.alpha_course_pool AS pool_row
                                    ON (pool_row.alpha_course_id, pool_row.module_position,
                                        pool_row.definition_position, pool_row.position) =
                                       (entry_row.alpha_course_id, entry_row.module_position,
                                        entry_row.definition_position, entry_row.position)
                                 WHERE (entry_row.alpha_course_id, entry_row.module_position,
                                        entry_row.definition_position) =
                                       (definition_row.alpha_course_id, definition_row.module_position,
                                        definition_row.position)
                                   AND entry_row.kind = 'pool'
                            ) AS entry_document
                        ), '[]'::jsonb))
                    ) ORDER BY definition_row.position)
                      FROM public.alpha_course_definition AS definition_row
                     WHERE definition_row.alpha_course_id = module_row.alpha_course_id
                       AND definition_row.module_position = module_row.position
                ), '[]'::jsonb)) ORDER BY module_row.position)
              FROM public.alpha_course_module AS module_row
             WHERE module_row.alpha_course_id = v_alpha.alpha_course_id
        ), '[]'::jsonb)
    );
END $$;

ALTER FUNCTION public.ple_reusable_definition_v1_is_valid(jsonb) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_reusable_alpha_v1_is_valid(jsonb) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_reusable_curriculum_instructor_actor(character, uuid) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_reusable_curriculum_preflight_v1(uuid, character, text) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_reusable_resolve_definition_v1(uuid, jsonb, boolean) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_reusable_pinned_catalog_v1(uuid, uuid) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_replace_curriculum_blueprint_v1(uuid, character, integer, bigint, jsonb) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_delete_curriculum_blueprint_v1(uuid, character, integer, bigint) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_list_curriculum_blueprints_v1(uuid, character, integer, integer) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_get_curriculum_blueprint_v1(uuid, character, integer) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_replace_curriculum_alpha_v1(uuid, character, integer, bigint, jsonb) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_list_curriculum_alpha_v1(uuid, character, integer, integer) OWNER TO ple_reusable_curriculum_broker;
ALTER FUNCTION public.ple_get_curriculum_alpha_v1(uuid, character, integer) OWNER TO ple_reusable_curriculum_broker;
REVOKE ALL ON FUNCTION public.ple_reusable_definition_v1_is_valid(jsonb), public.ple_reusable_alpha_v1_is_valid(jsonb), public.ple_reusable_curriculum_instructor_actor(character, uuid), public.ple_reusable_resolve_definition_v1(uuid, jsonb, boolean), public.ple_reusable_pinned_catalog_v1(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_reusable_curriculum_preflight_v1(uuid, character, text), public.ple_replace_curriculum_blueprint_v1(uuid, character, integer, bigint, jsonb), public.ple_delete_curriculum_blueprint_v1(uuid, character, integer, bigint), public.ple_list_curriculum_blueprints_v1(uuid, character, integer, integer), public.ple_get_curriculum_blueprint_v1(uuid, character, integer), public.ple_replace_curriculum_alpha_v1(uuid, character, integer, bigint, jsonb), public.ple_list_curriculum_alpha_v1(uuid, character, integer, integer), public.ple_get_curriculum_alpha_v1(uuid, character, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_reusable_curriculum_preflight_v1(uuid, character, text), public.ple_replace_curriculum_blueprint_v1(uuid, character, integer, bigint, jsonb), public.ple_delete_curriculum_blueprint_v1(uuid, character, integer, bigint), public.ple_list_curriculum_blueprints_v1(uuid, character, integer, integer), public.ple_get_curriculum_blueprint_v1(uuid, character, integer), public.ple_replace_curriculum_alpha_v1(uuid, character, integer, bigint, jsonb), public.ple_list_curriculum_alpha_v1(uuid, character, integer, integer), public.ple_get_curriculum_alpha_v1(uuid, character, integer) TO ple_app;
REVOKE ALL ON public.course_blueprint, public.course_blueprint_entry, public.course_blueprint_fixed, public.course_blueprint_pool, public.course_blueprint_pool_candidate, public.alpha_course, public.alpha_course_module, public.alpha_course_definition, public.alpha_course_entry, public.alpha_course_fixed, public.alpha_course_pool, public.alpha_course_pool_candidate FROM ple_app;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_roles AS role_row
         WHERE role_row.rolname = 'ple_reusable_curriculum_broker'
           AND (role_row.rolcanlogin OR role_row.rolsuper OR role_row.rolcreatedb
                OR role_row.rolcreaterole OR role_row.rolinherit OR role_row.rolreplication
                OR role_row.rolbypassrls)
    ) OR NOT EXISTS (
        SELECT 1 FROM pg_catalog.pg_policies AS policy_row
         WHERE policy_row.schemaname = 'public' AND policy_row.tablename = 'ple_account'
           AND policy_row.policyname = 'reusable_account_broker'
           AND policy_row.roles = ARRAY['ple_reusable_curriculum_broker']::name[]
    ) OR has_table_privilege('ple_app', 'public.course_blueprint', 'SELECT')
       OR has_table_privilege('ple_app', 'public.alpha_course', 'SELECT') THEN
        RAISE EXCEPTION 'reusable curriculum broker authority is closed';
    END IF;
END $$;

COMMIT;
