-- WP-PROF-D2: durable, session-authorized personal problem curation.
--
-- Collections deliberately retain exact immutable publication references.  The
-- public locator is only a compact capability input; resolution, authorization,
-- and version pinning remain inside the broker functions below.
-- ASVS 1.5.3, 2.1.1-2.1.3, 2.2.1-2.2.3, 8.1.1-8.3.2, 15.3.3, and 15.3.5:
-- the capability is session-derived, strictly normalized, bounded, and least-privilege.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.problem_collection WHERE visibility = 'public'
    ) THEN
        RAISE EXCEPTION 'legacy public problem collections require an explicit migration';
    END IF;
END
$$;

ALTER TABLE public.problem_collection
    ADD COLUMN collection_reference integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.problem_collection_reference_seq),
    ADD COLUMN kind text;
UPDATE public.problem_collection SET kind = 'named' WHERE kind IS NULL;
ALTER TABLE public.problem_collection
    ALTER COLUMN kind SET NOT NULL,
    ADD CONSTRAINT problem_collection_reference_positive CHECK (collection_reference > 0),
    ADD CONSTRAINT problem_collection_reference_key UNIQUE (collection_reference),
    ADD CONSTRAINT problem_collection_kind_check CHECK (kind IN ('favorites', 'named')),
    ADD CONSTRAINT problem_collection_favorites_shape_check CHECK (
        (kind = 'favorites' AND visibility = 'private' AND title = 'Favorites')
        OR kind = 'named'
    );
ALTER TABLE public.problem_collection
    DROP CONSTRAINT problem_collection_visibility_check,
    ADD CONSTRAINT problem_collection_visibility_check
        CHECK (visibility IN ('private', 'institution'));
CREATE UNIQUE INDEX problem_collection_one_favorites_per_owner_idx
    ON public.problem_collection (owner_tenant_id, owner_user_id)
    WHERE kind = 'favorites';
CREATE UNIQUE INDEX problem_collection_named_owner_title_idx
    ON public.problem_collection (owner_tenant_id, owner_user_id, lower(btrim(title)))
    WHERE kind = 'named';
CREATE INDEX problem_collection_read_idx
    ON public.problem_collection (owner_tenant_id, visibility, collection_reference);
CREATE INDEX problem_version_author_ids_gin_idx
    ON public.problem_version USING gin (author_ids jsonb_path_ops);

ALTER TABLE public.problem_collection
    ADD CONSTRAINT problem_collection_owner_user_fkey
        FOREIGN KEY (owner_user_id) REFERENCES public.ple_account(user_id) ON DELETE RESTRICT;

CREATE FUNCTION public.ple_guard_problem_collection_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path TO 'pg_catalog', 'public' AS $$
BEGIN
    IF NEW.owner_tenant_id IS DISTINCT FROM OLD.owner_tenant_id
       OR NEW.owner_user_id IS DISTINCT FROM OLD.owner_user_id
       OR NEW.kind IS DISTINCT FROM OLD.kind
       OR NEW.collection_reference IS DISTINCT FROM OLD.collection_reference THEN
        RAISE EXCEPTION 'problem collection identity is immutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END
$$;
REVOKE ALL ON FUNCTION public.ple_guard_problem_collection_identity() FROM PUBLIC;
CREATE TRIGGER problem_collection_identity_immutable
    BEFORE UPDATE ON public.problem_collection
    FOR EACH ROW EXECUTE FUNCTION public.ple_guard_problem_collection_identity();

CREATE FUNCTION public.ple_saved_problem_search_filter_v1_is_valid(p_query jsonb)
RETURNS boolean
LANGUAGE sql IMMUTABLE PARALLEL SAFE
SET search_path TO 'pg_catalog', 'public'
RETURN coalesce(
    jsonb_typeof(p_query) = 'object'
    AND p_query ?& ARRAY['text','bylines','backends','tags','responseFamilies','taxonomy',
        'capabilities','licenses','evidence','usedInMyCourses','authorship']
    AND (SELECT count(*) FROM jsonb_object_keys(p_query)) = 11
    AND CASE
        WHEN p_query->'text' = 'null'::jsonb THEN true
        WHEN jsonb_typeof(p_query->'text') = 'string' THEN
            char_length(p_query->>'text') BETWEEN 1 AND 256
            AND p_query->>'text' = lower(regexp_replace(
                btrim(p_query->>'text'), '[[:space:]]+', ' ', 'g'
            ))
        ELSE false
    END
    AND CASE WHEN jsonb_typeof(p_query->'bylines') = 'array' THEN
        jsonb_array_length(p_query->'bylines') <= 16
        AND p_query->'bylines' = (
            SELECT coalesce(jsonb_agg(item.value ORDER BY item.value#>>'{}' COLLATE "C"), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements(p_query->'bylines')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'bylines') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'string'
                OR char_length(item.value#>>'{}') NOT BETWEEN 1 AND 120
                OR item.value#>>'{}' <> lower(regexp_replace(
                    btrim(item.value#>>'{}'), '[[:space:]]+', ' ', 'g'
                ))
        )
        ELSE false END
    AND CASE WHEN jsonb_typeof(p_query->'backends') = 'array' THEN
        jsonb_array_length(p_query->'backends') <= 5
        AND p_query->'backends' = (
            SELECT coalesce(jsonb_agg(to_jsonb(item.value) ORDER BY array_position(
                ARRAY['native','webwork','qti','h5p','imathas']::text[], item.value)), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements_text(p_query->'backends')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'backends') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'string'
                OR item.value#>>'{}' NOT IN ('native','webwork','qti','h5p','imathas')
        )
        ELSE false END
    AND CASE WHEN jsonb_typeof(p_query->'tags') = 'array' THEN
        jsonb_array_length(p_query->'tags') <= 64
        AND p_query->'tags' = (
            SELECT coalesce(jsonb_agg(item.value ORDER BY item.value#>>'{}' COLLATE "C"), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements(p_query->'tags')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'tags') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'string'
                OR char_length(item.value#>>'{}') NOT BETWEEN 1 AND 256
                OR item.value#>>'{}' <> lower(regexp_replace(
                    btrim(item.value#>>'{}'), '[[:space:]]+', ' ', 'g'
                ))
        )
        ELSE false END
    AND CASE WHEN jsonb_typeof(p_query->'responseFamilies') = 'array' THEN
        jsonb_array_length(p_query->'responseFamilies') <= 9
        AND p_query->'responseFamilies' = (
            SELECT coalesce(jsonb_agg(to_jsonb(item.value) ORDER BY array_position(ARRAY[
                'numeric','multipleChoice','shortText','multiBlank','matching','ordering',
                'hotspot','fileUpload','externalTool']::text[], item.value)), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements_text(p_query->'responseFamilies')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'responseFamilies') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'string'
                OR item.value#>>'{}' NOT IN ('numeric','multipleChoice','shortText','multiBlank',
                    'matching','ordering','hotspot','fileUpload','externalTool')
        )
        ELSE false END
    AND CASE WHEN jsonb_typeof(p_query->'taxonomy') = 'array' THEN
        jsonb_array_length(p_query->'taxonomy') <= 64
        AND p_query->'taxonomy' = (
            SELECT coalesce(jsonb_agg(item.value ORDER BY item.value->>'scheme' COLLATE "C",
                item.value->>'code' COLLATE "C"), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements(p_query->'taxonomy')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'taxonomy') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'object'
                OR NOT item.value ?& ARRAY['scheme','code']
                OR (SELECT count(*) FROM jsonb_object_keys(item.value)) <> 2
                OR jsonb_typeof(item.value->'scheme') <> 'string'
                OR jsonb_typeof(item.value->'code') <> 'string'
                OR char_length(item.value->>'scheme') NOT BETWEEN 1 AND 128
                OR char_length(item.value->>'code') NOT BETWEEN 1 AND 128
                OR item.value->>'scheme' <> btrim(item.value->>'scheme')
                OR item.value->>'code' <> btrim(item.value->>'code')
        )
        ELSE false END
    AND CASE WHEN jsonb_typeof(p_query->'capabilities') = 'array' THEN
        jsonb_array_length(p_query->'capabilities') <= 8
        AND p_query->'capabilities' = (
            SELECT coalesce(jsonb_agg(to_jsonb(item.value) ORDER BY array_position(ARRAY[
                'algorithmicGeneration','clientRendering','serverGrading','partialCredit','hints',
                'perQuestionTiming','printExport','offlinePreview']::text[], item.value)), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements_text(p_query->'capabilities')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'capabilities') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'string'
                OR item.value#>>'{}' NOT IN ('algorithmicGeneration','clientRendering',
                    'serverGrading','partialCredit','hints','perQuestionTiming','printExport',
                    'offlinePreview')
        )
        ELSE false END
    AND CASE WHEN jsonb_typeof(p_query->'licenses') = 'array' THEN
        jsonb_array_length(p_query->'licenses') <= 6
        AND p_query->'licenses' = (
            SELECT coalesce(jsonb_agg(to_jsonb(item.value) ORDER BY array_position(ARRAY[
                'allRightsReserved','ccBy','ccBySa','ccByNc','cc0','other']::text[], item.value)), '[]'::jsonb)
              FROM (SELECT DISTINCT value FROM jsonb_array_elements_text(p_query->'licenses')) AS item(value))
        AND NOT EXISTS (
            SELECT 1 FROM jsonb_array_elements(p_query->'licenses') AS item(value)
             WHERE jsonb_typeof(item.value) <> 'string'
                OR item.value#>>'{}' NOT IN (
                    'allRightsReserved','ccBy','ccBySa','ccByNc','cc0','other'
                )
        )
        ELSE false END
    AND jsonb_typeof(p_query->'evidence') = 'string'
    AND p_query->>'evidence' IN ('any','available','unavailable')
    AND jsonb_typeof(p_query->'usedInMyCourses') = 'string'
    AND p_query->>'usedInMyCourses' IN ('any','used')
    AND jsonb_typeof(p_query->'authorship') = 'string'
    AND p_query->>'authorship' IN ('any','authoredByCurrentActor'),
    false
);

CREATE TABLE public.saved_problem_search (
    search_id uuid NOT NULL DEFAULT gen_random_uuid(),
    search_reference integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.saved_problem_search_reference_seq),
    owner_tenant_id uuid NOT NULL,
    owner_user_id uuid NOT NULL,
    title text NOT NULL,
    normalized_query jsonb NOT NULL,
    query_schema_version smallint NOT NULL DEFAULT 1,
    normalized_query_sha256 bytea NOT NULL,
    revision bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT transaction_timestamp(),
    CONSTRAINT saved_problem_search_pkey PRIMARY KEY (owner_tenant_id, search_id),
    CONSTRAINT saved_problem_search_reference_positive CHECK (search_reference > 0),
    CONSTRAINT saved_problem_search_reference_key UNIQUE (search_reference),
    CONSTRAINT saved_problem_search_title_check CHECK (char_length(btrim(title)) BETWEEN 1 AND 200),
    CONSTRAINT saved_problem_search_query_object_check CHECK (jsonb_typeof(normalized_query) = 'object'),
    CONSTRAINT saved_problem_search_query_schema_check CHECK (query_schema_version = 1),
    CONSTRAINT saved_problem_search_query_semantics_check CHECK (
        public.ple_saved_problem_search_filter_v1_is_valid(normalized_query)
    ),
    CONSTRAINT saved_problem_search_query_digest_check CHECK (octet_length(normalized_query_sha256) = 32),
    CONSTRAINT saved_problem_search_no_continuation_check CHECK (
        NOT (normalized_query ? 'after')
        AND NOT (normalized_query ? 'cursor')
        AND NOT (normalized_query ? 'snapshot')
        AND NOT (normalized_query ? 'pageSize')
    ),
    CONSTRAINT saved_problem_search_revision_check CHECK (revision > 0),
    CONSTRAINT saved_problem_search_owner_title_key
        UNIQUE (owner_tenant_id, owner_user_id, title)
);
ALTER TABLE public.saved_problem_search
    ADD CONSTRAINT saved_problem_search_owner_user_fkey
        FOREIGN KEY (owner_user_id) REFERENCES public.ple_account(user_id) ON DELETE RESTRICT;
CREATE UNIQUE INDEX saved_problem_search_normalized_owner_title_idx
    ON public.saved_problem_search (owner_tenant_id, owner_user_id, lower(btrim(title)));
CREATE INDEX saved_problem_search_owner_reference_idx
    ON public.saved_problem_search (owner_tenant_id, owner_user_id, search_reference);
ALTER TABLE public.saved_problem_search ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.saved_problem_search FORCE ROW LEVEL SECURITY;

CREATE FUNCTION public.ple_guard_saved_problem_search_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path TO 'pg_catalog', 'public' AS $$
BEGIN
    IF NEW.owner_tenant_id IS DISTINCT FROM OLD.owner_tenant_id
       OR NEW.owner_user_id IS DISTINCT FROM OLD.owner_user_id
       OR NEW.search_id IS DISTINCT FROM OLD.search_id
       OR NEW.search_reference IS DISTINCT FROM OLD.search_reference THEN
        RAISE EXCEPTION 'saved problem search identity is immutable' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END
$$;
REVOKE ALL ON FUNCTION public.ple_guard_saved_problem_search_identity() FROM PUBLIC;
CREATE TRIGGER saved_problem_search_identity_immutable
    BEFORE UPDATE ON public.saved_problem_search
    FOR EACH ROW EXECUTE FUNCTION public.ple_guard_saved_problem_search_identity();

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ple_problem_curation_broker') THEN
        CREATE ROLE ple_problem_curation_broker
            NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
    END IF;
END
$$;
ALTER ROLE ple_problem_curation_broker
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
DO $$
DECLARE
    membership_edge record;
    default_acl record;
    target_column record;
BEGIN
    -- Converge every pre-D2 membership edge in both directions before the
    -- broker receives its canonical capability.
    FOR membership_edge IN
        SELECT parent_role.rolname AS parent_name, member_role.rolname AS member_name
          FROM pg_catalog.pg_auth_members AS membership
          JOIN pg_catalog.pg_roles AS parent_role ON parent_role.oid = membership.roleid
          JOIN pg_catalog.pg_roles AS member_role ON member_role.oid = membership.member
         WHERE membership.member = 'ple_problem_curation_broker'::regrole
            OR membership.roleid = 'ple_problem_curation_broker'::regrole
    LOOP
        EXECUTE format(
            'REVOKE %I FROM %I', membership_edge.parent_name, membership_edge.member_name
        );
    END LOOP;

    -- Default grants are ambient future authority. Remove every existing
    -- table, sequence, and function default that names this broker.
    FOR default_acl IN
        SELECT DISTINCT owner_role.rolname AS owner_name, namespace.nspname AS schema_name,
               defaults.defaclobjtype
          FROM pg_catalog.pg_default_acl AS defaults
          JOIN pg_catalog.pg_roles AS owner_role ON owner_role.oid = defaults.defaclrole
          LEFT JOIN pg_catalog.pg_namespace AS namespace
            ON namespace.oid = defaults.defaclnamespace
          CROSS JOIN LATERAL aclexplode(defaults.defaclacl) AS privilege
         WHERE privilege.grantee = 'ple_problem_curation_broker'::regrole
           AND defaults.defaclobjtype IN ('r','S','f')
    LOOP
        EXECUTE format(
            'ALTER DEFAULT PRIVILEGES FOR ROLE %I%s REVOKE ALL PRIVILEGES ON %s FROM ple_problem_curation_broker',
            default_acl.owner_name,
            CASE WHEN default_acl.schema_name IS NULL THEN ''
                 ELSE format(' IN SCHEMA %I', default_acl.schema_name) END,
            CASE default_acl.defaclobjtype
                WHEN 'r' THEN 'TABLES'
                WHEN 'S' THEN 'SEQUENCES'
                WHEN 'f' THEN 'FUNCTIONS'
            END
        );
    END LOOP;

    -- Table-level revocation does not erase column ACLs, so close those
    -- direct grants explicitly before applying the exact table matrix.
    FOR target_column IN
        SELECT namespace.nspname, relation_row.relname, attribute.attname
          FROM pg_catalog.pg_attribute AS attribute
          JOIN pg_catalog.pg_class AS relation_row ON relation_row.oid = attribute.attrelid
          JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation_row.relnamespace
         WHERE namespace.nspname = 'public'
           AND relation_row.relkind IN ('r','p','v','m','f')
           AND attribute.attnum > 0 AND NOT attribute.attisdropped
           AND EXISTS (
               SELECT 1 FROM aclexplode(attribute.attacl) AS privilege
                WHERE privilege.grantee = 'ple_problem_curation_broker'::regrole
           )
    LOOP
        EXECUTE format(
            'REVOKE ALL PRIVILEGES (%I) ON TABLE %I.%I FROM ple_problem_curation_broker',
            target_column.attname, target_column.nspname, target_column.relname
        );
    END LOOP;
END
$$;
REVOKE ALL ON SCHEMA public FROM ple_problem_curation_broker;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM ple_problem_curation_broker;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM ple_problem_curation_broker;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM ple_problem_curation_broker;
GRANT USAGE ON SCHEMA public TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_saved_problem_search_filter_v1_is_valid(jsonb)
    OWNER TO ple_problem_curation_broker;
REVOKE ALL ON FUNCTION public.ple_saved_problem_search_filter_v1_is_valid(jsonb) FROM PUBLIC;

-- The 0802 direct-app policies predate the aggregate capability.  The broker
-- is the sole data-plane principal from this point forward.
DROP POLICY problem_collection_tenant_write ON public.problem_collection;
DROP POLICY problem_collection_visible_select ON public.problem_collection;
DROP POLICY problem_collection_member_tenant_write ON public.problem_collection_member;
DROP POLICY problem_collection_member_visible_select ON public.problem_collection_member;
CREATE POLICY problem_collection_curation_broker ON public.problem_collection
    TO ple_problem_curation_broker
    USING (owner_tenant_id = public.ple_current_tenant())
    WITH CHECK (owner_tenant_id = public.ple_current_tenant());
CREATE POLICY problem_collection_member_curation_broker ON public.problem_collection_member
    TO ple_problem_curation_broker
    USING (owner_tenant_id = public.ple_current_tenant())
    WITH CHECK (owner_tenant_id = public.ple_current_tenant());
CREATE POLICY saved_problem_search_curation_broker ON public.saved_problem_search
    TO ple_problem_curation_broker
    USING (owner_tenant_id = public.ple_current_tenant())
    WITH CHECK (owner_tenant_id = public.ple_current_tenant());
CREATE POLICY problem_curation_broker_catalog_document ON public.catalog_search_document
    FOR SELECT TO ple_problem_curation_broker
    USING (
        publication_scope = 'public' OR EXISTS (
            SELECT 1 FROM public.catalog_tenant_grant AS grant_row
             WHERE grant_row.tenant_id = public.ple_current_tenant()
               AND grant_row.problem_id = catalog_search_document.problem_id
               AND grant_row.version_id = catalog_search_document.version_id
        ) OR EXISTS (
            SELECT 1 FROM public.problem_collection_member AS member_row
             WHERE member_row.owner_tenant_id = public.ple_current_tenant()
               AND member_row.problem_id = catalog_search_document.problem_id
               AND member_row.version_id = catalog_search_document.version_id
        )
    );
CREATE POLICY problem_curation_broker_catalog_grant ON public.catalog_tenant_grant
    FOR SELECT TO ple_problem_curation_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY problem_curation_broker_session ON public.auth_session
    FOR SELECT TO ple_problem_curation_broker
    USING (tenant_id = public.ple_current_tenant());

GRANT SELECT, INSERT, UPDATE, DELETE ON public.problem_collection,
    public.saved_problem_search TO ple_problem_curation_broker;
GRANT SELECT, INSERT, DELETE ON public.problem_collection_member TO ple_problem_curation_broker;
GRANT SELECT ON public.catalog_search_document TO ple_problem_curation_broker;
GRANT SELECT ON public.catalog_tenant_grant TO ple_problem_curation_broker;
GRANT SELECT ON public.auth_session TO ple_problem_curation_broker;
GRANT USAGE ON SEQUENCE public.problem_collection_reference_seq,
    public.saved_problem_search_reference_seq TO ple_problem_curation_broker;
GRANT EXECUTE ON FUNCTION public.ple_current_tenant(),
    public.ple_catalog_discovery_actor(character, uuid),
    public.ple_instructor_approval_eligible(uuid) TO ple_problem_curation_broker;

CREATE FUNCTION public.ple_problem_curation_actor(
    p_session character(64), p_tenant uuid
) RETURNS TABLE (user_id uuid)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT actor.user_id
      FROM public.ple_catalog_discovery_actor(p_session, p_tenant) AS actor
$$;
ALTER FUNCTION public.ple_problem_curation_actor(character, uuid)
    OWNER TO ple_problem_curation_broker;
REVOKE ALL ON FUNCTION public.ple_problem_curation_actor(character, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_problem_curation_actor(character, uuid)
    TO ple_problem_curation_broker;

-- Favorites and named collection mutation belongs to an approved Instructor.
-- Sysadmins retain the intended institution-read capability only.
CREATE FUNCTION public.ple_problem_curation_instructor_actor(
    p_session character(64), p_tenant uuid
) RETURNS TABLE (user_id uuid)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    SELECT actor.user_id INTO v_actor
      FROM public.ple_problem_curation_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN
        RETURN;
    END IF;
    IF NOT EXISTS (
        SELECT 1
          FROM public.auth_session AS session
         WHERE session.user_id = v_actor
           AND session.tenant_id = p_tenant
           AND session.session_hash = p_session
           AND session.revoked_at IS NULL
           AND session.expires_at > transaction_timestamp()
           AND session.roles @> '["instructor"]'::jsonb
    ) OR NOT public.ple_instructor_approval_eligible(v_actor) THEN
        RAISE EXCEPTION 'personal problem curation requires Instructor authority'
            USING ERRCODE = '42501';
    END IF;
    user_id := v_actor;
    RETURN NEXT;
END
$$;
ALTER FUNCTION public.ple_problem_curation_instructor_actor(character, uuid)
    OWNER TO ple_problem_curation_broker;
REVOKE ALL ON FUNCTION public.ple_problem_curation_instructor_actor(character, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_problem_curation_instructor_actor(character, uuid)
    TO ple_problem_curation_broker;

-- The application asks only for one closed capability decision. Actor and
-- role details remain inside the session-derived broker boundary.
CREATE FUNCTION public.ple_problem_curation_preflight_v1(
    p_tenant uuid, p_session character(64), p_capability text
) RETURNS boolean
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
BEGIN
    IF p_capability = 'catalogInstitutionRead' THEN
        RETURN EXISTS (
            SELECT 1 FROM public.ple_problem_curation_actor(p_session, p_tenant)
        );
    ELSIF p_capability = 'personalMutation' THEN
        RETURN EXISTS (
            SELECT 1 FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant)
        );
    END IF;
    RAISE EXCEPTION 'problem curation capability is invalid' USING ERRCODE = '22023';
END
$$;

CREATE FUNCTION public.ple_problem_collection_readable(
    p_tenant uuid, p_actor uuid, p_collection_reference integer
) RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT EXISTS (
        SELECT 1
          FROM public.problem_collection AS collection_row
         WHERE collection_row.owner_tenant_id = p_tenant
           AND collection_row.collection_reference = p_collection_reference
           AND (collection_row.owner_user_id = p_actor
                OR collection_row.visibility = 'institution')
    )
$$;
ALTER FUNCTION public.ple_problem_collection_readable(uuid, uuid, integer)
    OWNER TO ple_problem_curation_broker;
REVOKE ALL ON FUNCTION public.ple_problem_collection_readable(uuid, uuid, integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_problem_collection_readable(uuid, uuid, integer)
    TO ple_problem_curation_broker;

CREATE FUNCTION public.ple_ensure_problem_favorites_v1(
    p_tenant uuid, p_session character(64)
) RETURNS TABLE (
    collection_reference integer, kind text, title text, visibility text, revision bigint
)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'problem Favorites request is invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor
      FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    INSERT INTO public.problem_collection AS collection_row
        (collection_id, owner_tenant_id, owner_user_id, kind, title, visibility)
    VALUES (gen_random_uuid(), p_tenant, v_actor, 'favorites', 'Favorites', 'private')
    ON CONFLICT (owner_tenant_id, owner_user_id)
        WHERE collection_row.kind = 'favorites' DO NOTHING;
    RETURN QUERY
    SELECT c.collection_reference, c.kind, c.title, c.visibility, c.revision
      FROM public.problem_collection AS c
     WHERE c.owner_tenant_id = p_tenant AND c.owner_user_id = v_actor AND c.kind = 'favorites';
END
$$;

CREATE FUNCTION public.ple_list_problem_collections_v1(
    p_tenant uuid, p_session character(64), p_after_reference integer, p_limit integer
) RETURNS TABLE (
    collection_reference integer, kind text, title text, visibility text, revision bigint, access text
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_limit NOT BETWEEN 1 AND 101
       OR (p_after_reference IS NOT NULL AND p_after_reference < 1)
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'problem collection listing request is invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY
    SELECT c.collection_reference, c.kind, c.title, c.visibility, c.revision,
           CASE WHEN c.owner_user_id = v_actor THEN 'owner' ELSE 'institutionReader' END
     FROM public.problem_collection AS c
     WHERE c.owner_tenant_id = p_tenant
       AND (c.owner_user_id = v_actor OR c.visibility = 'institution')
       AND (p_after_reference IS NULL OR c.collection_reference > p_after_reference)
     ORDER BY c.collection_reference LIMIT p_limit;
END
$$;

CREATE FUNCTION public.ple_problem_collection_summary_v1(
    p_tenant uuid, p_session character(64), p_collection_reference integer
) RETURNS TABLE (
    collection_reference integer, kind text, title text, visibility text, revision bigint, access text
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_collection_reference IS NULL
       OR p_collection_reference < 1 OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'problem collection summary request is invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY SELECT c.collection_reference, c.kind, c.title, c.visibility, c.revision,
        CASE WHEN c.owner_user_id = v_actor THEN 'owner' ELSE 'institutionReader' END
      FROM public.problem_collection AS c
     WHERE c.owner_tenant_id = p_tenant AND c.collection_reference = p_collection_reference
       AND (c.owner_user_id = v_actor OR c.visibility = 'institution');
END
$$;

CREATE FUNCTION public.ple_problem_collection_members_v1(
    p_tenant uuid, p_session character(64), p_collection_reference integer,
    p_after_position integer, p_limit integer
) RETURNS TABLE (
    "position" integer, question_id character(7), selection_available boolean,
    backend text, response_family text, capabilities jsonb, metadata jsonb, public_byline text[],
    publication_scope text, lifecycle text, lifecycle_reason text, published_at_millis bigint
)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_collection_reference IS NULL
       OR p_collection_reference < 1 OR p_limit NOT BETWEEN 1 AND 101
       OR (p_after_position IS NOT NULL AND p_after_position < 0)
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'problem collection member request is invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND OR NOT public.ple_problem_collection_readable(p_tenant, v_actor, p_collection_reference) THEN
        RETURN;
    END IF;
    RETURN QUERY
    SELECT m.position, document.question_id, document.lifecycle = 'published', document.backend,
           document.response_family, document.capabilities, document.metadata, document.public_byline,
           document.publication_scope, document.lifecycle, document.lifecycle_reason,
           floor(extract(epoch FROM document.published_at) * 1000)::bigint
      FROM public.problem_collection AS c
      JOIN public.problem_collection_member AS m
        ON m.owner_tenant_id = c.owner_tenant_id AND m.collection_id = c.collection_id
      LEFT JOIN public.catalog_search_document AS document
        ON document.problem_id = m.problem_id AND document.version_id = m.version_id
     WHERE c.owner_tenant_id = p_tenant AND c.collection_reference = p_collection_reference
       AND (p_after_position IS NULL OR m.position > p_after_position)
     ORDER BY m.position LIMIT p_limit;
END
$$;

CREATE FUNCTION public.ple_replace_problem_collection_v1(
    p_tenant uuid, p_session character(64), p_collection_reference integer,
    p_expected_revision bigint, p_title text, p_visibility text, p_question_ids text[]
) RETURNS TABLE (
    collection_reference integer, kind text, title text, visibility text, revision bigint
)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_collection public.problem_collection%ROWTYPE; v_new_id uuid;
DECLARE v_count integer; v_resolved_count integer; v_changed boolean;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_expected_revision IS NULL
       OR p_expected_revision < 0 OR p_title IS NULL OR p_title <> btrim(p_title)
       OR char_length(p_title) NOT BETWEEN 1 AND 200
       OR p_visibility NOT IN ('private', 'institution') OR p_question_ids IS NULL
       OR coalesce(cardinality(p_question_ids), 0) > 200
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'problem collection replacement arguments are invalid' USING ERRCODE = '22023';
    END IF;
    SELECT count(*) INTO v_count FROM unnest(p_question_ids) AS id(question_id);
    IF v_count <> coalesce(cardinality(p_question_ids), 0)
       OR EXISTS (SELECT 1 FROM unnest(p_question_ids) AS id(question_id)
                   WHERE id.question_id IS NULL OR id.question_id !~ '^[A-Z0-9]{7}$')
       OR (SELECT count(DISTINCT id.question_id) FROM unnest(p_question_ids) AS id(question_id)) <> v_count THEN
        RAISE EXCEPTION 'problem collection question identifiers are invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor
      FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    IF p_collection_reference IS NULL THEN
        IF p_expected_revision <> 0 THEN
            RAISE EXCEPTION 'new problem collection revision conflicts' USING ERRCODE = '55000';
        END IF;
        PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text || v_actor::text, 0));
        IF (SELECT count(*) FROM public.problem_collection AS c
             WHERE c.owner_tenant_id = p_tenant AND c.owner_user_id = v_actor AND c.kind = 'named') >= 100 THEN
            RAISE EXCEPTION 'named problem collection limit exceeded' USING ERRCODE = '22023';
        END IF;
        v_new_id := gen_random_uuid();
        INSERT INTO public.problem_collection
            (collection_id, owner_tenant_id, owner_user_id, kind, title, visibility)
        VALUES (v_new_id, p_tenant, v_actor, 'named', p_title, p_visibility)
        RETURNING * INTO v_collection;
    ELSE
        SELECT * INTO v_collection FROM public.problem_collection AS c
         WHERE c.owner_tenant_id = p_tenant AND c.collection_reference = p_collection_reference
           AND c.owner_user_id = v_actor FOR UPDATE;
        IF NOT FOUND THEN RETURN; END IF;
        IF v_collection.revision <> p_expected_revision THEN
            RAISE EXCEPTION 'problem collection revision conflicts' USING ERRCODE = '55000';
        END IF;
        IF v_collection.kind = 'favorites'
           AND (p_title <> 'Favorites' OR p_visibility <> 'private') THEN
            RAISE EXCEPTION 'Favorites metadata is fixed' USING ERRCODE = '22023';
        END IF;
    END IF;
    SELECT count(*) INTO v_resolved_count
      FROM unnest(p_question_ids) WITH ORDINALITY AS requested(question_id, position)
      JOIN public.catalog_search_document AS document
        ON document.question_id = requested.question_id
       AND document.lifecycle = 'published'
       AND (document.publication_scope = 'public' OR EXISTS (
            SELECT 1 FROM public.catalog_tenant_grant AS grant_row
             WHERE grant_row.tenant_id = p_tenant AND grant_row.problem_id = document.problem_id
               AND grant_row.version_id = document.version_id
       ));
    IF v_resolved_count <> v_count THEN
        RAISE EXCEPTION 'problem collection contains unavailable Question IDs' USING ERRCODE = '22023';
    END IF;
    WITH proposed AS (
        SELECT requested.position - 1 AS position, document.problem_id, document.version_id
          FROM unnest(p_question_ids) WITH ORDINALITY AS requested(question_id, position)
          JOIN public.catalog_search_document AS document
            ON document.question_id = requested.question_id AND document.lifecycle = 'published'
           AND (document.publication_scope = 'public' OR EXISTS (
                SELECT 1 FROM public.catalog_tenant_grant AS grant_row
                 WHERE grant_row.tenant_id = p_tenant AND grant_row.problem_id = document.problem_id
                   AND grant_row.version_id = document.version_id
           ))
    ), existing AS (
        SELECT position, problem_id, version_id FROM public.problem_collection_member
         WHERE owner_tenant_id = p_tenant AND collection_id = v_collection.collection_id
    ) SELECT (v_collection.title IS DISTINCT FROM p_title OR v_collection.visibility IS DISTINCT FROM p_visibility
        OR EXISTS ((SELECT * FROM proposed) EXCEPT (SELECT * FROM existing))
        OR EXISTS ((SELECT * FROM existing) EXCEPT (SELECT * FROM proposed))) INTO v_changed;
    IF v_changed THEN
        DELETE FROM public.problem_collection_member
         WHERE owner_tenant_id = p_tenant AND collection_id = v_collection.collection_id;
        INSERT INTO public.problem_collection_member
            (owner_tenant_id, collection_id, problem_id, version_id, position)
        SELECT p_tenant, v_collection.collection_id, document.problem_id, document.version_id,
               requested.position - 1
          FROM unnest(p_question_ids) WITH ORDINALITY AS requested(question_id, position)
          JOIN public.catalog_search_document AS document
            ON document.question_id = requested.question_id AND document.lifecycle = 'published'
           AND (document.publication_scope = 'public' OR EXISTS (
                SELECT 1 FROM public.catalog_tenant_grant AS grant_row
                 WHERE grant_row.tenant_id = p_tenant AND grant_row.problem_id = document.problem_id
                   AND grant_row.version_id = document.version_id
           ));
        UPDATE public.problem_collection AS collection_row
           SET title = p_title, visibility = p_visibility,
               revision = collection_row.revision + 1,
               updated_at = transaction_timestamp()
         WHERE collection_row.owner_tenant_id = p_tenant
           AND collection_row.collection_id = v_collection.collection_id
         RETURNING collection_row.* INTO v_collection;
    END IF;
    collection_reference := v_collection.collection_reference;
    kind := v_collection.kind; title := v_collection.title; visibility := v_collection.visibility;
    revision := v_collection.revision; RETURN NEXT;
END
$$;

CREATE FUNCTION public.ple_replace_saved_problem_search_v1(
    p_tenant uuid, p_session character(64), p_search_reference integer,
    p_expected_revision bigint, p_title text, p_normalized_query jsonb
) RETURNS TABLE (search_reference integer, title text, normalized_query jsonb, query_schema_version smallint, normalized_query_sha256 bytea, canonical_query_sha256 bytea, revision bigint)
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_search public.saved_problem_search%ROWTYPE;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_expected_revision IS NULL OR p_expected_revision < 0
       OR p_title IS NULL OR p_title <> btrim(p_title) OR char_length(p_title) NOT BETWEEN 1 AND 200
       OR NOT public.ple_saved_problem_search_filter_v1_is_valid(p_normalized_query)
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'saved problem search replacement arguments are invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    IF p_search_reference IS NULL THEN
        IF p_expected_revision <> 0 THEN RAISE EXCEPTION 'new saved search revision conflicts' USING ERRCODE = '55000'; END IF;
        PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text || v_actor::text, 0));
        IF (SELECT count(*) FROM public.saved_problem_search AS search_row
             WHERE search_row.owner_tenant_id = p_tenant AND search_row.owner_user_id = v_actor) >= 100 THEN
            RAISE EXCEPTION 'saved problem search limit exceeded' USING ERRCODE = '22023';
        END IF;
        INSERT INTO public.saved_problem_search(owner_tenant_id, owner_user_id, title, normalized_query, normalized_query_sha256)
        VALUES (p_tenant, v_actor, p_title, p_normalized_query,
                digest(convert_to(p_normalized_query::text, 'UTF8'), 'sha256')) RETURNING * INTO v_search;
    ELSE
        SELECT * INTO v_search FROM public.saved_problem_search AS search_row
         WHERE search_row.owner_tenant_id = p_tenant AND search_row.search_reference = p_search_reference
           AND search_row.owner_user_id = v_actor FOR UPDATE;
        IF NOT FOUND THEN RETURN; END IF;
        IF v_search.revision <> p_expected_revision THEN
            RAISE EXCEPTION 'saved problem search revision conflicts' USING ERRCODE = '55000';
        END IF;
        IF v_search.title IS DISTINCT FROM p_title OR v_search.normalized_query IS DISTINCT FROM p_normalized_query THEN
            UPDATE public.saved_problem_search AS search_row
               SET title = p_title, normalized_query = p_normalized_query,
                   normalized_query_sha256 = digest(
                       convert_to(p_normalized_query::text, 'UTF8'), 'sha256'
                   ),
                   revision = search_row.revision + 1,
                   updated_at = transaction_timestamp()
             WHERE search_row.owner_tenant_id = p_tenant
               AND search_row.search_id = v_search.search_id
             RETURNING search_row.* INTO v_search;
        END IF;
    END IF;
    search_reference := v_search.search_reference; title := v_search.title;
    normalized_query := v_search.normalized_query; query_schema_version := v_search.query_schema_version;
    normalized_query_sha256 := v_search.normalized_query_sha256;
    canonical_query_sha256 := digest(convert_to(v_search.normalized_query::text, 'UTF8'), 'sha256');
    revision := v_search.revision; RETURN NEXT;
END
$$;

CREATE FUNCTION public.ple_list_saved_problem_searches_v1(
    p_tenant uuid, p_session character(64), p_after_reference integer, p_limit integer
) RETURNS TABLE (search_reference integer, title text, normalized_query jsonb, query_schema_version smallint, normalized_query_sha256 bytea, canonical_query_sha256 bytea, revision bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_limit NOT BETWEEN 1 AND 101
       OR (p_after_reference IS NOT NULL AND p_after_reference < 1)
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'saved problem search listing request is invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY SELECT search_row.search_reference, search_row.title, search_row.normalized_query,
        search_row.query_schema_version, search_row.normalized_query_sha256,
        digest(convert_to(search_row.normalized_query::text, 'UTF8'), 'sha256'), search_row.revision
     FROM public.saved_problem_search AS search_row
     WHERE search_row.owner_tenant_id = p_tenant AND search_row.owner_user_id = v_actor
       AND (p_after_reference IS NULL OR search_row.search_reference > p_after_reference)
     ORDER BY search_row.search_reference LIMIT p_limit;
END
$$;

CREATE FUNCTION public.ple_saved_problem_search_v1(
    p_tenant uuid, p_session character(64), p_search_reference integer
) RETURNS TABLE (search_reference integer, title text, normalized_query jsonb, query_schema_version smallint, normalized_query_sha256 bytea, canonical_query_sha256 bytea, revision bigint)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
DECLARE v_actor uuid;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_search_reference IS NULL OR p_search_reference < 1
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'saved problem search request is invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY SELECT search_row.search_reference, search_row.title, search_row.normalized_query,
        search_row.query_schema_version, search_row.normalized_query_sha256,
        digest(convert_to(search_row.normalized_query::text, 'UTF8'), 'sha256'), search_row.revision
      FROM public.saved_problem_search AS search_row WHERE search_row.owner_tenant_id = p_tenant
       AND search_row.owner_user_id = v_actor AND search_row.search_reference = p_search_reference;
END $$;

CREATE FUNCTION public.ple_delete_problem_collection_v1(
    p_tenant uuid, p_session character(64), p_collection_reference integer, p_expected_revision bigint
) RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_collection public.problem_collection%ROWTYPE;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_collection_reference IS NULL
       OR p_expected_revision IS NULL OR p_expected_revision < 1
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'problem collection deletion arguments are invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN false; END IF;
    SELECT * INTO v_collection FROM public.problem_collection AS c WHERE c.owner_tenant_id = p_tenant
      AND c.collection_reference = p_collection_reference AND c.owner_user_id = v_actor FOR UPDATE;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_collection.revision <> p_expected_revision THEN RAISE EXCEPTION 'problem collection revision conflicts' USING ERRCODE = '55000'; END IF;
    IF v_collection.kind <> 'named' THEN RAISE EXCEPTION 'Favorites cannot be deleted' USING ERRCODE = '22023'; END IF;
    DELETE FROM public.problem_collection WHERE owner_tenant_id = p_tenant AND collection_id = v_collection.collection_id;
    RETURN true;
END
$$;

CREATE FUNCTION public.ple_delete_saved_problem_search_v1(
    p_tenant uuid, p_session character(64), p_search_reference integer, p_expected_revision bigint
) RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public', pg_temp AS $$
DECLARE v_actor uuid; v_search public.saved_problem_search%ROWTYPE;
BEGIN
    IF p_tenant IS NULL OR p_session IS NULL OR p_search_reference IS NULL
       OR p_expected_revision IS NULL OR p_expected_revision < 1
       OR p_tenant IS DISTINCT FROM public.ple_current_tenant() THEN
        RAISE EXCEPTION 'saved problem search deletion arguments are invalid' USING ERRCODE = '22023';
    END IF;
    SELECT actor.user_id INTO v_actor FROM public.ple_problem_curation_instructor_actor(p_session, p_tenant) AS actor;
    IF NOT FOUND THEN RETURN false; END IF;
    SELECT * INTO v_search FROM public.saved_problem_search AS search_row WHERE search_row.owner_tenant_id = p_tenant
      AND search_row.search_reference = p_search_reference AND search_row.owner_user_id = v_actor FOR UPDATE;
    IF NOT FOUND THEN RETURN false; END IF;
    IF v_search.revision <> p_expected_revision THEN RAISE EXCEPTION 'saved problem search revision conflicts' USING ERRCODE = '55000'; END IF;
    DELETE FROM public.saved_problem_search WHERE owner_tenant_id = p_tenant AND search_id = v_search.search_id;
    RETURN true;
END
$$;

ALTER FUNCTION public.ple_ensure_problem_favorites_v1(uuid, character) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_list_problem_collections_v1(uuid, character, integer, integer) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_problem_collection_summary_v1(uuid, character, integer) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_problem_collection_members_v1(uuid, character, integer, integer, integer) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_replace_problem_collection_v1(uuid, character, integer, bigint, text, text, text[]) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_replace_saved_problem_search_v1(uuid, character, integer, bigint, text, jsonb) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_list_saved_problem_searches_v1(uuid, character, integer, integer) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_saved_problem_search_v1(uuid, character, integer) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_delete_problem_collection_v1(uuid, character, integer, bigint) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_delete_saved_problem_search_v1(uuid, character, integer, bigint) OWNER TO ple_problem_curation_broker;
ALTER FUNCTION public.ple_problem_curation_preflight_v1(uuid, character, text) OWNER TO ple_problem_curation_broker;
REVOKE ALL ON FUNCTION public.ple_problem_curation_preflight_v1(uuid, character, text),
    public.ple_ensure_problem_favorites_v1(uuid, character),
    public.ple_list_problem_collections_v1(uuid, character, integer, integer),
    public.ple_problem_collection_summary_v1(uuid, character, integer),
    public.ple_problem_collection_members_v1(uuid, character, integer, integer, integer),
    public.ple_replace_problem_collection_v1(uuid, character, integer, bigint, text, text, text[]),
    public.ple_replace_saved_problem_search_v1(uuid, character, integer, bigint, text, jsonb),
    public.ple_list_saved_problem_searches_v1(uuid, character, integer, integer),
    public.ple_saved_problem_search_v1(uuid, character, integer),
    public.ple_delete_problem_collection_v1(uuid, character, integer, bigint),
    public.ple_delete_saved_problem_search_v1(uuid, character, integer, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_problem_curation_preflight_v1(uuid, character, text),
    public.ple_ensure_problem_favorites_v1(uuid, character),
    public.ple_list_problem_collections_v1(uuid, character, integer, integer),
    public.ple_problem_collection_summary_v1(uuid, character, integer),
    public.ple_problem_collection_members_v1(uuid, character, integer, integer, integer),
    public.ple_replace_problem_collection_v1(uuid, character, integer, bigint, text, text, text[]),
    public.ple_replace_saved_problem_search_v1(uuid, character, integer, bigint, text, jsonb),
    public.ple_list_saved_problem_searches_v1(uuid, character, integer, integer),
    public.ple_saved_problem_search_v1(uuid, character, integer),
    public.ple_delete_problem_collection_v1(uuid, character, integer, bigint),
    public.ple_delete_saved_problem_search_v1(uuid, character, integer, bigint) TO ple_app;
REVOKE ALL ON public.problem_collection, public.problem_collection_member, public.saved_problem_search FROM ple_app;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_roles AS role_row
         WHERE role_row.rolname = 'ple_problem_curation_broker'
           AND (role_row.rolcanlogin OR role_row.rolsuper OR role_row.rolcreatedb
                OR role_row.rolcreaterole OR role_row.rolinherit OR role_row.rolreplication
                OR role_row.rolbypassrls)
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_auth_members AS membership
         WHERE membership.member = 'ple_problem_curation_broker'::regrole
            OR membership.roleid = 'ple_problem_curation_broker'::regrole
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_default_acl AS defaults
        CROSS JOIN LATERAL aclexplode(defaults.defaclacl) AS privilege
         WHERE privilege.grantee = 'ple_problem_curation_broker'::regrole
           AND defaults.defaclobjtype IN ('r','S','f')
    ) OR NOT has_schema_privilege('ple_problem_curation_broker','public','USAGE')
      OR has_schema_privilege('ple_problem_curation_broker','public','CREATE')
    OR EXISTS (
        WITH expected(object_kind,object_oid,sub_id,privilege_type) AS (
            VALUES
                ('table','public.problem_collection'::regclass::oid,0,'SELECT'),
                ('table','public.problem_collection'::regclass::oid,0,'INSERT'),
                ('table','public.problem_collection'::regclass::oid,0,'UPDATE'),
                ('table','public.problem_collection'::regclass::oid,0,'DELETE'),
                ('table','public.problem_collection_member'::regclass::oid,0,'SELECT'),
                ('table','public.problem_collection_member'::regclass::oid,0,'INSERT'),
                ('table','public.problem_collection_member'::regclass::oid,0,'DELETE'),
                ('table','public.saved_problem_search'::regclass::oid,0,'SELECT'),
                ('table','public.saved_problem_search'::regclass::oid,0,'INSERT'),
                ('table','public.saved_problem_search'::regclass::oid,0,'UPDATE'),
                ('table','public.saved_problem_search'::regclass::oid,0,'DELETE'),
                ('table','public.catalog_search_document'::regclass::oid,0,'SELECT'),
                ('table','public.catalog_tenant_grant'::regclass::oid,0,'SELECT'),
                ('table','public.auth_session'::regclass::oid,0,'SELECT'),
                ('sequence','public.problem_collection_reference_seq'::regclass::oid,0,'USAGE'),
                ('sequence','public.saved_problem_search_reference_seq'::regclass::oid,0,'USAGE'),
                ('function','public.ple_current_tenant()'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_catalog_discovery_actor(character,uuid)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_instructor_approval_eligible(uuid)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_saved_problem_search_filter_v1_is_valid(jsonb)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_problem_curation_actor(character,uuid)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_problem_curation_instructor_actor(character,uuid)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_problem_curation_preflight_v1(uuid,character,text)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_problem_collection_readable(uuid,uuid,integer)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_ensure_problem_favorites_v1(uuid,character)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_list_problem_collections_v1(uuid,character,integer,integer)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_problem_collection_summary_v1(uuid,character,integer)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_problem_collection_members_v1(uuid,character,integer,integer,integer)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_replace_problem_collection_v1(uuid,character,integer,bigint,text,text,text[])'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_replace_saved_problem_search_v1(uuid,character,integer,bigint,text,jsonb)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_list_saved_problem_searches_v1(uuid,character,integer,integer)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_saved_problem_search_v1(uuid,character,integer)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_delete_problem_collection_v1(uuid,character,integer,bigint)'::regprocedure::oid,0,'EXECUTE'),
                ('function','public.ple_delete_saved_problem_search_v1(uuid,character,integer,bigint)'::regprocedure::oid,0,'EXECUTE')
        ), actual AS (
            SELECT 'table',relation_row.oid,0,privilege.privilege_type
              FROM pg_catalog.pg_class AS relation_row
              JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid=relation_row.relnamespace
              CROSS JOIN LATERAL aclexplode(coalesce(
                  relation_row.relacl,acldefault('r',relation_row.relowner))) AS privilege
             WHERE namespace.nspname='public' AND relation_row.relkind IN ('r','p')
               AND privilege.grantee='ple_problem_curation_broker'::regrole
            UNION ALL
            SELECT 'column',attribute.attrelid,attribute.attnum,privilege.privilege_type
              FROM pg_catalog.pg_attribute AS attribute
              CROSS JOIN LATERAL aclexplode(attribute.attacl) AS privilege
             WHERE privilege.grantee='ple_problem_curation_broker'::regrole
            UNION ALL
            SELECT 'sequence',sequence_row.oid,0,privilege.privilege_type
              FROM pg_catalog.pg_class AS sequence_row
              JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid=sequence_row.relnamespace
              CROSS JOIN LATERAL aclexplode(coalesce(
                  sequence_row.relacl,acldefault('S',sequence_row.relowner))) AS privilege
             WHERE namespace.nspname='public' AND sequence_row.relkind='S'
               AND privilege.grantee='ple_problem_curation_broker'::regrole
            UNION ALL
            SELECT 'function',function_row.oid,0,privilege.privilege_type
              FROM pg_catalog.pg_proc AS function_row
              JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid=function_row.pronamespace
              CROSS JOIN LATERAL aclexplode(coalesce(
                  function_row.proacl,acldefault('f',function_row.proowner))) AS privilege
             WHERE namespace.nspname='public'
               AND privilege.grantee='ple_problem_curation_broker'::regrole
        )
        SELECT 1 FROM (
            (SELECT * FROM expected EXCEPT SELECT * FROM actual)
            UNION ALL (SELECT * FROM actual EXCEPT SELECT * FROM expected)
        ) AS privilege_drift
    ) OR EXISTS (
        SELECT 1 FROM unnest(ARRAY['problem_collection', 'problem_collection_member', 'saved_problem_search']) AS relation_name
         CROSS JOIN unnest(ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER']) AS privilege(privilege_name)
         WHERE has_table_privilege('ple_app', format('public.%I', relation_name), privilege_name)
    ) OR EXISTS (
        SELECT 1 FROM pg_class AS relation_row
          JOIN pg_namespace AS namespace ON namespace.oid = relation_row.relnamespace
         WHERE namespace.nspname = 'public'
           AND relation_row.relname IN ('problem_collection', 'problem_collection_member', 'saved_problem_search')
           AND (NOT relation_row.relrowsecurity OR NOT relation_row.relforcerowsecurity)
    ) THEN
        RAISE EXCEPTION 'problem curation authority catalog is unsafe';
    END IF;
END
$$;

COMMIT;
