-- WP-PROF-S7: one normalized public scalar per root aggregate and immutable,
-- browser-safe attribution. This is a pre-production direct cutover.

ALTER TABLE public.course_group
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.course_group_public_id_seq),
    ADD CONSTRAINT course_group_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT course_group_public_id_key UNIQUE (public_id);
GRANT USAGE, SELECT ON SEQUENCE public.course_group_public_id_seq TO ple_app;

ALTER TABLE public.problem_version RENAME COLUMN authors TO author_ids;
ALTER TABLE public.problem_version RENAME CONSTRAINT problem_version_authors_check TO problem_version_author_ids_check;
ALTER TABLE public.problem_version RENAME CONSTRAINT problem_version_authors_nonempty_check TO problem_version_author_ids_nonempty_check;
CREATE FUNCTION public.ple_valid_public_byline(p_names text[]) RETURNS boolean
    LANGUAGE sql IMMUTABLE PARALLEL SAFE
    RETURN cardinality(p_names) BETWEEN 1 AND 16
       AND NOT EXISTS (
           SELECT 1 FROM unnest(p_names) AS name
           WHERE name <> btrim(name) OR name = '' OR char_length(name) > 120 OR name ~ '[[:cntrl:]]'
       )
       AND cardinality(p_names) = (SELECT count(DISTINCT name) FROM unnest(p_names) AS name);
ALTER TABLE public.problem_version
    ADD COLUMN public_byline text[] NOT NULL,
    ADD CONSTRAINT problem_version_public_byline_check
        CHECK (public.ple_valid_public_byline(public_byline));

-- `catalog_search_view` is the public read projection over this column.  Tear
-- down the owned derived readers before changing the physical type, then
-- recreate them below against the final public-byline contract.  PostgreSQL
-- cannot rewrite a column while a view rule still depends on its old type.
DROP VIEW public.catalog_search_view;
DROP INDEX public.catalog_search_document_trigram_text_idx;
ALTER TABLE public.catalog_search_document DROP COLUMN normalized_search_text;
DROP FUNCTION public.ple_catalog_normalized_search_text(text, text, jsonb);

ALTER TABLE public.catalog_search_document RENAME COLUMN authors TO public_byline;
ALTER TABLE public.catalog_search_document RENAME COLUMN authors_text TO byline_text;
ALTER TABLE public.catalog_search_document RENAME CONSTRAINT catalog_search_document_authors_check TO catalog_search_document_public_byline_check;
ALTER TABLE public.catalog_search_document DROP CONSTRAINT catalog_search_document_public_byline_check;
ALTER TABLE public.catalog_search_document
    ALTER COLUMN public_byline TYPE text[] USING ARRAY[]::text[];
ALTER TABLE public.catalog_search_document
    ADD CONSTRAINT catalog_search_document_public_byline_check
        CHECK (public.ple_valid_public_byline(public_byline));

CREATE FUNCTION public.ple_catalog_normalized_search_text(
    p_title text, p_byline text, p_metadata jsonb
) RETURNS text LANGUAGE sql IMMUTABLE PARALLEL SAFE
    RETURN lower(coalesce(p_title, '') || ' ' || coalesce(p_byline, '') || ' ' || coalesce(p_metadata::text, ''));
ALTER TABLE public.catalog_search_document
    ADD COLUMN normalized_search_text text GENERATED ALWAYS AS (
        public.ple_catalog_normalized_search_text(title, byline_text, metadata)
    ) STORED;
CREATE INDEX catalog_search_document_trigram_text_idx ON public.catalog_search_document
    USING gin (normalized_search_text gin_trgm_ops);

CREATE OR REPLACE FUNCTION public.ple_project_catalog_search_document() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
DECLARE stable_question_id character(7);
DECLARE rendered_byline text;
BEGIN
    SELECT question_id INTO stable_question_id FROM public.problem WHERE problem_id = NEW.problem_id;
    SELECT string_agg(value, ', ' ORDER BY ordinality) INTO rendered_byline
      FROM unnest(NEW.public_byline) WITH ORDINALITY AS name(value, ordinality);
    INSERT INTO public.catalog_search_document (
        problem_id, version_id, question_id, title, backend, metadata, publication_scope,
        lifecycle, lifecycle_reason, public_byline, derived_from_problem_id,
        derived_from_version_id, published_at, byline_text, question_type, language, license,
        taxonomy, keywords, capabilities, search_text
    ) VALUES (
        NEW.problem_id, NEW.version_id, stable_question_id, NEW.title, NEW.backend, NEW.metadata,
        NEW.publication_scope, NEW.lifecycle, NEW.lifecycle_reason, NEW.public_byline,
        NEW.derived_from_problem_id, NEW.derived_from_version_id, NEW.created_at, rendered_byline,
        NEW.backend, COALESCE(NEW.metadata->>'language', 'und'),
        COALESCE(NEW.metadata #>> '{license,kind}', 'unknown'),
        COALESCE(NEW.metadata->'taxonomy', '[]'::jsonb), COALESCE(NEW.metadata->'tags', '[]'::jsonb),
        NEW.capabilities, to_tsvector('simple', concat_ws(' ', NEW.title, rendered_byline, NEW.metadata::text))
    ) ON CONFLICT (problem_id, version_id) DO UPDATE SET lifecycle = EXCLUDED.lifecycle,
        lifecycle_reason = EXCLUDED.lifecycle_reason, updated_at = transaction_timestamp();
    RETURN NEW;
END $$;

CREATE VIEW public.catalog_search_view WITH (security_invoker = true) AS
SELECT document.problem_id, document.version_id, document.question_id, document.title, document.backend,
       document.metadata, document.publication_scope, document.lifecycle, document.lifecycle_reason,
       document.public_byline, document.derived_from_problem_id, document.derived_from_version_id,
       document.published_at, document.byline_text, document.question_type, document.language,
       document.license, document.taxonomy, document.keywords, document.capabilities,
       document.search_text, document.quality_signal, document.updated_at, statistics.cohort_size,
       statistics.difficulty_index, statistics.attempts_mean, statistics.time_median_seconds_estimate,
       statistics.discrimination_index, (statistics.cohort_size IS NOT NULL) AS statistics_available,
       document.catalog_sequence, disclosure.disclosed_sequence AS statistics_disclosed_sequence,
       document.normalized_search_text
  FROM public.catalog_search_document AS document
  LEFT JOIN LATERAL public.ple_question_statistics_view(document.problem_id, document.version_id) AS statistics ON true
  LEFT JOIN public.catalog_statistics_disclosure AS disclosure
    ON disclosure.problem_id = document.problem_id AND disclosure.version_id = document.version_id;
GRANT SELECT ON TABLE public.catalog_search_view TO ple_app, ple_student;
