-- Stable human-facing route references. Internal UUIDs remain the relational and authorization keys.

ALTER TABLE public.course
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.course_public_id_seq),
    ADD CONSTRAINT course_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT course_public_id_key UNIQUE (public_id);

ALTER TABLE public.assignment
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.assignment_public_id_seq),
    ADD CONSTRAINT assignment_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT assignment_public_id_key UNIQUE (public_id);

ALTER TABLE public.assignment_run
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.assignment_run_public_id_seq),
    ADD CONSTRAINT assignment_run_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT assignment_run_public_id_key UNIQUE (public_id);

ALTER TABLE public.workspace_draft
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.workspace_public_id_seq),
    ADD CONSTRAINT workspace_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT workspace_public_id_key UNIQUE (public_id);

GRANT USAGE, SELECT ON SEQUENCE public.course_public_id_seq TO ple_app;
GRANT USAGE, SELECT ON SEQUENCE public.assignment_public_id_seq TO ple_app;
GRANT USAGE, SELECT ON SEQUENCE public.assignment_run_public_id_seq TO ple_app;
GRANT USAGE, SELECT ON SEQUENCE public.workspace_public_id_seq TO ple_app;
