-- WP-PROF-T2: course-group operations and deliberately separate teaching authority.
-- This is a forward-only pre-production migration.  It refuses malformed
-- existing modifiers rather than changing their meaning.

BEGIN;

CREATE TABLE public.course_group_membership_policy (
    tenant_id uuid NOT NULL,
    course_id uuid NOT NULL,
    purpose text NOT NULL,
    multiple_membership text NOT NULL,
    revision bigint NOT NULL,
    CONSTRAINT course_group_membership_policy_pkey
        PRIMARY KEY (tenant_id, course_id, purpose),
    CONSTRAINT course_group_membership_policy_course_fk
        FOREIGN KEY (tenant_id, course_id)
        REFERENCES public.course(tenant_id, course_id) ON DELETE CASCADE,
    CONSTRAINT course_group_membership_policy_purpose_check
        CHECK (purpose IN ('section', 'lab', 'cohort', 'accommodation', 'work')),
    CONSTRAINT course_group_membership_policy_multiple_check
        CHECK (multiple_membership IN ('allow', 'warn')),
    CONSTRAINT course_group_membership_policy_revision_check CHECK (revision > 0)
);

INSERT INTO public.course_group_membership_policy
    (tenant_id, course_id, purpose, multiple_membership, revision)
SELECT course.tenant_id, course.course_id, defaults.purpose,
       defaults.multiple_membership, 1
  FROM public.course AS course
 CROSS JOIN (VALUES
    ('section'::text, 'warn'::text),
    ('lab'::text, 'allow'::text),
    ('cohort'::text, 'allow'::text),
    ('accommodation'::text, 'allow'::text),
    ('work'::text, 'allow'::text)
 ) AS defaults(purpose, multiple_membership);

CREATE FUNCTION public.ple_create_course_group_membership_policies() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public'
AS $$
BEGIN
    INSERT INTO public.course_group_membership_policy
        (tenant_id, course_id, purpose, multiple_membership, revision)
    VALUES
        (NEW.tenant_id, NEW.course_id, 'section', 'warn', 1),
        (NEW.tenant_id, NEW.course_id, 'lab', 'allow', 1),
        (NEW.tenant_id, NEW.course_id, 'cohort', 'allow', 1),
        (NEW.tenant_id, NEW.course_id, 'accommodation', 'allow', 1),
        (NEW.tenant_id, NEW.course_id, 'work', 'allow', 1);
    RETURN NEW;
END
$$;

CREATE CONSTRAINT TRIGGER course_creates_group_membership_policies
    AFTER INSERT ON public.course
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION public.ple_create_course_group_membership_policies();

ALTER TABLE public.course_group_membership_policy ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_group_membership_policy FORCE ROW LEVEL SECURITY;
CREATE POLICY course_group_membership_policy_app
    ON public.course_group_membership_policy TO ple_app
    USING (tenant_id = public.ple_current_tenant()
           AND public.ple_course_records_accessible(tenant_id, course_id))
    WITH CHECK (tenant_id = public.ple_current_tenant()
                AND public.ple_course_records_accessible(tenant_id, course_id));
GRANT SELECT, INSERT, UPDATE ON public.course_group_membership_policy TO ple_app;

-- The migration owner creates this account-only operator.  It has no broad
-- Typed public locators are stable, positive 31-bit database identities. They
-- locate records only; every resolution remains inside an authorized Store
-- capability and no account email is projected through these columns.
ALTER TABLE public.ple_account
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.ple_account_public_id_seq),
    ADD CONSTRAINT ple_account_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT ple_account_public_id_key UNIQUE (public_id);
ALTER TABLE public.course_member
    ADD COLUMN public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.course_member_public_id_seq),
    ADD CONSTRAINT course_member_public_id_positive CHECK (public_id > 0),
    ADD CONSTRAINT course_member_public_id_key UNIQUE (public_id);
-- `ple_auth` inserts accounts through passwordless identity.  The application
-- role never inserts accounts, so it receives no account identity sequence
-- capability; `ple_app` alone inserts memberships and invitations below.
GRANT USAGE, SELECT ON SEQUENCE public.ple_account_public_id_seq TO ple_auth;
GRANT USAGE, SELECT ON SEQUENCE public.course_member_public_id_seq TO ple_app;

-- The migration owner creates this account-only operator.  It has no broad
-- role membership, does not bypass RLS, and owns only the definer functions.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ple_teaching_authority_broker') THEN
        CREATE ROLE ple_teaching_authority_broker
            NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
    END IF;
END
$$;
ALTER ROLE ple_teaching_authority_broker
    NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
REVOKE ALL ON SCHEMA public FROM ple_teaching_authority_broker;
GRANT USAGE ON SCHEMA public TO ple_teaching_authority_broker;

-- Approval is global operator eligibility.  It intentionally has neither a
-- tenant key nor RLS policy, and it does not confer a platform or course role.
CREATE TABLE public.instructor_approval (
    user_id uuid PRIMARY KEY REFERENCES public.ple_account(user_id),
    approved_by uuid NOT NULL REFERENCES public.ple_account(user_id),
    approved_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    revision bigint NOT NULL,
    CONSTRAINT instructor_approval_revision_check CHECK (revision > 0),
    CONSTRAINT instructor_approval_chronology_check
        CHECK (revoked_at IS NULL OR revoked_at >= approved_at)
);

CREATE FUNCTION public.ple_instructor_approval_eligible(p_target uuid) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
    SELECT p_target IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.instructor_approval
         WHERE user_id = p_target AND revoked_at IS NULL
    )
$$;

-- Pending invitations are target-bound, so the application may resolve only
-- the subject of the presented active session.  Direct `auth_session` access
-- remains unavailable to `ple_app`; this broker returns no session metadata.
CREATE FUNCTION public.ple_target_session_subject(
    p_session character(64), p_tenant uuid
) RETURNS TABLE (user_id uuid)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
    SELECT session.user_id
      FROM public.auth_session AS session
     WHERE session.session_hash = p_session
       AND session.tenant_id = p_tenant
       AND session.tenant_id = public.ple_current_tenant()
       AND session.revoked_at IS NULL
       AND session.expires_at > transaction_timestamp()
$$;

-- The application has no direct access to global account rows.  Invitation
-- creation still distinguishes a nonexistent target from an existing but
-- unapproved target through this account-ID-only broker predicate.
CREATE FUNCTION public.ple_instructor_approval_target_exists(p_target uuid) RETURNS boolean
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
    SELECT p_target IS NOT NULL AND EXISTS (
        SELECT 1 FROM public.ple_account WHERE user_id = p_target
    )
$$;

-- These are the only account-reference projections available to `ple_app`.
-- They intentionally return neither normalized nor delivery email.  The
-- session-bound variants check the persisted, active same-tenant session in
-- the broker, rather than trusting caller-supplied identity or role inputs.
CREATE FUNCTION public.ple_own_account_reference(
    p_session character(64), p_tenant uuid
) RETURNS TABLE (public_id integer, display_name text)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
    SELECT account.public_id, account.display_name
      FROM public.auth_session AS session
      JOIN public.ple_account AS account ON account.user_id = session.user_id
     WHERE session.session_hash = p_session
       AND session.tenant_id = p_tenant
       AND session.tenant_id = public.ple_current_tenant()
       AND session.revoked_at IS NULL
       AND session.expires_at > transaction_timestamp()
$$;

CREATE FUNCTION public.ple_sysadmin_account_reference(
    p_session character(64), p_public_id integer
) RETURNS TABLE (user_id uuid)
    LANGUAGE plpgsql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
DECLARE actor uuid;
DECLARE roles jsonb;
BEGIN
    SELECT session.user_id, session.roles INTO actor, roles
      FROM public.auth_session AS session
     WHERE session.session_hash = p_session
       AND session.tenant_id = public.ple_current_tenant()
       AND session.revoked_at IS NULL
       AND session.expires_at > transaction_timestamp();
    IF actor IS NULL THEN
        RETURN;
    END IF;
    IF NOT roles @> '["sysadmin"]'::jsonb THEN
        RAISE EXCEPTION 'sysadmin account reference is not authorized' USING ERRCODE = '42501';
    END IF;
    RETURN QUERY SELECT account.user_id
      FROM public.ple_account AS account WHERE account.public_id = p_public_id;
END
$$;

CREATE FUNCTION public.ple_approved_account_reference(
    p_public_id integer
) RETURNS TABLE (user_id uuid)
    LANGUAGE sql STABLE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
    SELECT account.user_id
      FROM public.ple_account AS account
      JOIN public.instructor_approval AS approval ON approval.user_id = account.user_id
     WHERE account.public_id = p_public_id AND approval.revoked_at IS NULL
$$;

-- Acceptance must hold this exact approval row through its membership and
-- invitation writes.  Sysadmin approval and revocation use the same row lock,
-- so either transition serializes before acceptance can commit.
CREATE FUNCTION public.ple_lock_instructor_approval_eligibility(p_target uuid) RETURNS boolean
    LANGUAGE plpgsql VOLATILE SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
DECLARE stored public.instructor_approval%ROWTYPE;
BEGIN
    IF p_target IS NULL THEN
        RETURN false;
    END IF;
    SELECT * INTO stored FROM public.instructor_approval
     WHERE user_id = p_target FOR UPDATE;
    RETURN FOUND AND stored.revoked_at IS NULL;
END
$$;

CREATE FUNCTION public.ple_sysadmin_instructor_approval(
    p_session character,
    p_target uuid,
    p_expected_revision bigint DEFAULT NULL
) RETURNS TABLE (
    user_id uuid, approved_by uuid, approved_at timestamp with time zone,
    revoked_at timestamp with time zone, revision bigint
)
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
DECLARE actor uuid;
DECLARE roles jsonb;
DECLARE stored public.instructor_approval%ROWTYPE;
BEGIN
    PERFORM set_config('ple.session_hash', p_session, true);
    SELECT session.user_id, session.roles INTO actor, roles
      FROM public.auth_session AS session
     WHERE session.session_hash = p_session
       AND session.tenant_id = public.ple_current_tenant()
       AND session.revoked_at IS NULL
       AND session.expires_at > transaction_timestamp();
    IF actor IS NULL OR NOT roles @> '["sysadmin"]'::jsonb OR p_target IS NULL THEN
        RAISE EXCEPTION 'sysadmin instructor approval is not authorized' USING ERRCODE = '42501';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM public.ple_account AS account
         WHERE account.user_id = p_target
    ) THEN
        RETURN;
    END IF;
    SELECT * INTO stored FROM public.instructor_approval AS approval
     WHERE approval.user_id = p_target FOR UPDATE;
    IF FOUND AND p_expected_revision IS DISTINCT FROM stored.revision THEN
        RAISE EXCEPTION 'stale instructor approval revision' USING ERRCODE = '55000';
    END IF;
    IF NOT FOUND AND p_expected_revision IS NOT NULL THEN
        RAISE EXCEPTION 'stale instructor approval revision' USING ERRCODE = '55000';
    END IF;
    IF NOT FOUND THEN
        INSERT INTO public.instructor_approval
            (user_id, approved_by, approved_at, revoked_at, revision)
        VALUES (p_target, actor, transaction_timestamp(), NULL, 1)
        RETURNING * INTO stored;
    ELSE
        UPDATE public.instructor_approval AS approval
           SET approved_by = actor, approved_at = transaction_timestamp(), revoked_at = NULL,
               revision = approval.revision + 1
         WHERE approval.user_id = p_target RETURNING * INTO stored;
    END IF;
    RETURN QUERY SELECT stored.user_id, stored.approved_by, stored.approved_at,
                        stored.revoked_at, stored.revision;
END
$$;

CREATE FUNCTION public.ple_sysadmin_revoke_instructor_approval(
    p_session character, p_target uuid, p_expected_revision bigint
) RETURNS TABLE (
    user_id uuid, approved_by uuid, approved_at timestamp with time zone,
    revoked_at timestamp with time zone, revision bigint
)
    LANGUAGE plpgsql SECURITY DEFINER
    SET search_path TO 'pg_catalog', 'public'
AS $$
DECLARE actor uuid;
DECLARE roles jsonb;
DECLARE stored public.instructor_approval%ROWTYPE;
BEGIN
    PERFORM set_config('ple.session_hash', p_session, true);
    SELECT session.user_id, session.roles INTO actor, roles
      FROM public.auth_session AS session
     WHERE session.session_hash = p_session
       AND session.tenant_id = public.ple_current_tenant()
       AND session.revoked_at IS NULL
       AND session.expires_at > transaction_timestamp();
    IF actor IS NULL OR NOT roles @> '["sysadmin"]'::jsonb OR p_target IS NULL THEN
        RAISE EXCEPTION 'sysadmin instructor approval is not authorized' USING ERRCODE = '42501';
    END IF;
    SELECT * INTO stored FROM public.instructor_approval AS approval
     WHERE approval.user_id = p_target FOR UPDATE;
    IF NOT FOUND THEN
        RETURN;
    END IF;
    IF stored.revoked_at IS NOT NULL
       OR p_expected_revision IS DISTINCT FROM stored.revision THEN
        RAISE EXCEPTION 'stale instructor approval revision' USING ERRCODE = '55000';
    END IF;
    UPDATE public.instructor_approval AS approval
       SET revoked_at = transaction_timestamp(), revision = approval.revision + 1
     WHERE approval.user_id = p_target RETURNING * INTO stored;
    RETURN QUERY SELECT stored.user_id, stored.approved_by, stored.approved_at,
                        stored.revoked_at, stored.revision;
END
$$;

ALTER FUNCTION public.ple_instructor_approval_eligible(uuid)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_target_session_subject(character, uuid)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_own_account_reference(character, uuid)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_sysadmin_account_reference(character, integer)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_approved_account_reference(integer)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_instructor_approval_target_exists(uuid)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_lock_instructor_approval_eligibility(uuid)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_sysadmin_instructor_approval(character, uuid, bigint)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_sysadmin_revoke_instructor_approval(character, uuid, bigint)
    OWNER TO ple_teaching_authority_broker;
-- Approval is global, but the broker needs only account existence.  Its
-- account policy and column grant deliberately exclude account PII.
CREATE POLICY ple_account_teaching_authority_broker
    ON public.ple_account FOR SELECT TO ple_teaching_authority_broker
    USING (true);
GRANT SELECT (user_id, public_id, display_name) ON public.ple_account
    TO ple_teaching_authority_broker;
GRANT SELECT ON public.auth_session TO ple_teaching_authority_broker;
GRANT SELECT, INSERT, UPDATE ON public.instructor_approval TO ple_teaching_authority_broker;
GRANT EXECUTE ON FUNCTION public.ple_current_tenant() TO ple_teaching_authority_broker;
REVOKE ALL ON FUNCTION public.ple_instructor_approval_eligible(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_target_session_subject(character, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_own_account_reference(character, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_sysadmin_account_reference(character, integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_approved_account_reference(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_instructor_approval_target_exists(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_lock_instructor_approval_eligibility(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_sysadmin_instructor_approval(character, uuid, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_sysadmin_revoke_instructor_approval(character, uuid, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_instructor_approval_eligible(uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_target_session_subject(character, uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_own_account_reference(character, uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_sysadmin_account_reference(character, integer) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_approved_account_reference(integer) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_instructor_approval_target_exists(uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_lock_instructor_approval_eligibility(uuid) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_sysadmin_instructor_approval(character, uuid, bigint) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_sysadmin_revoke_instructor_approval(character, uuid, bigint) TO ple_app;

-- Authorized public-reference list projections. These deliberately provide
-- presentation facts only; internal UUIDs and emails stay inside the broker.
CREATE POLICY course_teaching_authority_broker
    ON public.course FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY course_member_teaching_authority_broker
    ON public.course_member FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY course_group_teaching_authority_broker
    ON public.course_group FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY course_group_member_teaching_authority_broker
    ON public.course_group_member FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY course_roster_profile_teaching_authority_broker
    ON public.course_roster_profile FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
CREATE POLICY course_roster_state_teaching_authority_broker
    ON public.course_roster_state FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
GRANT SELECT ON public.course, public.course_member, public.course_group, public.course_group_member,
    public.course_roster_profile, public.course_roster_state
    TO ple_teaching_authority_broker;


CREATE TABLE public.course_instructor_invitation (
    tenant_id uuid NOT NULL,
    course_id uuid NOT NULL,
    invitation_id uuid NOT NULL DEFAULT gen_random_uuid(),
    public_id integer GENERATED BY DEFAULT AS IDENTITY
        (SEQUENCE NAME public.course_instructor_invitation_public_id_seq),
    target_user_id uuid NOT NULL REFERENCES public.ple_account(user_id),
    invited_by_membership_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT transaction_timestamp(),
    expires_at timestamp with time zone NOT NULL DEFAULT (transaction_timestamp() + interval '30 days'),
    status text NOT NULL DEFAULT 'pending',
    accepted_at timestamp with time zone,
    declined_at timestamp with time zone,
    revoked_at timestamp with time zone,
    accepted_membership_id uuid,
    revision bigint NOT NULL DEFAULT 1,
    CONSTRAINT course_instructor_invitation_pkey PRIMARY KEY (tenant_id, invitation_id),
    CONSTRAINT course_instructor_invitation_public_id_positive CHECK (public_id > 0),
    CONSTRAINT course_instructor_invitation_public_id_key UNIQUE (public_id),
    CONSTRAINT course_instructor_invitation_course_fk
        FOREIGN KEY (tenant_id, course_id)
        REFERENCES public.course(tenant_id, course_id) ON DELETE CASCADE,
    CONSTRAINT course_instructor_invitation_inviter_fk
        FOREIGN KEY (tenant_id, course_id, invited_by_membership_id)
        REFERENCES public.course_member(tenant_id, course_id, course_membership_id) ON DELETE RESTRICT,
    CONSTRAINT course_instructor_invitation_accepted_membership_fk
        FOREIGN KEY (tenant_id, course_id, accepted_membership_id)
        REFERENCES public.course_member(tenant_id, course_id, course_membership_id) ON DELETE RESTRICT,
    CONSTRAINT course_instructor_invitation_status_check
        CHECK (status IN ('pending', 'accepted', 'declined', 'revoked', 'expired')),
    CONSTRAINT course_instructor_invitation_expiry_check
        CHECK (expires_at = created_at + interval '30 days'),
    CONSTRAINT course_instructor_invitation_revision_check CHECK (revision > 0),
    CONSTRAINT course_instructor_invitation_lifecycle_check CHECK (
        (status = 'pending' AND accepted_at IS NULL AND declined_at IS NULL
         AND revoked_at IS NULL AND accepted_membership_id IS NULL)
        OR (status = 'accepted' AND accepted_at IS NOT NULL AND declined_at IS NULL
            AND revoked_at IS NULL AND accepted_membership_id IS NOT NULL)
        OR (status = 'declined' AND accepted_at IS NULL AND declined_at IS NOT NULL
            AND revoked_at IS NULL AND accepted_membership_id IS NULL)
        OR (status = 'revoked' AND accepted_at IS NULL AND declined_at IS NULL
            AND revoked_at IS NOT NULL AND accepted_membership_id IS NULL)
        OR (status = 'expired' AND accepted_at IS NULL AND declined_at IS NULL
            AND revoked_at IS NULL AND accepted_membership_id IS NULL)
    )
);
GRANT USAGE, SELECT ON SEQUENCE public.course_instructor_invitation_public_id_seq TO ple_app;

-- A new invite first expires a prior pending row for the same target/course.
-- The partial unique index then makes concurrent reinvites serialize without
-- permanently blocking a re-invite after the 30 day term.
CREATE UNIQUE INDEX course_instructor_invitation_one_pending_target_key
    ON public.course_instructor_invitation (tenant_id, course_id, target_user_id)
    WHERE status = 'pending';
CREATE INDEX course_instructor_invitation_target_pending_idx
    ON public.course_instructor_invitation (target_user_id, status, expires_at, invitation_id);

CREATE FUNCTION public.ple_expire_pending_course_instructor_invitation() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public'
AS $$
BEGIN
    UPDATE public.course_instructor_invitation
       SET status = 'expired', revision = revision + 1
     WHERE tenant_id = NEW.tenant_id AND course_id = NEW.course_id
       AND target_user_id = NEW.target_user_id AND status = 'pending'
       AND expires_at <= transaction_timestamp();
    RETURN NEW;
END
$$;

CREATE FUNCTION public.ple_guard_course_instructor_invitation() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public'
AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'pending' OR NEW.revision <> 1
           OR NEW.created_at <> transaction_timestamp()
           OR NEW.expires_at <> NEW.created_at + interval '30 days'
           OR NOT public.ple_instructor_approval_eligible(NEW.target_user_id)
           OR NOT EXISTS (
                SELECT 1 FROM public.course_member
                 WHERE tenant_id = NEW.tenant_id AND course_id = NEW.course_id
                   AND course_membership_id = NEW.invited_by_membership_id
                   AND role = 'instructor' AND status = 'active'
           ) THEN
            RAISE EXCEPTION 'invalid co-instructor invitation' USING ERRCODE = '23514';
        END IF;
        RETURN NEW;
    END IF;
    IF (NEW.tenant_id, NEW.course_id, NEW.invitation_id, NEW.target_user_id,
        NEW.invited_by_membership_id, NEW.created_at, NEW.expires_at)
       IS DISTINCT FROM
       (OLD.tenant_id, OLD.course_id, OLD.invitation_id, OLD.target_user_id,
        OLD.invited_by_membership_id, OLD.created_at, OLD.expires_at)
       OR NEW.revision <> OLD.revision + 1 THEN
        RAISE EXCEPTION 'co-instructor invitation identity is immutable' USING ERRCODE = '55000';
    END IF;
    IF OLD.status <> 'pending' THEN
        RAISE EXCEPTION 'terminal co-instructor invitation is immutable' USING ERRCODE = '55000';
    END IF;
    IF NEW.status = 'accepted' THEN
        IF transaction_timestamp() >= OLD.expires_at
           OR NOT public.ple_instructor_approval_eligible(OLD.target_user_id)
           OR NEW.accepted_at <> transaction_timestamp()
           OR NOT EXISTS (
                SELECT 1 FROM public.course_member
                 WHERE tenant_id = OLD.tenant_id AND course_id = OLD.course_id
                   AND course_membership_id = NEW.accepted_membership_id
                   AND user_id = OLD.target_user_id AND role = 'instructor' AND status = 'active'
           ) THEN
            RAISE EXCEPTION 'invalid co-instructor invitation acceptance' USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.status = 'declined' THEN
        IF NEW.revoked_at IS NOT NULL OR NEW.declined_at <> transaction_timestamp() THEN
            RAISE EXCEPTION 'invalid co-instructor invitation terminal state' USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.status = 'revoked' THEN
        IF NEW.declined_at IS NOT NULL OR NEW.revoked_at <> transaction_timestamp() THEN
            RAISE EXCEPTION 'invalid co-instructor invitation terminal state' USING ERRCODE = '23514';
        END IF;
    ELSIF NEW.status = 'expired' THEN
        IF transaction_timestamp() < OLD.expires_at
           OR NEW.accepted_at IS NOT NULL OR NEW.declined_at IS NOT NULL
           OR NEW.revoked_at IS NOT NULL THEN
            RAISE EXCEPTION 'co-instructor invitation is not expired' USING ERRCODE = '23514';
        END IF;
    ELSE
        RAISE EXCEPTION 'co-instructor invitation may only leave pending once' USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
END
$$;

CREATE TRIGGER course_instructor_invitation_expires_prior_pending
    BEFORE INSERT ON public.course_instructor_invitation
    FOR EACH ROW EXECUTE FUNCTION public.ple_expire_pending_course_instructor_invitation();
CREATE TRIGGER course_instructor_invitation_guard
    BEFORE INSERT OR UPDATE ON public.course_instructor_invitation
    FOR EACH ROW EXECUTE FUNCTION public.ple_guard_course_instructor_invitation();

ALTER TABLE public.course_instructor_invitation ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.course_instructor_invitation FORCE ROW LEVEL SECURITY;
CREATE POLICY course_instructor_invitation_app ON public.course_instructor_invitation TO ple_app
    USING (tenant_id = public.ple_current_tenant()
           AND public.ple_course_records_accessible(tenant_id, course_id))
    WITH CHECK (tenant_id = public.ple_current_tenant()
                AND public.ple_course_records_accessible(tenant_id, course_id));
GRANT SELECT, INSERT, UPDATE ON public.course_instructor_invitation TO ple_app;

CREATE FUNCTION public.ple_course_instructor_invitation_reference_list(p_actor uuid, p_course uuid, p_after integer, p_limit integer)
RETURNS TABLE(invitation_public_id integer, target_public_id integer, target_display_name text,
              target_is_approved boolean, target_approval_revision bigint, state text,
              created_at_millis bigint, expires_at_millis bigint, revision bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT invitation.public_id, account.public_id, account.display_name,
           approval.revoked_at IS NULL, approval.revision,
           CASE WHEN invitation.status = 'pending' AND invitation.expires_at <= transaction_timestamp() THEN 'expired' ELSE invitation.status END,
           floor(extract(epoch FROM invitation.created_at) * 1000)::bigint, floor(extract(epoch FROM invitation.expires_at) * 1000)::bigint, invitation.revision
      FROM public.course_instructor_invitation invitation
      JOIN public.ple_account account ON account.user_id = invitation.target_user_id
      JOIN public.instructor_approval approval ON approval.user_id = invitation.target_user_id
     WHERE invitation.tenant_id = public.ple_current_tenant() AND invitation.course_id = p_course
       AND (p_after IS NULL OR invitation.public_id > p_after)
       AND EXISTS (SELECT 1 FROM public.course_member actor_membership WHERE actor_membership.tenant_id = invitation.tenant_id AND actor_membership.course_id = invitation.course_id AND actor_membership.user_id = p_actor AND actor_membership.role = 'instructor' AND actor_membership.status = 'active')
     ORDER BY invitation.public_id LIMIT p_limit
$$;
CREATE FUNCTION public.ple_pending_instructor_invitation_reference_list(p_session character(64), p_tenant uuid, p_after integer, p_limit integer)
RETURNS TABLE(invitation_public_id integer, course_title text, expires_at_millis bigint, revision bigint)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT invitation.public_id, course.title, floor(extract(epoch FROM invitation.expires_at) * 1000)::bigint, invitation.revision
      FROM public.auth_session session JOIN public.course_instructor_invitation invitation ON invitation.target_user_id = session.user_id
      JOIN public.course ON course.tenant_id = invitation.tenant_id AND course.course_id = invitation.course_id
     WHERE session.session_hash = p_session AND session.tenant_id = p_tenant AND session.tenant_id = public.ple_current_tenant()
       AND session.revoked_at IS NULL AND session.expires_at > transaction_timestamp() AND invitation.tenant_id = session.tenant_id
       AND invitation.status = 'pending' AND invitation.expires_at > transaction_timestamp() AND (p_after IS NULL OR invitation.public_id > p_after)
     ORDER BY invitation.public_id LIMIT p_limit
$$;
CREATE FUNCTION public.ple_course_membership_reference_list(p_actor uuid, p_course uuid, p_group_public_id integer, p_after integer, p_limit integer)
RETURNS TABLE(membership_public_id integer, display_name text, role text, status text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT membership.public_id, COALESCE(account.display_name, roster.display_name), membership.role, membership.status FROM public.course_member membership
    LEFT JOIN public.ple_account account ON account.user_id = membership.user_id
    LEFT JOIN public.course_roster_profile roster ON roster.tenant_id = membership.tenant_id AND roster.course_id = membership.course_id AND roster.course_membership_id = membership.course_membership_id
    WHERE membership.tenant_id = public.ple_current_tenant() AND membership.course_id = p_course AND (p_after IS NULL OR membership.public_id > p_after)
      AND (p_group_public_id IS NULL OR EXISTS (SELECT 1 FROM public.course_group group_record JOIN public.course_group_member group_membership ON group_membership.tenant_id = group_record.tenant_id AND group_membership.course_id = group_record.course_id AND group_membership.course_group_id = group_record.course_group_id AND group_membership.course_membership_id = membership.course_membership_id WHERE group_record.tenant_id = membership.tenant_id AND group_record.course_id = membership.course_id AND group_record.public_id = p_group_public_id))
      AND EXISTS (SELECT 1 FROM public.course_member actor_membership WHERE actor_membership.tenant_id = membership.tenant_id AND actor_membership.course_id = membership.course_id AND actor_membership.user_id = p_actor AND actor_membership.role = 'instructor' AND actor_membership.status = 'active')
    ORDER BY membership.public_id LIMIT p_limit
$$;
-- Assignment-access student selection is narrower than the general roster
-- list: only current active Students are eligible for projection.
CREATE FUNCTION public.ple_course_active_student_membership_reference_list(
    p_actor uuid, p_course uuid, p_after integer, p_limit integer
) RETURNS TABLE(
    membership_public_id integer, display_name text, role text, status text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT membership.public_id,
           COALESCE(account.display_name, roster.display_name),
           membership.role,
           membership.status
      FROM public.course_member membership
      LEFT JOIN public.ple_account account ON account.user_id = membership.user_id
      LEFT JOIN public.course_roster_profile roster
        ON roster.tenant_id = membership.tenant_id
       AND roster.course_id = membership.course_id
       AND roster.course_membership_id = membership.course_membership_id
     WHERE membership.tenant_id = public.ple_current_tenant()
       AND membership.course_id = p_course
       AND membership.role = 'student'
       AND membership.status = 'active'
       AND (p_after IS NULL OR membership.public_id > p_after)
       AND EXISTS (
           SELECT 1
             FROM public.course_member actor_membership
            WHERE actor_membership.tenant_id = membership.tenant_id
              AND actor_membership.course_id = membership.course_id
              AND actor_membership.user_id = p_actor
              AND actor_membership.role = 'instructor'
              AND actor_membership.status = 'active'
       )
     ORDER BY membership.public_id
     LIMIT p_limit
$$;
CREATE FUNCTION public.ple_course_active_student_membership_reference(
    p_actor uuid, p_course uuid, p_student uuid
) RETURNS TABLE(
    membership_public_id integer, display_name text, role text, status text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT membership.public_id,
           COALESCE(account.display_name, roster.display_name),
           membership.role,
           membership.status
      FROM public.course_member membership
      LEFT JOIN public.ple_account account ON account.user_id = membership.user_id
      LEFT JOIN public.course_roster_profile roster
        ON roster.tenant_id = membership.tenant_id
       AND roster.course_id = membership.course_id
       AND roster.course_membership_id = membership.course_membership_id
     WHERE membership.tenant_id = public.ple_current_tenant()
       AND membership.course_id = p_course
       AND membership.student_id = p_student
       AND membership.role = 'student'
       AND membership.status = 'active'
       AND EXISTS (
           SELECT 1 FROM public.course_member actor_membership
            WHERE actor_membership.tenant_id = membership.tenant_id
              AND actor_membership.course_id = membership.course_id
              AND actor_membership.user_id = p_actor
              AND actor_membership.role = 'instructor'
              AND actor_membership.status = 'active'
       )
$$;
CREATE FUNCTION public.ple_course_instructor_membership_reference_list(
    p_actor uuid, p_course uuid, p_after integer, p_limit integer
) RETURNS TABLE(
    membership_public_id integer, account_public_id integer, account_display_name text
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT membership.public_id, account.public_id, account.display_name
      FROM public.course_member membership
      JOIN public.ple_account account ON account.user_id = membership.user_id
     WHERE membership.tenant_id = public.ple_current_tenant() AND membership.course_id = p_course
       AND membership.role = 'instructor' AND membership.status = 'active'
       AND (p_after IS NULL OR membership.public_id > p_after)
       AND EXISTS (
           SELECT 1 FROM public.course_member actor_membership
            WHERE actor_membership.tenant_id = membership.tenant_id
              AND actor_membership.course_id = membership.course_id
              AND actor_membership.user_id = p_actor
              AND actor_membership.role = 'instructor'
              AND actor_membership.status = 'active'
       )
     ORDER BY membership.public_id LIMIT p_limit
$$;
CREATE FUNCTION public.ple_course_instructor_roster_revision(
    p_actor uuid, p_course uuid
) RETURNS bigint
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT roster.revision
      FROM public.course_roster_state roster
     WHERE roster.tenant_id = public.ple_current_tenant() AND roster.course_id = p_course
       AND EXISTS (
           SELECT 1 FROM public.course_member actor_membership
            WHERE actor_membership.tenant_id = roster.tenant_id
              AND actor_membership.course_id = roster.course_id
              AND actor_membership.user_id = p_actor
              AND actor_membership.role = 'instructor'
              AND actor_membership.status = 'active'
       )
$$;
ALTER FUNCTION public.ple_course_instructor_invitation_reference_list(
    uuid, uuid, integer, integer
) OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_pending_instructor_invitation_reference_list(
    character, uuid, integer, integer
) OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_course_membership_reference_list(
    uuid, uuid, integer, integer, integer
) OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_course_active_student_membership_reference_list(
    uuid, uuid, integer, integer
) OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_course_active_student_membership_reference(uuid, uuid, uuid)
    OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_course_instructor_membership_reference_list(
    uuid, uuid, integer, integer
) OWNER TO ple_teaching_authority_broker;
ALTER FUNCTION public.ple_course_instructor_roster_revision(uuid, uuid)
    OWNER TO ple_teaching_authority_broker;
REVOKE ALL ON FUNCTION public.ple_course_instructor_invitation_reference_list(
    uuid, uuid, integer, integer
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_pending_instructor_invitation_reference_list(
    character, uuid, integer, integer
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_course_membership_reference_list(
    uuid, uuid, integer, integer, integer
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_course_active_student_membership_reference_list(
    uuid, uuid, integer, integer
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_course_active_student_membership_reference(
    uuid, uuid, uuid
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_course_instructor_membership_reference_list(
    uuid, uuid, integer, integer
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.ple_course_instructor_roster_revision(uuid, uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_course_instructor_invitation_reference_list(
    uuid, uuid, integer, integer
) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_pending_instructor_invitation_reference_list(
    character, uuid, integer, integer
) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_course_membership_reference_list(
    uuid, uuid, integer, integer, integer
) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_course_active_student_membership_reference_list(
    uuid, uuid, integer, integer
) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_course_active_student_membership_reference(
    uuid, uuid, uuid
) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_course_instructor_membership_reference_list(
    uuid, uuid, integer, integer
) TO ple_app;
GRANT EXECUTE ON FUNCTION public.ple_course_instructor_roster_revision(uuid, uuid) TO ple_app;

-- Co-instructor discovery is intentionally a narrow account-presentation
-- projection.  The broker can read exactly the invitation columns needed to
-- suppress currently pending targets; it never returns account UUIDs or email.
CREATE POLICY course_instructor_invitation_teaching_authority_broker
    ON public.course_instructor_invitation FOR SELECT TO ple_teaching_authority_broker
    USING (tenant_id = public.ple_current_tenant());
GRANT SELECT (
    tenant_id, course_id, public_id, target_user_id, status, expires_at,
    created_at, revision
) ON public.course_instructor_invitation TO ple_teaching_authority_broker;

CREATE FUNCTION public.ple_course_co_instructor_target_search(
    p_actor uuid, p_course uuid, p_query text, p_after integer, p_limit integer
) RETURNS TABLE(
    account_public_id integer, account_display_name text, approval_revision bigint
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path TO 'pg_catalog', 'public' AS $$
    SELECT account.public_id, account.display_name, approval.revision
      FROM public.ple_account AS account
      JOIN public.instructor_approval AS approval ON approval.user_id = account.user_id
     WHERE approval.revoked_at IS NULL
       AND position(lower(p_query) IN lower(account.display_name)) > 0
       AND (p_after IS NULL OR account.public_id > p_after)
       AND NOT EXISTS (
           SELECT 1 FROM public.course_member AS membership
            WHERE membership.tenant_id = public.ple_current_tenant()
              AND membership.course_id = p_course
              AND membership.user_id = account.user_id
              AND membership.role = 'instructor'
              AND membership.status = 'active'
       )
       AND NOT EXISTS (
           SELECT 1 FROM public.course_instructor_invitation AS invitation
            WHERE invitation.tenant_id = public.ple_current_tenant()
              AND invitation.course_id = p_course
              AND invitation.target_user_id = account.user_id
              AND invitation.status = 'pending'
              AND invitation.expires_at > transaction_timestamp()
       )
       AND EXISTS (
           SELECT 1 FROM public.course_member AS actor_membership
            WHERE actor_membership.tenant_id = public.ple_current_tenant()
              AND actor_membership.course_id = p_course
              AND actor_membership.user_id = p_actor
              AND actor_membership.role = 'instructor'
              AND actor_membership.status = 'active'
       )
     ORDER BY account.public_id
     LIMIT p_limit
$$;
ALTER FUNCTION public.ple_course_co_instructor_target_search(uuid, uuid, text, integer, integer)
    OWNER TO ple_teaching_authority_broker;
REVOKE ALL ON FUNCTION public.ple_course_co_instructor_target_search(
    uuid, uuid, text, integer, integer
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ple_course_co_instructor_target_search(
    uuid, uuid, text, integer, integer
) TO ple_app;

-- Direct mutations cannot revoke the final current Instructor membership.
CREATE FUNCTION public.ple_guard_final_active_course_instructor() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public'
AS $$
BEGIN
    IF OLD.role = 'instructor' AND OLD.status = 'active'
       AND NEW.status = 'revoked' THEN
        -- Every final-Instructor transition takes this exact parent row before
        -- it counts peers.  The row lock is shared by all membership changes
        -- for this tenant/course, so a second revocation waits, then sees the
        -- first committed revocation and refuses.  No cross-course lock is
        -- acquired, and course deletion cascades DELETE rows rather than this
        -- status UPDATE trigger.
        PERFORM 1 FROM public.course
         WHERE tenant_id = OLD.tenant_id AND course_id = OLD.course_id
         FOR UPDATE;
        IF NOT EXISTS (
            SELECT 1 FROM public.course_member AS other
             WHERE other.tenant_id = OLD.tenant_id AND other.course_id = OLD.course_id
               AND other.role = 'instructor' AND other.status = 'active'
               AND other.course_membership_id <> OLD.course_membership_id
        ) THEN
            RAISE EXCEPTION 'cannot revoke the final active course instructor' USING ERRCODE = '23514';
        END IF;
    END IF;
    RETURN NEW;
END
$$;
CREATE TRIGGER course_member_final_active_instructor_guard
    BEFORE UPDATE OF status ON public.course_member
    FOR EACH ROW EXECUTE FUNCTION public.ple_guard_final_active_course_instructor();

-- Existing S3 modifier FKs were cascading and therefore contradicted T2's
-- reference-refusal rule.  Rebuild all three group references as RESTRICT.
ALTER TABLE public.assignment_group_schedule_offset
    DROP CONSTRAINT assignment_group_schedule_offset_group_fk,
    ADD CONSTRAINT assignment_group_schedule_offset_group_fk
        FOREIGN KEY (tenant_id, course_id, course_group_id)
        REFERENCES public.course_group(tenant_id, course_id, course_group_id) ON DELETE RESTRICT;
ALTER TABLE public.assignment_group_accommodation
    DROP CONSTRAINT assignment_group_accommodation_group_fk,
    ADD CONSTRAINT assignment_group_accommodation_group_fk
        FOREIGN KEY (tenant_id, course_id, course_group_id)
        REFERENCES public.course_group(tenant_id, course_id, course_group_id) ON DELETE RESTRICT;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.assignment_audience_group AS audience
        JOIN public.course_group AS groups
          ON groups.tenant_id = audience.tenant_id
         AND groups.course_id = audience.course_id
         AND groups.course_group_id = audience.course_group_id
        WHERE groups.purpose NOT IN ('section', 'lab', 'cohort')
    ) OR EXISTS (
        SELECT 1 FROM public.assignment_group_schedule_offset AS modifier
        JOIN public.course_group AS groups
          ON groups.tenant_id = modifier.tenant_id
         AND groups.course_id = modifier.course_id
         AND groups.course_group_id = modifier.course_group_id
        WHERE groups.purpose NOT IN ('section', 'lab', 'cohort')
    ) OR EXISTS (
        SELECT 1 FROM public.assignment_group_accommodation AS modifier
        JOIN public.course_group AS groups
          ON groups.tenant_id = modifier.tenant_id
         AND groups.course_id = modifier.course_id
         AND groups.course_group_id = modifier.course_group_id
        WHERE groups.purpose <> 'accommodation'
    ) THEN
        RAISE EXCEPTION 'T2 group-purpose cutover found invalid existing references'
            USING ERRCODE = '23514';
    END IF;
END
$$;

CREATE FUNCTION public.ple_validate_assignment_group_reference_purpose() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public'
AS $$
DECLARE group_purpose text;
BEGIN
    SELECT purpose INTO group_purpose FROM public.course_group
     WHERE tenant_id = NEW.tenant_id AND course_id = NEW.course_id
       AND course_group_id = NEW.course_group_id;
    IF TG_TABLE_NAME = 'assignment_group_accommodation' THEN
        IF group_purpose <> 'accommodation' THEN
            RAISE EXCEPTION 'accommodation modifier requires an accommodation group'
                USING ERRCODE = '23514';
        END IF;
    ELSIF group_purpose NOT IN ('section', 'lab', 'cohort') THEN
        RAISE EXCEPTION 'audience and schedule modifiers require section, lab, or cohort groups'
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END
$$;

CREATE FUNCTION public.ple_validate_course_group_purpose_references() RETURNS trigger
    LANGUAGE plpgsql
    SET search_path TO 'pg_catalog', 'public'
AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM public.assignment_audience_group
         WHERE tenant_id = NEW.tenant_id AND course_id = NEW.course_id
           AND course_group_id = NEW.course_group_id
    ) OR EXISTS (
        SELECT 1 FROM public.assignment_group_schedule_offset
         WHERE tenant_id = NEW.tenant_id AND course_id = NEW.course_id
           AND course_group_id = NEW.course_group_id
    ) THEN
        IF NEW.purpose NOT IN ('section', 'lab', 'cohort') THEN
            RAISE EXCEPTION 'group purpose conflicts with audience or schedule modifier'
                USING ERRCODE = '23514';
        END IF;
    END IF;
    IF EXISTS (
        SELECT 1 FROM public.assignment_group_accommodation
         WHERE tenant_id = NEW.tenant_id AND course_id = NEW.course_id
           AND course_group_id = NEW.course_group_id
    ) AND NEW.purpose <> 'accommodation' THEN
        RAISE EXCEPTION 'group purpose conflicts with accommodation modifier'
            USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END
$$;

CREATE CONSTRAINT TRIGGER assignment_audience_group_purpose_check
    AFTER INSERT OR UPDATE OF course_group_id, course_id ON public.assignment_audience_group
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
    EXECUTE FUNCTION public.ple_validate_assignment_group_reference_purpose();
CREATE CONSTRAINT TRIGGER assignment_group_schedule_offset_purpose_check
    AFTER INSERT OR UPDATE OF course_group_id, course_id ON public.assignment_group_schedule_offset
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
    EXECUTE FUNCTION public.ple_validate_assignment_group_reference_purpose();
CREATE CONSTRAINT TRIGGER assignment_group_accommodation_purpose_check
    AFTER INSERT OR UPDATE OF course_group_id, course_id ON public.assignment_group_accommodation
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
    EXECUTE FUNCTION public.ple_validate_assignment_group_reference_purpose();
CREATE CONSTRAINT TRIGGER course_group_purpose_reference_check
    AFTER UPDATE OF purpose ON public.course_group
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
    EXECUTE FUNCTION public.ple_validate_course_group_purpose_references();

COMMIT;
