use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

use super::model::Generated;
use anyhow::{Context, Result, bail};

pub(super) const GENERATED_HEADER: &str =
    "// Generated by crates/project-tools from Rust contract roots.";
pub(super) const LEGACY_PROJECT_TOOLS_GENERATED_HEADER: &str =
    "// Generated by crates/project-tools from the Rust question model.";
pub(super) const LEGACY_XTASK_GENERATED_HEADER: &str =
    "// Generated by crates/xtask from the Rust question model.";

pub(super) fn prepare_out_dir(out_dir: &Path) -> Result<()> {
    fs::create_dir_all(out_dir).with_context(|| format!("creating {}", out_dir.display()))?;
    let entries =
        fs::read_dir(out_dir).with_context(|| format!("reading {}", out_dir.display()))?;
    let mut owned_paths = Vec::new();
    for entry in entries {
        let path = entry
            .with_context(|| format!("reading an entry in {}", out_dir.display()))?
            .path();
        if path.extension().is_none_or(|extension| extension != "ts") {
            continue;
        }
        let source = fs::read_to_string(&path)
            .with_context(|| format!("checking generated marker in {}", path.display()))?;
        if !has_owned_header(&source) {
            bail!(
                "refusing to replace unowned TypeScript in generated output: {}",
                path.display()
            );
        }
        owned_paths.push(path);
    }
    for path in owned_paths {
        fs::remove_file(&path).with_context(|| format!("removing stale {}", path.display()))?;
    }
    Ok(())
}

fn has_owned_header(source: &str) -> bool {
    matches!(
        source.lines().next(),
        Some(GENERATED_HEADER)
            | Some(LEGACY_PROJECT_TOOLS_GENERATED_HEADER)
            | Some(LEGACY_XTASK_GENERATED_HEADER)
    )
}
pub(super) fn render(
    type_definition: &Generated,
    generated_declaration_names: &BTreeSet<String>,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// Do not edit by hand; run ./build.sh (or cargo tools tsgen).\n");
    let mut imports: Vec<&String> = type_definition
        .dependencies
        .iter()
        .filter(|name| {
            **name != type_definition.name && generated_declaration_names.contains(*name)
        })
        .collect();
    imports.sort();
    if !imports.is_empty() {
        out.push('\n');
        for import in imports {
            let _ = writeln!(out, "import type {{ {import} }} from \"./{import}\";");
        }
    }
    out.push('\n');
    if !type_definition.docs.is_empty() {
        out.push_str("/**\n");
        for line in &type_definition.docs {
            if line.trim().is_empty() {
                out.push_str(" *\n");
            } else {
                let _ = writeln!(out, " *{line}");
            }
        }
        out.push_str(" */\n");
    }
    if let Some(value) = type_definition.body.strip_prefix("__CONST__ ") {
        let _ = writeln!(
            out,
            "export const {} = {value} as const;",
            type_definition.name
        );
        return out;
    }
    if type_definition.body.starts_with('\n') {
        let _ = writeln!(
            out,
            "export type {} ={};",
            type_definition.name, type_definition.body
        );
    } else {
        let _ = writeln!(
            out,
            "export type {} = {};",
            type_definition.name, type_definition.body
        );
    }
    out
}
