// Runtime narrowing for untrusted URL strings. Wire strings themselves are generated by Rust.

import type { AssignmentReference } from "../../generated/api/AssignmentReference";
import type { CourseReference } from "../../generated/api/CourseReference";
import type { CourseMembershipReference } from "../../generated/api/CourseMembershipReference";
import type { QuestionId } from "../../generated/api/QuestionId";
import type { AssignmentAttemptReference } from "../../generated/api/AssignmentAttemptReference";
import type { WorkspaceReference } from "../../generated/api/WorkspaceReference";
import { normalizeQuestionIdSyntax } from "../question_id";

declare const routeReferenceBrand: unique symbol;
type BrandedRouteReference<Kind extends string> = string & { readonly [routeReferenceBrand]: Kind };
export type CourseRouteReference = CourseReference & BrandedRouteReference<"course">;
export type CourseMembershipRouteReference = CourseMembershipReference &
  BrandedRouteReference<"courseMembership">;
export type AssignmentRouteReference = AssignmentReference & BrandedRouteReference<"assignment">;
export type AssignmentAttemptRouteReference = AssignmentAttemptReference &
  BrandedRouteReference<"assignmentAttempt">;
export type WorkspaceRouteReference = WorkspaceReference & BrandedRouteReference<"workspace">;
export type ProblemRouteReference = BrandedRouteReference<"question">;
export type PublicRouteReference =
  | AssignmentAttemptRouteReference
  | CourseRouteReference
  | AssignmentRouteReference
  | WorkspaceRouteReference;

function parseExact<Kind extends string>(
  value: string,
  prefix: string,
): BrandedRouteReference<Kind> | null {
  if (!new RegExp(`^${prefix}-[1-9][0-9]{0,9}$`, "u").test(value)) return null;
  const number = Number(value.slice(prefix.length + 1));
  return Number.isSafeInteger(number) && number <= 2_147_483_647
    ? (value as BrandedRouteReference<Kind>)
    : null;
}
export function parseCourseReference(value: string): CourseRouteReference | null {
  return parseExact<"course">(value, "C");
}
export function parseCourseMembershipReference(
  value: string,
): CourseMembershipRouteReference | null {
  return parseExact<"courseMembership">(value, "M");
}
export function parseAssignmentReference(value: string): AssignmentRouteReference | null {
  return parseExact<"assignment">(value, "A");
}
export function parseAssignmentAttemptReference(
  value: string,
): AssignmentAttemptRouteReference | null {
  return parseExact<"assignmentAttempt">(value, "R");
}
export function parseWorkspaceReference(value: string): WorkspaceRouteReference | null {
  return parseExact<"workspace">(value, "W");
}
export function courseRouteReference(value: CourseReference): CourseRouteReference {
  const result = parseCourseReference(value);
  if (result === null) throw new Error("invalid course reference");
  return result;
}
export function assignmentRouteReference(value: AssignmentReference): AssignmentRouteReference {
  const result = parseAssignmentReference(value);
  if (result === null) throw new Error("invalid assignment reference");
  return result;
}
export function courseMembershipRouteReference(
  value: CourseMembershipReference,
): CourseMembershipRouteReference {
  const result = parseCourseMembershipReference(value);
  if (result === null) throw new Error("invalid course membership reference");
  return result;
}
export function assignmentAttemptRouteReference(
  value: AssignmentAttemptReference,
): AssignmentAttemptRouteReference {
  const result = parseAssignmentAttemptReference(value);
  if (result === null) throw new Error("invalid Assignment Attempt reference");
  return result;
}
export function workspaceRouteReference(value: WorkspaceReference): WorkspaceRouteReference {
  const result = parseWorkspaceReference(value);
  if (result === null) throw new Error("invalid workspace reference");
  return result;
}
export function parsePublicRouteReference(value: string): PublicRouteReference | null {
  return (
    parseCourseReference(value) ??
    parseAssignmentReference(value) ??
    parseAssignmentAttemptReference(value) ??
    parseWorkspaceReference(value)
  );
}
export function problemRouteReference(questionId: QuestionId): ProblemRouteReference {
  const result = parseProblemRouteReference(questionId);
  if (result === null) throw new Error("question ID must use Crockford Base32");
  return result;
}
export function parseProblemRouteReference(value: string): ProblemRouteReference | null {
  return normalizeQuestionIdSyntax(value) as ProblemRouteReference | null;
}
