// Runtime narrowing for untrusted URL strings. Wire strings themselves are generated by Rust.

import type { AssessmentReference } from "../../generated/api/AssessmentReference";
import type { CourseInstanceReference } from "../../generated/api/CourseInstanceReference";
import type { CourseMembershipReference } from "../../generated/api/CourseMembershipReference";
import type { QuestionId } from "../../generated/api/QuestionId";
import type { AssessmentAttemptReference } from "../../generated/api/AssessmentAttemptReference";
import type { AuthoringWorkspaceReference } from "../../generated/api/AuthoringWorkspaceReference";
import type { DraftQuestionReference } from "../../generated/api/DraftQuestionReference";
import type { BlueprintCourseReference } from "../../generated/api/BlueprintCourseReference";
import {
  validateCanonicalPublicReference,
  validateCanonicalQuestionIdSyntax,
  type CanonicalPublicReferenceFamily,
} from "../question_id";

declare const routeReferenceBrand: unique symbol;
type BrandedRouteReference<Kind extends string> = string & { readonly [routeReferenceBrand]: Kind };
export type CourseInstanceRouteReference = CourseInstanceReference &
  BrandedRouteReference<"courseInstance">;
export type CourseMembershipRouteReference = CourseMembershipReference &
  BrandedRouteReference<"courseMembership">;
export type AssessmentRouteReference = AssessmentReference & BrandedRouteReference<"assessment">;
export type AssessmentAttemptRouteReference = AssessmentAttemptReference &
  BrandedRouteReference<"assessmentAttempt">;
export type AuthoringWorkspaceRouteReference = AuthoringWorkspaceReference &
  BrandedRouteReference<"authoringWorkspace">;
export type DraftQuestionRouteReference = DraftQuestionReference &
  BrandedRouteReference<"draftQuestion">;
export type BlueprintCourseRouteReference = BlueprintCourseReference &
  BrandedRouteReference<"blueprintCourse">;
export type QuestionRouteReference = BrandedRouteReference<"question">;
export type PublicRouteReference =
  | AssessmentAttemptRouteReference
  | CourseInstanceRouteReference
  | AssessmentRouteReference
  | AuthoringWorkspaceRouteReference
  | DraftQuestionRouteReference
  | BlueprintCourseRouteReference;

function parseNumeric<Kind extends string>(
  value: string,
  prefix: string,
): BrandedRouteReference<Kind> | null {
  if (!new RegExp(`^${prefix}-[1-9][0-9]{0,9}$`, "u").test(value)) return null;
  const number = Number(value.slice(prefix.length + 1));
  return Number.isSafeInteger(number) && number <= 2_147_483_647
    ? (value as BrandedRouteReference<Kind>)
    : null;
}
export function parseCourseInstanceReference(value: string): CourseInstanceRouteReference | null {
  return parseCanonicalPublicReference<"courseInstance">(value, "courseInstance");
}
export function parseCourseMembershipReference(
  value: string,
): CourseMembershipRouteReference | null {
  return parseNumeric<"courseMembership">(value, "M");
}
export function parseAssessmentReference(value: string): AssessmentRouteReference | null {
  return parseCanonicalPublicReference<"assessment">(value, "assessment");
}
export function parseAssessmentAttemptReference(
  value: string,
): AssessmentAttemptRouteReference | null {
  return parseNumeric<"assessmentAttempt">(value, "R");
}
export function parseAuthoringWorkspaceReference(
  value: string,
): AuthoringWorkspaceRouteReference | null {
  return parseNumeric<"authoringWorkspace">(value, "W");
}
export function parseDraftQuestionReference(value: string): DraftQuestionRouteReference | null {
  return parseNumeric<"draftQuestion">(value, "D");
}
export function parseBlueprintCourseReference(value: string): BlueprintCourseRouteReference | null {
  return parseCanonicalPublicReference<"blueprintCourse">(value, "blueprintCourse");
}

/** Syntax only: the existing opaque Proposal UUID is never an authorization grant. */
export function parseBlueprintChangeProposalHandle(value: string): string | null {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/u.test(value)
    ? value
    : null;
}

/** Parses one exact, checksum-valid public ID without reformatting it. */
function parseCanonicalPublicReference<Kind extends string>(
  value: string,
  family: CanonicalPublicReferenceFamily,
): BrandedRouteReference<Kind> | null {
  const result = validateCanonicalPublicReference(family, value);
  return result === null ? null : (result as BrandedRouteReference<Kind>);
}
export function courseInstanceRouteReference(
  value: CourseInstanceReference,
): CourseInstanceRouteReference {
  const result = parseCourseInstanceReference(value);
  if (result === null) throw new Error("invalid Course Instance Reference");
  return result;
}
export function assessmentRouteReference(value: AssessmentReference): AssessmentRouteReference {
  const result = parseAssessmentReference(value);
  if (result === null) throw new Error("invalid assessment reference");
  return result;
}
export function courseMembershipRouteReference(
  value: CourseMembershipReference,
): CourseMembershipRouteReference {
  const result = parseCourseMembershipReference(value);
  if (result === null) throw new Error("invalid course membership reference");
  return result;
}
export function assessmentAttemptRouteReference(
  value: AssessmentAttemptReference,
): AssessmentAttemptRouteReference {
  const result = parseAssessmentAttemptReference(value);
  if (result === null) throw new Error("invalid Assessment Attempt reference");
  return result;
}
export function authoringWorkspaceRouteReference(
  value: AuthoringWorkspaceReference,
): AuthoringWorkspaceRouteReference {
  const result = parseAuthoringWorkspaceReference(value);
  if (result === null) throw new Error("invalid Authoring Workspace Reference");
  return result;
}
export function draftQuestionRouteReference(
  value: DraftQuestionReference,
): DraftQuestionRouteReference {
  const result = parseDraftQuestionReference(value);
  if (result === null) throw new Error("invalid Draft Question Reference");
  return result;
}
export function parsePublicRouteReference(value: string): PublicRouteReference | null {
  return (
    parseCourseInstanceReference(value) ??
    parseAssessmentReference(value) ??
    parseAssessmentAttemptReference(value) ??
    parseAuthoringWorkspaceReference(value) ??
    parseDraftQuestionReference(value) ??
    parseBlueprintCourseReference(value)
  );
}
export function questionRouteReference(questionId: QuestionId): QuestionRouteReference {
  const result = parseQuestionRouteReference(questionId);
  if (result === null) throw new Error("question ID must use Crockford Base32");
  return result;
}
export function parseQuestionRouteReference(value: string): QuestionRouteReference | null {
  const result = validateCanonicalQuestionIdSyntax(value);
  return result === null ? null : (result as QuestionRouteReference);
}
