// build_ribbon_icon_sprite.mjs - create the exact Font Awesome SVG subset used by the Ribbon.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  faArrowLeft,
  faBookOpen,
  faCircleUser,
  faClipboardList,
  faEye,
  faFilePen,
  faGear,
  faGraduationCap,
  faListCheck,
  faPalette,
  faPenToSquare,
  faRightFromBracket,
  faStar,
  faTableList,
  faUserGraduate,
  faUsers,
} from "@fortawesome/free-solid-svg-icons";

import {
  RIBBON_CONTEXT_GLYPHS,
  RIBBON_DESTINATION_GLYPHS,
  RIBBON_GLYPH_IDS,
} from "../src/ribbon/ribbon_icons.ts";
import { getRepoRoot } from "./repo_root.mjs";

const SAFE_GLYPH_ID = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/u;
const PATH_COMMAND_ARITY = new Map([
  ["M", 2],
  ["L", 2],
  ["H", 1],
  ["V", 1],
  ["C", 6],
  ["S", 4],
  ["Q", 4],
  ["T", 2],
  ["A", 7],
  ["Z", 0],
]);
const PATH_TOKEN = /[a-zA-Z]|[-+]?(?:(?:\d+\.?\d*)|(?:\.\d+))(?:[eE][-+]?\d+)?/uy;
const GENERATED_SPRITE_PREFIX =
  "<!-- Generated by devel/build_ribbon_icon_sprite.mjs. Do not edit by hand. -->\n" +
  '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">\n' +
  "  <defs>\n";
const GENERATED_SPRITE_SUFFIX = "  </defs>\n</svg>\n";
const GENERATED_SYMBOL = new RegExp(
  [
    '^ {4}<symbol id="([a-z][a-z0-9]*(?:-[a-z0-9]+)*)" ',
    'viewBox="0 0 ([1-9]\\d*) ([1-9]\\d*)">\\n',
    '((?: {6}<path d="(?:[^"<&]|&(amp|lt|gt|quot|apos);)+" \\/>\\n)+)',
    " {4}<\\/symbol>$",
  ].join(""),
  "u",
);
const GENERATED_PATH = /^ {6}<path d="((?:[^"<&]|&(amp|lt|gt|quot|apos);)+)" \/>$/u;
const XML_ATTRIBUTE_ENTITIES = new Map([
  ["amp", "&"],
  ["lt", "<"],
  ["gt", ">"],
  ["quot", '"'],
  ["apos", "'"],
]);
/**
 * The generator admits only the glyphs declared by the Ribbon's semantic
 * vocabulary. Keeping this explicit makes an accidental package-wide Font
 * Awesome import impossible and leaves unknown contract glyphs as hard errors.
 */
const FONT_AWESOME_DEFINITIONS = Object.freeze({
  "arrow-left": faArrowLeft,
  "book-open": faBookOpen,
  "circle-user": faCircleUser,
  "clipboard-list": faClipboardList,
  eye: faEye,
  "file-pen": faFilePen,
  gear: faGear,
  "graduation-cap": faGraduationCap,
  "list-check": faListCheck,
  palette: faPalette,
  "pen-to-square": faPenToSquare,
  "right-from-bracket": faRightFromBracket,
  star: faStar,
  "table-list": faTableList,
  "user-graduate": faUserGraduate,
  users: faUsers,
});

function spritePathFor(repoRoot) {
  return path.join(repoRoot, "src/ribbon/assets/ribbon-icons.svg");
}

//============================================

function glyphIdsFromContract() {
  const glyphIds = new Set([
    ...Object.values(RIBBON_DESTINATION_GLYPHS),
    ...Object.values(RIBBON_CONTEXT_GLYPHS),
  ]);
  const glyphIdsSorted = [...glyphIds].sort();
  assertSameGlyphSet([...RIBBON_GLYPH_IDS].sort(), glyphIdsSorted);
  return glyphIdsSorted;
}

//============================================

function iconDefinitionFor(glyphId) {
  const definition = FONT_AWESOME_DEFINITIONS[glyphId];
  if (definition === undefined || typeof definition !== "object" || definition === null) {
    throw new Error(`Font Awesome Free has no solid SVG definition for Ribbon glyph ${glyphId}.`);
  }
  if (!("icon" in definition) || !Array.isArray(definition.icon)) {
    throw new Error(`Font Awesome Free definition for Ribbon glyph ${glyphId} has no icon tuple.`);
  }
  return definition;
}

//============================================

export function validateGlyphId(glyphId) {
  if (typeof glyphId !== "string" || !SAFE_GLYPH_ID.test(glyphId)) {
    throw new Error(`Ribbon glyph ID must be a safe XML identifier: ${String(glyphId)}.`);
  }
  return glyphId;
}

//============================================

export function validateViewBoxDimension(glyphId, dimension, name) {
  if (!Number.isInteger(dimension) || dimension < 1 || dimension > 100_000) {
    throw new Error(`Font Awesome Free glyph ${glyphId} has an invalid ${name}.`);
  }
  return dimension;
}

//============================================

function containsForbiddenControl(value) {
  for (const character of value) {
    const codePoint = character.codePointAt(0);
    if (codePoint <= 0x1f || codePoint === 0x7f) return true;
  }
  return false;
}

//============================================

/**
 * Admit the compact absolute/relative SVG path subset emitted by Font Awesome.
 * This deliberately excludes XML syntax, control characters, and every non-path
 * command before package data reaches the generated SVG document.
 */
export function validatePathData(glyphId, pathData) {
  if (typeof pathData !== "string" || pathData.length === 0 || containsForbiddenControl(pathData)) {
    throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
  }

  const tokens = [];
  let position = 0;
  while (position < pathData.length) {
    if (pathData[position] === " ") {
      position += 1;
      continue;
    }
    if (pathData[position] === ",") {
      const priorToken = tokens.at(-1);
      let nextPosition = position + 1;
      while (pathData[nextPosition] === " ") nextPosition += 1;
      PATH_TOKEN.lastIndex = nextPosition;
      const nextToken = PATH_TOKEN.exec(pathData)?.[0];
      if (
        priorToken === undefined ||
        /^[a-zA-Z]$/u.test(priorToken) ||
        nextToken === undefined ||
        /^[a-zA-Z]$/u.test(nextToken)
      ) {
        throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
      }
      position = nextPosition;
      continue;
    }
    PATH_TOKEN.lastIndex = position;
    const match = PATH_TOKEN.exec(pathData);
    if (match === null) {
      throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
    }
    tokens.push(match[0]);
    position = PATH_TOKEN.lastIndex;
  }

  let command = undefined;
  let parameterCount = 0;
  let sawCommand = false;
  const commandIsComplete = () => {
    const arity = PATH_COMMAND_ARITY.get(command);
    return arity === 0
      ? parameterCount === 0
      : parameterCount >= arity && parameterCount % arity === 0;
  };
  for (const token of tokens) {
    if (/^[a-zA-Z]$/u.test(token)) {
      const upper = token.toUpperCase();
      if (!PATH_COMMAND_ARITY.has(upper)) {
        throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
      }
      if (command !== undefined && !commandIsComplete()) {
        throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
      }
      command = upper;
      parameterCount = 0;
      sawCommand = true;
      continue;
    }
    const numericValue = Number(token);
    if (command === undefined || !Number.isFinite(numericValue)) {
      throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
    }
    const arity = PATH_COMMAND_ARITY.get(command);
    if (arity === 0)
      throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
    if (command === "A") {
      const parameterPosition = parameterCount % arity;
      if (
        ((parameterPosition === 0 || parameterPosition === 1) && numericValue < 0) ||
        ((parameterPosition === 3 || parameterPosition === 4) && !/^[01]$/u.test(token))
      ) {
        throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
      }
    }
    parameterCount += 1;
  }
  if (
    command === undefined ||
    tokens[0]?.toUpperCase() !== "M" ||
    !sawCommand ||
    !commandIsComplete()
  ) {
    throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
  }
  return pathData;
}

//============================================

export function xmlEscapeAttribute(value) {
  return String(value).replace(
    /[&<>"']/gu,
    (character) =>
      ({
        "&": "&amp;",
        "<": "&lt;",
        ">": "&gt;",
        '"': "&quot;",
        "'": "&apos;",
      })[character],
  );
}

//============================================

function xmlUnescapeAttribute(value) {
  return value.replace(
    /&(amp|lt|gt|quot|apos);/gu,
    (_entity, name) => XML_ATTRIBUTE_ENTITIES.get(name) ?? "",
  );
}

//============================================

/**
 * Validate the intentionally tiny, exact SVG grammar emitted by renderSprite.
 * Keeping this check in-process makes sprite validation portable while refusing
 * every tag, attribute, order, or entity outside the generator's fixed subset.
 */
export function validateGeneratedSprite(sprite, expectedGlyphIds) {
  if (typeof sprite !== "string" || !Array.isArray(expectedGlyphIds)) {
    throw new Error("Ribbon sprite does not use the generated SVG subset.");
  }
  if (!sprite.startsWith(GENERATED_SPRITE_PREFIX) || !sprite.endsWith(GENERATED_SPRITE_SUFFIX)) {
    throw new Error("Ribbon sprite does not use the generated SVG subset.");
  }

  const symbolText = sprite.slice(GENERATED_SPRITE_PREFIX.length, -GENERATED_SPRITE_SUFFIX.length);
  if (!symbolText.endsWith("\n")) {
    throw new Error("Ribbon sprite does not use the generated SVG subset.");
  }
  const symbols = symbolText.slice(0, -1).split("\n");
  const actualGlyphIds = [];
  let symbolLines = [];
  const validateSymbol = () => {
    const symbol = symbolLines.join("\n");
    const match = GENERATED_SYMBOL.exec(symbol);
    if (match === null) throw new Error("Ribbon sprite does not use the generated SVG subset.");
    validateGlyphId(match[1]);
    validateViewBoxDimension(match[1], Number(match[2]), "viewBox width");
    validateViewBoxDimension(match[1], Number(match[3]), "viewBox height");
    for (const pathLine of match[4].trimEnd().split("\n")) {
      const pathMatch = GENERATED_PATH.exec(pathLine);
      if (pathMatch === null)
        throw new Error("Ribbon sprite does not use the generated SVG subset.");
      validatePathData(match[1], xmlUnescapeAttribute(pathMatch[1]));
    }
    actualGlyphIds.push(match[1]);
    symbolLines = [];
  };
  for (const line of symbols) {
    if (line.startsWith("    <symbol ")) {
      if (symbolLines.length !== 0)
        throw new Error("Ribbon sprite does not use the generated SVG subset.");
      symbolLines.push(line);
    } else if (symbolLines.length !== 0) {
      symbolLines.push(line);
      if (line === "    </symbol>") validateSymbol();
    } else {
      throw new Error("Ribbon sprite does not use the generated SVG subset.");
    }
  }
  if (symbolLines.length !== 0)
    throw new Error("Ribbon sprite does not use the generated SVG subset.");
  assertSameGlyphSet([...expectedGlyphIds].sort(), actualGlyphIds.sort());
  return sprite;
}

//============================================

export function pathsFromDefinition(glyphId, definition) {
  validateGlyphId(glyphId);
  const icon = definition.icon;
  const width = icon[0];
  const height = icon[1];
  const pathData = icon[4];
  validateViewBoxDimension(glyphId, width, "viewBox width");
  validateViewBoxDimension(glyphId, height, "viewBox height");
  const paths = typeof pathData === "string" ? [pathData] : pathData;
  if (
    !Array.isArray(paths) ||
    paths.length === 0 ||
    paths.some((entry) => typeof entry !== "string")
  ) {
    throw new Error(`Font Awesome Free glyph ${glyphId} has invalid SVG path data.`);
  }
  return { width, height, paths: paths.map((entry) => validatePathData(glyphId, entry)) };
}

//============================================

function renderSymbol(glyphId) {
  validateGlyphId(glyphId);
  const definition = iconDefinitionFor(glyphId);
  const { width, height, paths } = pathsFromDefinition(glyphId, definition);
  const renderedPaths = paths
    .map((pathData) => `      <path d="${xmlEscapeAttribute(pathData)}" />`)
    .join("\n");
  const escapedGlyphId = xmlEscapeAttribute(glyphId);
  const escapedWidth = xmlEscapeAttribute(width);
  const escapedHeight = xmlEscapeAttribute(height);
  const symbolOpen =
    `    <symbol id="${escapedGlyphId}" ` + `viewBox="0 0 ${escapedWidth} ${escapedHeight}">`;
  return [symbolOpen, renderedPaths, "    </symbol>"].join("\n");
}

//============================================

export function renderSprite(glyphIds) {
  if (!Array.isArray(glyphIds)) {
    throw new Error("Ribbon sprite glyph IDs must be an array.");
  }
  glyphIds.forEach(validateGlyphId);
  const symbols = glyphIds.map(renderSymbol).join("\n");
  return [
    "<!-- Generated by devel/build_ribbon_icon_sprite.mjs. Do not edit by hand. -->",
    '<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false">',
    "  <defs>",
    symbols,
    "  </defs>",
    "</svg>",
    "",
  ].join("\n");
}

//============================================

function assertSameGlyphSet(expectedGlyphIds, actualGlyphIds) {
  const expected = expectedGlyphIds.join(", ");
  const actual = actualGlyphIds.join(", ");
  if (expected !== actual) {
    throw new Error(
      "Ribbon sprite glyph IDs differ from the glyph contract. " +
        `Expected: ${expected}. Actual: ${actual}.`,
    );
  }
}

//============================================

function parseCheckMode() {
  const args = process.argv.slice(2);
  if (args.length === 0) return false;
  if (args.length === 1 && args[0] === "--check") return true;
  throw new Error("Usage: node --import tsx devel/build_ribbon_icon_sprite.mjs [--check]");
}

//============================================

export function main() {
  const checkMode = parseCheckMode();
  const repoRoot = getRepoRoot();
  const spritePath = spritePathFor(repoRoot);
  const glyphIds = glyphIdsFromContract();
  const expectedSprite = renderSprite(glyphIds);
  if (checkMode) {
    if (!fs.existsSync(spritePath)) {
      throw new Error("Ribbon icon sprite is missing. Run devel/build_ribbon_icon_sprite.mjs.");
    }
    const committedSprite = fs.readFileSync(spritePath, "utf8");
    validateGeneratedSprite(committedSprite, glyphIds);
    if (committedSprite !== expectedSprite) {
      throw new Error("Ribbon icon sprite is stale. Run devel/build_ribbon_icon_sprite.mjs.");
    }
    console.log("Ribbon icon sprite is current.");
    return;
  }

  fs.mkdirSync(path.dirname(spritePath), { recursive: true });
  fs.writeFileSync(spritePath, expectedSprite);
  console.log(`Wrote ${path.relative(repoRoot, spritePath)}.`);
}

if (
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)
) {
  main();
}
