#!/usr/bin/env python3
"""Generate the browser-safe Question ID syntax contract from its Rust authority.

Run ``source source_me.sh && python3 devel/generate_question_id_contract.py``
to refresh the derived TypeScript contract. Add ``--check`` to fail when the
generated output is stale.
"""

import argparse
import json
import pathlib
import re


RUST_CONTRACT_PATH = pathlib.Path("crates/question_model/src/question_library.rs")
TYPESCRIPT_CONTRACT_PATH = pathlib.Path("generated/api/QuestionIdSyntaxContract.ts")
OWNERSHIP_HEADER = "// Generated by devel/generate_question_id_contract.py from the Rust model contract."
ALPHABET_PATTERN = re.compile(
	r'pub const QUESTION_ID_ALPHABET: &\[u8; 32\] = b"([0-9A-Z]+)";'
)
NUMBER_PATTERN = re.compile(
	r"pub const (QUESTION_ID_(?:IDENTIFIER_LENGTH|COMPACT_LENGTH|"
	r"CHECK_CHARACTER_COMPACT_INDEX|DISPLAY_HYPHEN_INDEX)): usize = (\d+);"
)
ALIASES_PATTERN = re.compile(
	r"pub const QUESTION_ID_NORMALIZATION_ALIASES: &\[\(char, char\)\] =\s*"
	r"&\[(.*?)\];",
	re.DOTALL,
)
ALIAS_ENTRY_PATTERN = re.compile(r"\('([A-Z])', '([0-9A-Z])'\)")


#============================================


def parse_arguments() -> argparse.Namespace:
	"""Read the one deliberately narrow generator operation."""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
	return parser.parse_args()


#============================================


def repository_root() -> pathlib.Path:
	"""Return the checkout root from this script's fixed repository location."""
	return pathlib.Path(__file__).resolve().parent.parent


#============================================


def rust_contract_values(root: pathlib.Path) -> tuple[str, dict[str, int], list[tuple[str, str]]]:
	"""Read the exact browser-safe syntax facts from the single Rust contract."""
	contract = (root / RUST_CONTRACT_PATH).read_text(encoding="utf-8")
	alphabet_match = ALPHABET_PATTERN.search(contract)
	if alphabet_match is None or len(alphabet_match.group(1)) != 32:
		raise ValueError("Question ID Rust contract must define one 32-character alphabet")
	numbers = {name: int(value) for name, value in NUMBER_PATTERN.findall(contract)}
	required_names = {
		"QUESTION_ID_IDENTIFIER_LENGTH",
		"QUESTION_ID_COMPACT_LENGTH",
		"QUESTION_ID_CHECK_CHARACTER_COMPACT_INDEX",
		"QUESTION_ID_DISPLAY_HYPHEN_INDEX",
	}
	if set(numbers) != required_names:
		raise ValueError("Question ID Rust contract must define every syntax length and position")
	if (
		numbers["QUESTION_ID_IDENTIFIER_LENGTH"] + 1 != numbers["QUESTION_ID_COMPACT_LENGTH"]
		or numbers["QUESTION_ID_CHECK_CHARACTER_COMPACT_INDEX"]
		!= numbers["QUESTION_ID_DISPLAY_HYPHEN_INDEX"]
		or numbers["QUESTION_ID_CHECK_CHARACTER_COMPACT_INDEX"] >= numbers["QUESTION_ID_COMPACT_LENGTH"]
	):
		raise ValueError("Question ID Rust syntax facts are internally inconsistent")
	aliases_match = ALIASES_PATTERN.search(contract)
	if aliases_match is None:
		raise ValueError("Question ID Rust contract must define normalization aliases")
	aliases = ALIAS_ENTRY_PATTERN.findall(aliases_match.group(1))
	if aliases != [("O", "0"), ("I", "1"), ("L", "1")]:
		raise ValueError("Question ID Rust normalization aliases must be the documented aliases")
	return alphabet_match.group(1), numbers, aliases


#============================================


def render_typescript(
	alphabet: str, numbers: dict[str, int], aliases: list[tuple[str, str]],
) -> str:
	"""Render syntax-only browser code with no HMAC or server authority."""
	alias_object = ", ".join(
		f"{json.dumps(alias)}: {json.dumps(normalized)}" for alias, normalized in aliases
	)
	return "\n".join([
		OWNERSHIP_HEADER,
		"// Do not edit by hand.",
		"",
		"/** Browser-safe syntax facts only; the server validates the HMAC check character. */",
		f"export const QUESTION_ID_ALPHABET = {json.dumps(alphabet)};",
		f"export const QUESTION_ID_IDENTIFIER_LENGTH = {numbers['QUESTION_ID_IDENTIFIER_LENGTH']};",
		f"export const QUESTION_ID_COMPACT_LENGTH = {numbers['QUESTION_ID_COMPACT_LENGTH']};",
		("export const QUESTION_ID_CHECK_CHARACTER_COMPACT_INDEX = "
		f"{numbers['QUESTION_ID_CHECK_CHARACTER_COMPACT_INDEX']};"),
		f"export const QUESTION_ID_DISPLAY_HYPHEN_INDEX = {numbers['QUESTION_ID_DISPLAY_HYPHEN_INDEX']};",
		f"export const QUESTION_ID_NORMALIZATION_ALIASES = {{ {alias_object} }} as const;",
		"",
		"/** Normalize documented Question ID entry syntax to canonical display form. */",
		"export function normalizeQuestionIdSyntax(value: string): string | null {",
		"  const trimmed = value.trim();",
		"  const hyphens = [...trimmed].filter((character) => character === \"-\").length;",
		"  if (",
		"    hyphens > 0 &&",
		"    (hyphens !== 1 ||",
		"      trimmed.length !== QUESTION_ID_COMPACT_LENGTH + 1 ||",
		"      trimmed[QUESTION_ID_DISPLAY_HYPHEN_INDEX] !== \"-\")",
		"  ) {",
		"    return null;",
		"  }",
		"  const compact = [...trimmed]",
		"    .filter((character) => character !== \"-\")",
		"    .map((character) => {",
		"      const uppercase = character.toUpperCase();",
		"      return QUESTION_ID_NORMALIZATION_ALIASES[",
		"        uppercase as keyof typeof QUESTION_ID_NORMALIZATION_ALIASES",
		"      ] ?? uppercase;",
		"    })",
		"    .join(\"\");",
		"  if (",
		"    compact.length !== QUESTION_ID_COMPACT_LENGTH ||",
		"    [...compact].some((character) => !QUESTION_ID_ALPHABET.includes(character))",
		"  ) {",
		"    return null;",
		"  }",
		"  return `${compact.slice(0, QUESTION_ID_DISPLAY_HYPHEN_INDEX)}-${compact.slice(",
		"    QUESTION_ID_DISPLAY_HYPHEN_INDEX,",
		"  )}`;",
		"}",
		"",
	])


#============================================


def write_or_check(root: pathlib.Path, output: str, check: bool) -> None:
	"""Write one fixed derived path, or identify it precisely when stale."""
	path = root / TYPESCRIPT_CONTRACT_PATH
	if check:
		if not path.is_file() or path.read_text(encoding="utf-8") != output:
			raise SystemExit(f"Question ID syntax contract is stale: {TYPESCRIPT_CONTRACT_PATH}")
		return
	if path.is_file() and not path.read_text(encoding="utf-8").startswith(OWNERSHIP_HEADER):
		raise SystemExit(f"refusing to overwrite non-Question-ID generator output: {TYPESCRIPT_CONTRACT_PATH}")
	path.write_text(output, encoding="utf-8")


#============================================


def main() -> None:
	"""Generate or check the sole derived browser syntax contract."""
	args = parse_arguments()
	root = repository_root()
	alphabet, numbers, aliases = rust_contract_values(root)
	write_or_check(root, render_typescript(alphabet, numbers, aliases), args.check)


if __name__ == "__main__":
	main()
