#!/usr/bin/env python3
"""Generate the exact browser Question-ID validator from its Rust authority.

Run source source_me.sh && python3 devel/generate_question_id_contract.py to
refresh the derived TypeScript contract. Add --check to fail when stale.
"""

import argparse
import json
import pathlib
import re


RUST_CONTRACT_PATH = pathlib.Path("crates/question_model/src/question_library.rs")
PUBLIC_ROUTE_CONTRACT_PATH = pathlib.Path("crates/question_model/src/public_route.rs")
TYPESCRIPT_CONTRACT_PATH = pathlib.Path("generated/api/QuestionIdSyntaxContract.ts")
OWNERSHIP_HEADER = "// Generated by devel/generate_question_id_contract.py from the Rust model contract."
ALPHABET_PATTERN = re.compile(
	r'pub const QUESTION_ID_ALPHABET: &\[u8; 32\] = b"([0-9A-Z]+)";'
)
NUMBER_PATTERN = re.compile(
	r"pub const (QUESTION_ID_(?:IDENTIFIER_LENGTH|CANONICAL_LENGTH|"
	r"CHECK_CHARACTER_INDEX|HYPHEN_INDEX)): usize = (\d+);"
)
PUBLIC_ID_LENGTH_PATTERN = re.compile(
	r"pub const PUBLIC_ID_RANDOM_LENGTH: usize = (\d+);"
)
PUBLIC_ID_PATTERN = re.compile(
	r'impl_public_id!\(\s*(\w+),\s*"([A-Z]+)",\s*"([A-Z]+)",\s*"[^"]+"\s*\);',
	re.DOTALL,
)


#============================================


def parse_arguments() -> argparse.Namespace:
	"""Read the one deliberately narrow generator operation."""
	parser = argparse.ArgumentParser(description=__doc__)
	parser.add_argument("--check", action="store_true", help="fail when generated output is stale")
	return parser.parse_args()


#============================================


def repository_root() -> pathlib.Path:
	"""Return the checkout root from this script's fixed repository location."""
	return pathlib.Path(__file__).resolve().parent.parent


#============================================


def rust_contract_values(
	root: pathlib.Path,
) -> tuple[str, dict[str, int], list[tuple[str, str]]]:
	"""Read the browser-safe exact-ID facts from the single Rust contract."""
	contract = (root / RUST_CONTRACT_PATH).read_text(encoding="utf-8")
	alphabet_match = ALPHABET_PATTERN.search(contract)
	if alphabet_match is None or len(alphabet_match.group(1)) != 32:
		raise ValueError("Question ID Rust contract must define one 32-character alphabet")
	numbers = {name: int(value) for name, value in NUMBER_PATTERN.findall(contract)}
	required_names = {
		"QUESTION_ID_IDENTIFIER_LENGTH",
		"QUESTION_ID_CANONICAL_LENGTH",
		"QUESTION_ID_CHECK_CHARACTER_INDEX",
		"QUESTION_ID_HYPHEN_INDEX",
	}
	if set(numbers) != required_names:
		raise ValueError("Question ID Rust contract must define every exact-ID position and length")
	if (
		numbers["QUESTION_ID_IDENTIFIER_LENGTH"] + 2
		!= numbers["QUESTION_ID_CANONICAL_LENGTH"]
		or numbers["QUESTION_ID_CHECK_CHARACTER_INDEX"]
		!= numbers["QUESTION_ID_HYPHEN_INDEX"] + 1
		or numbers["QUESTION_ID_CHECK_CHARACTER_INDEX"]
		>= numbers["QUESTION_ID_CANONICAL_LENGTH"]
	):
		raise ValueError("Question ID Rust syntax facts are internally inconsistent")
	public_route = (root / PUBLIC_ROUTE_CONTRACT_PATH).read_text(encoding="utf-8")
	id_length_match = PUBLIC_ID_LENGTH_PATTERN.search(public_route)
	if id_length_match is None:
		raise ValueError("public-route Rust contract must define one random-character length")
	if int(id_length_match.group(1)) != numbers["QUESTION_ID_IDENTIFIER_LENGTH"]:
		raise ValueError("all approved public IDs must use the Question-ID random-character length")
	public_ids = PUBLIC_ID_PATTERN.findall(public_route)
	required_ids = [
		("BlueprintCourseId", "BP", "BP"),
		("CourseInstanceId", "CI", "CI"),
		("AssessmentId", "A", "A"),
		("AccountId", "U", "U"),
	]
	if sorted(public_ids) != sorted(required_ids):
		raise ValueError("public-route Rust contract must define only approved checksum public IDs")
	families = [
		(name.removesuffix("Id")[0].lower() + name.removesuffix("Id")[1:], prefix)
		for name, prefix, _checksum_prefix in required_ids
	]
	return alphabet_match.group(1), numbers, families


#============================================


def render_typescript(
	alphabet: str, numbers: dict[str, int], id_families: list[tuple[str, str]],
) -> str:
	"""Render exact browser validation with the public one-block SHA-256 calculation."""
	round_constants = ", ".join([
		"0x428a2f98", "0x71374491", "0xb5c0fbcf", "0xe9b5dba5",
		"0x3956c25b", "0x59f111f1", "0x923f82a4", "0xab1c5ed5",
		"0xd807aa98", "0x12835b01", "0x243185be", "0x550c7dc3",
		"0x72be5d74", "0x80deb1fe", "0x9bdc06a7", "0xc19bf174",
		"0xe49b69c1", "0xefbe4786", "0x0fc19dc6", "0x240ca1cc",
		"0x2de92c6f", "0x4a7484aa", "0x5cb0a9dc", "0x76f988da",
		"0x983e5152", "0xa831c66d", "0xb00327c8", "0xbf597fc7",
		"0xc6e00bf3", "0xd5a79147", "0x06ca6351", "0x14292967",
		"0x27b70a85", "0x2e1b2138", "0x4d2c6dfc", "0x53380d13",
		"0x650a7354", "0x766a0abb", "0x81c2c92e", "0x92722c85",
		"0xa2bfe8a1", "0xa81a664b", "0xc24b8b70", "0xc76c51a3",
		"0xd192e819", "0xd6990624", "0xf40e3585", "0x106aa070",
		"0x19a4c116", "0x1e376c08", "0x2748774c", "0x34b0bcb5",
		"0x391c0cb3", "0x4ed8aa4a", "0x5b9cca4f", "0x682e6ff3",
		"0x748f82ee", "0x78a5636f", "0x84c87814", "0x8cc70208",
		"0x90befffa", "0xa4506ceb", "0xbef9a3f7", "0xc67178f2",
	])
	family_lines = [
		f"  {json.dumps(family)}: {json.dumps(prefix)}," for family, prefix in id_families
	]
	return "\n".join([
		OWNERSHIP_HEADER,
		"// Do not edit by hand.",
		"",
		"/** Exact public-ID facts shared with the Rust model. */",
		f"export const QUESTION_ID_ALPHABET = {json.dumps(alphabet)};",
		f"export const QUESTION_ID_IDENTIFIER_LENGTH = {numbers['QUESTION_ID_IDENTIFIER_LENGTH']};",
		f"export const QUESTION_ID_CANONICAL_LENGTH = {numbers['QUESTION_ID_CANONICAL_LENGTH']};",
		("export const QUESTION_ID_CHECK_CHARACTER_INDEX = "
		f"{numbers['QUESTION_ID_CHECK_CHARACTER_INDEX']};"),
		f"export const QUESTION_ID_HYPHEN_INDEX = {numbers['QUESTION_ID_HYPHEN_INDEX']};",
		"",
		"const SHA256_ROUND_CONSTANTS = new Uint32Array([",
		f"  {round_constants},",
		"]);",
		"",
		"function rotateRight(value: number, bits: number): number {",
		"  return (value >>> bits) | (value << (32 - bits));",
		"}",
		"",
		"function arrayValue(values: Uint8Array | Uint32Array, index: number): number {",
		"  return values[index] ?? 0;",
		"}",
		"",
		"/** Return SHA-256 byte zero for one short ASCII checksum input. */",
		"function sha256FirstByte(ascii: string): number {",
		"  const block = new Uint8Array(64);",
		"  for (let index = 0; index < ascii.length; index += 1) {",
		"    block[index] = ascii.charCodeAt(index);",
		"  }",
		"  block[ascii.length] = 0x80;",
		"  block[63] = ascii.length * 8;",
		"  const words = new Uint32Array(64);",
		"  for (let index = 0; index < 16; index += 1) {",
		"    const offset = index * 4;",
		"    words[index] =",
		"      (arrayValue(block, offset) << 24) |",
		"      (arrayValue(block, offset + 1) << 16) |",
		"      (arrayValue(block, offset + 2) << 8) |",
		"      arrayValue(block, offset + 3);",
		"  }",
		"  for (let index = 16; index < 64; index += 1) {",
		"    const sigma0 =",
		"      rotateRight(arrayValue(words, index - 15), 7) ^",
		"      rotateRight(arrayValue(words, index - 15), 18) ^",
		"      (arrayValue(words, index - 15) >>> 3);",
		"    const sigma1 =",
		"      rotateRight(arrayValue(words, index - 2), 17) ^",
		"      rotateRight(arrayValue(words, index - 2), 19) ^",
		"      (arrayValue(words, index - 2) >>> 10);",
		"    words[index] = (",
		"      arrayValue(words, index - 16) + sigma0 + arrayValue(words, index - 7) + sigma1",
		"    ) >>> 0;",
		"  }",
		"  let a = 0x6a09e667;",
		"  let b = 0xbb67ae85;",
		"  let c = 0x3c6ef372;",
		"  let d = 0xa54ff53a;",
		"  let e = 0x510e527f;",
		"  let f = 0x9b05688c;",
		"  let g = 0x1f83d9ab;",
		"  let h = 0x5be0cd19;",
		"  for (let index = 0; index < 64; index += 1) {",
		"    const sigma1 = rotateRight(e, 6) ^ rotateRight(e, 11) ^ rotateRight(e, 25);",
		"    const choose = (e & f) ^ (~e & g);",
		"    const temporary1 = (",
		"      h + sigma1 + choose + arrayValue(SHA256_ROUND_CONSTANTS, index) + arrayValue(words, index)",
		"    ) >>> 0;",
		"    const sigma0 = rotateRight(a, 2) ^ rotateRight(a, 13) ^ rotateRight(a, 22);",
		"    const majority = (a & b) ^ (a & c) ^ (b & c);",
		"    const temporary2 = (sigma0 + majority) >>> 0;",
		"    h = g;",
		"    g = f;",
		"    f = e;",
		"    e = (d + temporary1) >>> 0;",
		"    d = c;",
		"    c = b;",
		"    b = a;",
		"    a = (temporary1 + temporary2) >>> 0;",
		"  }",
		"  return ((0x6a09e667 + a) >>> 24) & 0xff;",
		"}",
		"",
		"function checksumCharacter(input: string): string {",
		"  return QUESTION_ID_ALPHABET.charAt(sha256FirstByte(input) >>> 3);",
		"}",
		"",
		"/** Exact prefixes for the only approved contiguous public-ID families. */",
		"export const CANONICAL_PUBLIC_ID_FAMILIES = {",
		*family_lines,
		"} as const;",
		"export type CanonicalPublicIdFamily =",
		"  keyof typeof CANONICAL_PUBLIC_ID_FAMILIES;",
		"",
		"/** Validate one already-canonical Question or Pool ID without changing it. */",
		"export function isCanonicalQuestionId(value: string): boolean {",
		"  if (",
		"    value.length !== QUESTION_ID_CANONICAL_LENGTH ||",
		"    value.charAt(QUESTION_ID_HYPHEN_INDEX) !== \"-\"",
		"  ) {",
		"    return false;",
		"  }",
		"  const checksumInput =",
		"    value.slice(0, QUESTION_ID_HYPHEN_INDEX) +",
		"    value.slice(QUESTION_ID_CHECK_CHARACTER_INDEX + 1);",
		"  if (",
		"    checksumInput.length !== QUESTION_ID_IDENTIFIER_LENGTH ||",
		"    [...checksumInput].some((character) => !QUESTION_ID_ALPHABET.includes(character)) ||",
		"    !QUESTION_ID_ALPHABET.includes(value.charAt(QUESTION_ID_CHECK_CHARACTER_INDEX))",
		"  ) {",
		"    return false;",
		"  }",
		"  return value.charAt(QUESTION_ID_CHECK_CHARACTER_INDEX) === checksumCharacter(checksumInput);",
		"}",
		"",
		"/** Return the exact input only when it is a canonical checksum-valid ID. */",
		"export function validateCanonicalQuestionIdSyntax(value: string): string | null {",
		"  return isCanonicalQuestionId(value) ? value : null;",
		"}",
		"",
		"/** Validate one exact contiguous public ID without changing it. */",
		"export function isCanonicalPublicId(",
		"  family: CanonicalPublicIdFamily,",
		"  value: string,",
		"): boolean {",
		"  const prefix = CANONICAL_PUBLIC_ID_FAMILIES[family];",
		"  if (!value.startsWith(prefix)) return false;",
		"  const suffix = value.slice(prefix.length);",
		"  if (",
		"    suffix.length !== QUESTION_ID_IDENTIFIER_LENGTH + 1 ||",
		"    [...suffix].some((character) => !QUESTION_ID_ALPHABET.includes(character))",
		"  ) {",
		"    return false;",
		"  }",
		"  const checksumInput = prefix + suffix.slice(0, QUESTION_ID_IDENTIFIER_LENGTH);",
		"  return suffix.charAt(QUESTION_ID_IDENTIFIER_LENGTH) === checksumCharacter(checksumInput);",
		"}",
		"",
		"/** Return the exact input only when it is one canonical checksum-valid public ID. */",
		"export function validateCanonicalPublicId(",
		"  family: CanonicalPublicIdFamily,",
		"  value: string,",
		"): string | null {",
		"  return isCanonicalPublicId(family, value) ? value : null;",
		"}",
		"",
	])


#============================================


def write_or_check(root: pathlib.Path, output: str, check: bool) -> None:
	"""Write one fixed derived path, or identify it precisely when stale."""
	path = root / TYPESCRIPT_CONTRACT_PATH
	if check:
		if not path.is_file() or path.read_text(encoding="utf-8") != output:
			raise SystemExit(f"Question ID syntax contract is stale: {TYPESCRIPT_CONTRACT_PATH}")
		return
	if path.is_file() and not path.read_text(encoding="utf-8").startswith(OWNERSHIP_HEADER):
		raise SystemExit(f"refusing to overwrite non-Question-ID generator output: {TYPESCRIPT_CONTRACT_PATH}")
	path.write_text(output, encoding="utf-8")


#============================================


def main() -> None:
	"""Generate or check the sole derived browser syntax contract."""
	args = parse_arguments()
	root = repository_root()
	alphabet, numbers, reference_families = rust_contract_values(root)
	write_or_check(root, render_typescript(alphabet, numbers, reference_families), args.check)


if __name__ == "__main__":
	main()
