#!/usr/bin/env node
/**
 * Copies the current lockfile-installed RDKit browser pair into PLE-owned
 * assets and generates the closed server registry. This is deliberately not a
 * package resolver, CDN client, or generic static-asset builder.
 */

import { copyFile, lstat, mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const packageName = "@rdkit/rdkit";
const packageRoot = join(root, "node_modules", "@rdkit", "rdkit");
const sourceRoot = join(packageRoot, "dist");
const assetRoot = join(root, "assets", "author-content-dependencies", "rdkit");
const registryPath = join(
  root,
  "crates",
  "server",
  "src",
  "author_content_dependency_registry_generated.rs",
);
const files = [
  ["RDKit_minimal.js", "application/javascript; charset=utf-8"],
  ["RDKit_minimal.wasm", "application/wasm"],
];

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function normalizedVersion(value) {
  const match = /^(\d+)\.(\d+)\.(\d+)(.*)$/.exec(value);
  if (!match) throw new Error("RDKit package version is not a three-part release version");
  return `${Number(match[1])}.${Number(match[2])}.${Number(match[3])}${match[4]}`;
}

async function readRegularFile(path, purpose) {
  const metadata = await lstat(path);
  if (!metadata.isFile()) throw new Error(`${purpose} must be a regular file`);
  return readFile(path);
}

function registry(entries) {
  const values = entries
    .map(
      ({ name, digest, mediaType }) => `    ReviewedAuthorContentRuntimeFile {
        file_name: ${JSON.stringify(name)},
        sha256: ${JSON.stringify(digest)},
        media_type: ${JSON.stringify(mediaType)},
    },`,
    )
    .join("\n");
  return `// @generated by devel/sync_author_content_dependency.mjs; do not edit.
// The root npm lockfile supplies the current reviewed local RDKit bytes. No
// author URL, package version, CDN, or historical runtime catalog is authority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ReviewedAuthorContentRuntimeFile {
    pub(crate) file_name: &'static str,
    pub(crate) sha256: &'static str,
    pub(crate) media_type: &'static str,
}

pub(crate) const RDKIT_FILES: &[ReviewedAuthorContentRuntimeFile] = &[
${values}
];
`;
}

async function input() {
  const [rootPackage, lockfile, packageMetadata] = await Promise.all([
    readFile(join(root, "package.json"), "utf8").then(JSON.parse),
    readFile(join(root, "package-lock.json"), "utf8").then(JSON.parse),
    readFile(join(packageRoot, "package.json"), "utf8").then(JSON.parse),
  ]);
  const declared = rootPackage.devDependencies?.[packageName];
  const locked = lockfile.packages?.["node_modules/@rdkit/rdkit"];
  const expectedResolved = locked
    ? `https://registry.npmjs.org/@rdkit/rdkit/-/rdkit-${locked.version}.tgz`
    : undefined;
  if (
    typeof declared !== "string" ||
    !declared.startsWith(">=") ||
    !locked ||
    normalizedVersion(locked.version) !== normalizedVersion(packageMetadata.version) ||
    locked.resolved !== expectedResolved ||
    typeof locked.integrity !== "string" ||
    !locked.integrity.startsWith("sha512-") ||
    locked.license !== "BSD-3-Clause" ||
    packageMetadata.license !== "BSD-3-Clause"
  ) {
    throw new Error("root npm dependency, lockfile, and installed RDKit metadata disagree");
  }
  return Promise.all(
    files.map(async ([name, mediaType]) => {
      const bytes = await readRegularFile(join(sourceRoot, name), `installed RDKit ${name}`);
      return { name, mediaType, bytes, digest: sha256(bytes) };
    }),
  );
}

async function check(entries) {
  const directoryEntries = await readdir(assetRoot, { withFileTypes: true });
  const names = directoryEntries.map((entry) => entry.name).sort();
  if (
    JSON.stringify(names) !== JSON.stringify(files.map(([name]) => name).sort()) ||
    directoryEntries.some((entry) => !entry.isFile())
  ) {
    throw new Error("PLE-owned RDKit asset directory has an unexpected shape");
  }
  for (const entry of entries) {
    const actual = await readRegularFile(
      join(assetRoot, entry.name),
      `PLE-owned RDKit ${entry.name}`,
    );
    if (sha256(actual) !== entry.digest) throw new Error(`local asset differs: ${entry.name}`);
  }
  const actualRegistry = await readFile(registryPath, "utf8");
  if (actualRegistry !== registry(entries)) throw new Error("generated RDKit registry differs");
}

const checkOnly = process.argv.slice(2).join(" ") === "--check";
if (!checkOnly && process.argv.length !== 2) {
  throw new Error("usage: node devel/sync_author_content_dependency.mjs [--check]");
}
const entries = await input();
if (!checkOnly) {
  await mkdir(assetRoot, { recursive: true });
  await Promise.all(
    entries.map((entry) => copyFile(join(sourceRoot, entry.name), join(assetRoot, entry.name))),
  );
  await writeFile(registryPath, registry(entries), "utf8");
}
await check(entries);
console.log("current lockfile-installed RDKit assets and registry are synchronized");
