// @generated by devel/sync_author_content_dependency.mjs; do not edit.
// The root npm lockfile supplies the current reviewed local RDKit bytes. No
// author URL, package version, CDN, or historical runtime catalog is authority.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct ReviewedAuthorContentRuntimeFile {
    pub(crate) file_name: &'static str,
    pub(crate) sha256: &'static str,
    pub(crate) media_type: &'static str,
}

pub(crate) const RDKIT_FILES: &[ReviewedAuthorContentRuntimeFile] = &[
    ReviewedAuthorContentRuntimeFile {
        file_name: "RDKit_minimal.js",
        sha256: "25ea1529b8eeb106ac1f3acb7c5d338a90533248c6223614574fefd14fee772f",
        media_type: "application/javascript; charset=utf-8",
    },
    ReviewedAuthorContentRuntimeFile {
        file_name: "RDKit_minimal.wasm",
        sha256: "f5981af4cf5bdcef861ffdf7410330bf9887f1195e39fbf9901b3a2f134ace2e",
        media_type: "application/wasm",
    },
];
