//! Bounded public delivery for the renderer's two asset namespaces.
//!
//! The renderer emits only `webwork2_files` and `pg_files` URLs in an embed
//! document. This route forwards those static/generated bytes from the private
//! renderer without accepting a renderer address, redirect, query, or any
//! other URL shape from the browser.

use std::time::Duration;

use axum::{
    Router,
    body::Body,
    extract::{OriginalUri, Path, State},
    http::{
        HeaderValue, StatusCode,
        header::{CACHE_CONTROL, CONTENT_TYPE, LOCATION},
    },
    response::{IntoResponse, Response},
    routing::{MethodFilter, on},
};
use reqwest::{Client, Url, redirect::Policy};

const MAX_ASSET_BYTES: usize = 8 * 1024 * 1024;
const ASSET_ROUTE: &str = "/api/webwork-assets/";

#[derive(Clone)]
pub(crate) struct WebworkAssetProxyConfig {
    renderer_base: Url,
    deadline: Duration,
}

impl WebworkAssetProxyConfig {
    pub(crate) fn new(renderer_base: &str, deadline: Duration) -> Result<Self, String> {
        let renderer_base = Url::parse(renderer_base)
            .map_err(|_| "WeBWorK renderer asset base must be an absolute HTTP(S) origin")?;
        if !matches!(renderer_base.scheme(), "http" | "https")
            || renderer_base.host_str().is_none()
            || !renderer_base.username().is_empty()
            || renderer_base.password().is_some()
            || renderer_base.query().is_some()
            || renderer_base.fragment().is_some()
            || renderer_base.path() != "/"
            || deadline.is_zero()
        {
            return Err(
                "WeBWorK renderer asset base must be a credential-free HTTP(S) origin with a positive deadline"
                    .to_string(),
            );
        }
        Ok(Self {
            renderer_base,
            deadline,
        })
    }
}

#[derive(Clone)]
struct WebworkAssetProxyState {
    client: Client,
    renderer_base: Url,
}

/// Registers the intentionally public renderer-asset route. Public asset
/// namespace validation established that these two namespaces contain only
/// browser-safe renderer assets.
pub(crate) fn webwork_asset_proxy_router(
    config: WebworkAssetProxyConfig,
) -> Result<Router, String> {
    let client = Client::builder()
        .connect_timeout(config.deadline)
        .timeout(config.deadline)
        .redirect(Policy::none())
        .build()
        .map_err(|_| "could not construct WeBWorK renderer asset client".to_string())?;
    Ok(Router::new()
        .route(
            "/api/webwork-assets/{prefix}/{*path}",
            // Axum otherwise dispatches HEAD through a GET handler. Register
            // it explicitly so this public asset boundary remains GET-only.
            on(MethodFilter::GET, get_asset).on(MethodFilter::HEAD, method_not_allowed),
        )
        .with_state(WebworkAssetProxyState {
            client,
            renderer_base: config.renderer_base,
        }))
}

async fn get_asset(
    State(state): State<WebworkAssetProxyState>,
    OriginalUri(uri): OriginalUri,
    Path((prefix, _path)): Path<(String, String)>,
) -> Response {
    let raw_path =
        match valid_raw_asset_path(uri.path_and_query().map(|value| value.as_str()), &prefix) {
            Some(value) => value,
            None => return concealed(),
        };
    let target = match upstream_url(&state.renderer_base, raw_path) {
        Some(value) => value,
        None => return concealed(),
    };
    let response = match state.client.get(target).send().await {
        Ok(value) => value,
        Err(_) => return unavailable(),
    };
    if response.status().is_redirection() || response.headers().contains_key(LOCATION) {
        return concealed();
    }
    if response.status() == reqwest::StatusCode::NOT_FOUND || response.status().is_client_error() {
        return concealed();
    }
    if response.status().is_server_error() || !response.status().is_success() {
        return unavailable();
    }
    let content_type = match safe_content_type(response.headers().get(CONTENT_TYPE)) {
        Some(value) => value,
        None => return concealed(),
    };
    if response
        .content_length()
        .is_some_and(|length| length > MAX_ASSET_BYTES as u64)
    {
        return concealed();
    }
    let bytes = match read_bounded(response).await {
        Some(value) => value,
        None => return concealed(),
    };
    asset_response(prefix.as_str(), content_type, bytes)
}

/// Validates the un-decoded browser path before the trusted renderer URL is
/// built. The route extractor is intentionally not the authority here because
/// it normalizes percent-encoded path data.
fn valid_raw_asset_path<'a>(raw: Option<&'a str>, prefix: &str) -> Option<&'a str> {
    if !matches!(prefix, "webwork2_files" | "pg_files") {
        return None;
    }
    let raw = raw?;
    if raw.contains('?') || raw.contains(['\\', '\0']) {
        return None;
    }
    let required_start = format!("{ASSET_ROUTE}{prefix}/");
    let path = raw.strip_prefix(&required_start)?;
    if path.is_empty()
        || path.starts_with('/')
        || raw.contains("//")
        || contains_encoded_escape(raw)
    {
        return None;
    }
    if path.split('/').any(|segment| {
        segment.is_empty() || matches!(segment, "." | "..") || segment.contains(['\\', '\0'])
    }) {
        return None;
    }
    Some(&raw[ASSET_ROUTE.len()..])
}

fn contains_encoded_escape(value: &str) -> bool {
    let lower = value.to_ascii_lowercase();
    ["%00", "%2e", "%2f", "%5c"]
        .iter()
        .any(|needle| lower.contains(needle))
}

/// Combines only a validated relative asset path with the private origin.
fn upstream_url(base: &Url, raw_path: &str) -> Option<Url> {
    if raw_path.starts_with('/') || raw_path.contains('?') || raw_path.contains('#') {
        return None;
    }
    Url::parse(&format!("{}{}", base.as_str(), raw_path)).ok()
}

fn safe_content_type(value: Option<&HeaderValue>) -> Option<HeaderValue> {
    let value = value?.to_str().ok()?;
    let media_type = value.split(';').next()?.trim().to_ascii_lowercase();
    let allowed = matches!(
        media_type.as_str(),
        "application/javascript"
            | "application/x-javascript"
            | "text/javascript"
            | "text/css"
            | "image/png"
            | "image/jpeg"
            | "image/gif"
            | "image/svg+xml"
            | "image/webp"
            | "font/woff"
            | "font/woff2"
            | "application/font-woff"
            | "application/vnd.ms-fontobject"
    );
    allowed.then(|| HeaderValue::from_str(value).ok()).flatten()
}

async fn read_bounded(mut response: reqwest::Response) -> Option<Vec<u8>> {
    let mut bytes = Vec::new();
    while let Some(chunk) = response.chunk().await.ok()? {
        if bytes.len().checked_add(chunk.len())? > MAX_ASSET_BYTES {
            return None;
        }
        bytes.extend_from_slice(&chunk);
    }
    Some(bytes)
}

fn asset_response(prefix: &str, content_type: HeaderValue, bytes: Vec<u8>) -> Response {
    let cache_control = if prefix == "webwork2_files" {
        "public, max-age=86400"
    } else {
        "no-store"
    };
    let mut response = Response::new(Body::from(bytes));
    let headers = response.headers_mut();
    headers.insert(CONTENT_TYPE, content_type);
    headers.insert(CACHE_CONTROL, HeaderValue::from_static(cache_control));
    // This explicit same-origin CORP policy matches the dynamic API default
    // without changing that default for unrelated routes.
    headers.insert(
        "cross-origin-resource-policy",
        HeaderValue::from_static("same-origin"),
    );
    response
}

fn concealed() -> Response {
    StatusCode::NOT_FOUND.into_response()
}

async fn method_not_allowed() -> Response {
    StatusCode::METHOD_NOT_ALLOWED.into_response()
}

fn unavailable() -> Response {
    StatusCode::SERVICE_UNAVAILABLE.into_response()
}

#[cfg(test)]
mod tests {
    use axum::{
        body::Body,
        http::{Request, Response as HttpResponse},
        routing::any,
    };
    use tower::ServiceExt;

    use super::*;

    async fn proxy() -> Router {
        let upstream = Router::new().route("/{*path}", any(upstream_response));
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
            .await
            .expect("test listener");
        let address = listener.local_addr().expect("test address");
        tokio::spawn(async move {
            axum::serve(listener, upstream)
                .await
                .expect("test upstream server");
        });
        webwork_asset_proxy_router(
            WebworkAssetProxyConfig::new(&format!("http://{address}/"), Duration::from_secs(2))
                .expect("valid test proxy config"),
        )
        .expect("test asset proxy router")
    }

    async fn upstream_response(uri: axum::http::Uri) -> HttpResponse<Body> {
        match uri.path() {
            "/webwork2_files/js/app.js" => {
                response("application/javascript", b"window.pg = 1;".to_vec())
            }
            "/pg_files/tmp/plot.png" => response("image/png", vec![1, 2, 3]),
            "/webwork2_files/redirect" => {
                let mut response = StatusCode::FOUND.into_response();
                response
                    .headers_mut()
                    .insert(LOCATION, HeaderValue::from_static("/elsewhere"));
                response
            }
            "/webwork2_files/too-big.js" => {
                response("application/javascript", vec![0; MAX_ASSET_BYTES + 1])
            }
            "/webwork2_files/page.html" => response("text/html", b"<html>".to_vec()),
            _ => StatusCode::NOT_FOUND.into_response(),
        }
    }

    fn response(content_type: &'static str, body: Vec<u8>) -> HttpResponse<Body> {
        let mut response = HttpResponse::new(Body::from(body));
        response
            .headers_mut()
            .insert(CONTENT_TYPE, HeaderValue::from_static(content_type));
        response
    }

    #[tokio::test]
    async fn forwards_only_allowed_renderer_assets_with_selected_cache_and_corp() {
        let app = proxy().await;
        let static_asset = app
            .clone()
            .oneshot(
                Request::get("/api/webwork-assets/webwork2_files/js/app.js")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(static_asset.status(), StatusCode::OK);
        assert_eq!(
            static_asset.headers()[CONTENT_TYPE],
            "application/javascript"
        );
        assert_eq!(
            static_asset.headers()[CACHE_CONTROL],
            "public, max-age=86400"
        );
        assert_eq!(
            static_asset.headers()["cross-origin-resource-policy"],
            "same-origin"
        );

        let generated = app
            .oneshot(
                Request::get("/api/webwork-assets/pg_files/tmp/plot.png")
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(generated.status(), StatusCode::OK);
        assert_eq!(generated.headers()[CACHE_CONTROL], "no-store");
    }

    #[tokio::test]
    async fn conceals_invalid_paths_redirects_oversize_and_unsafe_media() {
        let app = proxy().await;
        for path in [
            "/api/webwork-assets/webwork2_files/js/app.js?x=1",
            "/api/webwork-assets/webwork2_files/%2e%2e/secret.js",
            "/api/webwork-assets/webwork2_files/redirect",
            "/api/webwork-assets/webwork2_files/too-big.js",
            "/api/webwork-assets/webwork2_files/page.html",
        ] {
            let response = app
                .clone()
                .oneshot(Request::get(path).body(Body::empty()).unwrap())
                .await
                .unwrap();
            assert_eq!(response.status(), StatusCode::NOT_FOUND, "{path}");
        }
    }

    #[test]
    fn conceals_raw_path_boundary_refusals() {
        let raw_nul = format!("{ASSET_ROUTE}webwork2_files/js\0app.js");
        let cases = [
            (
                "empty path",
                "/api/webwork-assets/webwork2_files/",
                "webwork2_files",
            ),
            (
                "dot segment",
                "/api/webwork-assets/webwork2_files/./app.js",
                "webwork2_files",
            ),
            (
                "dot-dot segment",
                "/api/webwork-assets/webwork2_files/../secret.js",
                "webwork2_files",
            ),
            (
                "repeated separator",
                "/api/webwork-assets/webwork2_files/js//app.js",
                "webwork2_files",
            ),
            (
                "backslash",
                "/api/webwork-assets/webwork2_files/js\\app.js",
                "webwork2_files",
            ),
            ("NUL", raw_nul.as_str(), "webwork2_files"),
            (
                "encoded slash",
                "/api/webwork-assets/webwork2_files/js%2fapp.js",
                "webwork2_files",
            ),
            (
                "encoded backslash",
                "/api/webwork-assets/webwork2_files/js%5capp.js",
                "webwork2_files",
            ),
            (
                "encoded NUL",
                "/api/webwork-assets/webwork2_files/js%00app.js",
                "webwork2_files",
            ),
            (
                "encoded traversal",
                "/api/webwork-assets/webwork2_files/%2e%2e/secret.js",
                "webwork2_files",
            ),
            (
                "unexpected prefix",
                "/api/webwork-assets/other_files/js/app.js",
                "other_files",
            ),
        ];

        for (name, raw, prefix) in cases {
            assert!(
                valid_raw_asset_path(Some(raw), prefix).is_none(),
                "{name} must not select an upstream asset"
            );
            assert_eq!(
                concealed().status(),
                StatusCode::NOT_FOUND,
                "{name} must remain concealed"
            );
        }
    }

    #[tokio::test]
    async fn route_accepts_only_get() {
        let app = proxy().await;
        for request in [
            Request::head("/api/webwork-assets/webwork2_files/js/app.js")
                .body(Body::empty())
                .unwrap(),
            Request::post("/api/webwork-assets/webwork2_files/js/app.js")
                .body(Body::empty())
                .unwrap(),
        ] {
            let response = app.clone().oneshot(request).await.unwrap();
            assert_eq!(response.status(), StatusCode::METHOD_NOT_ALLOWED);
        }
    }
}
