//! External Tool Grading Contexts, launch-session authentication, and verified grades.

use base64::Engine as _;

use objects::{ObjectStoreError, QuestionSourceResolutionError};
use question_model::generation::QuestionSeed;
use question_model::{
    GradingResult, QuestionAttemptId, QuestionRevisionReference, QuestionTitleError,
};

/// Fresh, 256-bit server challenge for one External Tool Launch Session.
///
/// The server obtains these bytes from its CSPRNG. The value is opaque to
/// browser code and logs, but the contracted provider echoes its encoded form
/// in a signed result so the server can reject a replayed launch.
#[derive(Clone, PartialEq, Eq)]
pub struct ExternalToolLaunchChallenge(pub(crate) [u8; 32]);

impl ExternalToolLaunchChallenge {
    /// Wraps one non-placeholder value generated by the server CSPRNG.
    pub fn from_server_random(value: [u8; 32]) -> Result<Self, ImathasAdapterError> {
        if value.iter().all(|byte| *byte == 0) {
            return Err(ImathasAdapterError::InvalidExternalToolLaunchSessionAuthentication);
        }
        Ok(Self(value))
    }

    pub(crate) fn encoded(&self) -> String {
        base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(self.0)
    }
}

impl std::fmt::Debug for ExternalToolLaunchChallenge {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str("ExternalToolLaunchChallenge(REDACTED)")
    }
}

/// Opaque External Tool Launch Session authentication. It is deliberately neither serializable
/// nor constructible from browser data. The server derives it only through the
/// complete [`ExternalToolLaunchSessionAuthenticationCodec`](crate::external_question_provider::ExternalToolLaunchSessionAuthenticationCodec).
#[derive(Clone, PartialEq, Eq)]
pub struct ExternalToolLaunchSessionAuthentication(pub(crate) String);

/// Exact server-owned grade identity persisted alongside its idempotency row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExternalToolGradingContext {
    pub attempt: QuestionAttemptId,
    pub question_revision: QuestionRevisionReference,
    pub seed: QuestionSeed,
}

impl std::fmt::Debug for ExternalToolLaunchSessionAuthentication {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ExternalToolLaunchSessionAuthentication(REDACTED)")
    }
}

/// Authenticated provider verdict. The fields are private and this type has no
/// serde implementation, so an HTTP/browser payload cannot deserialize into it.
#[derive(Clone, PartialEq)]
pub struct VerifiedProviderGrade {
    pub(crate) result: GradingResult,
    pub(crate) attempt: QuestionAttemptId,
    pub(crate) question_revision: QuestionRevisionReference,
    pub(crate) seed: QuestionSeed,
    pub(crate) launch_session_authentication: String,
}

impl std::fmt::Debug for VerifiedProviderGrade {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("VerifiedProviderGrade")
            .field("result", &self.result)
            .field("attempt", &self.attempt)
            .field("question_revision", &self.question_revision)
            .field("seed", &self.seed)
            .field("launch_session_authentication", &"REDACTED")
            .finish()
    }
}

impl VerifiedProviderGrade {
    /// Server-only verified result; this type is non-serde and can only be
    /// obtained from the sealed contracted verifier.
    pub fn result(&self) -> GradingResult {
        self.result
    }

    /// Exact identity authenticated by the provider verifier.
    pub fn binding(&self) -> ExternalToolGradingContext {
        ExternalToolGradingContext {
            attempt: self.attempt,
            question_revision: self.question_revision.clone(),
            seed: self.seed,
        }
    }

    /// Provider implementations use this only after their signature/audience/
    /// expiry/challenge verification succeeds.
    #[cfg(test)]
    pub(crate) fn verified(
        result: GradingResult,
        attempt: QuestionAttemptId,
        question_revision: QuestionRevisionReference,
        seed: QuestionSeed,
        launch_session_authentication: &ExternalToolLaunchSessionAuthentication,
    ) -> Self {
        Self {
            result,
            attempt,
            question_revision,
            seed,
            launch_session_authentication: launch_session_authentication.0.clone(),
        }
    }

    /// The scored-embed verifier is the only production constructor. Its
    /// result token has already passed signature, expiry, exact question, and
    /// single-use server-ledger checks before this sealed grade exists.
    pub(crate) fn from_scored_embed(
        result: GradingResult,
        binding: ExternalToolGradingContext,
        launch_session_authentication: &ExternalToolLaunchSessionAuthentication,
    ) -> Self {
        Self {
            result,
            attempt: binding.attempt,
            question_revision: binding.question_revision,
            seed: binding.seed,
            launch_session_authentication: launch_session_authentication.0.clone(),
        }
    }
}

/// Provider-local failures. They are deliberately classified as unavailable or
/// invalid rather than a student correctness decision.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ProviderFailure {
    Unavailable,
    Timeout,
    UnsupportedProfile,
    Authentication,
    LaunchSessionAuthentication,
    InvalidResponse,
}

/// Adapter failures suitable for a backend-local retry/degraded state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ImathasAdapterError {
    UnsupportedSource,
    InvalidDraft,
    UnsupportedProfile,
    SourceChecksumMismatch,
    UntrustedSource,
    SourceDoesNotMatchQuestion,
    InvalidCache,
    InvalidProviderRender,
    InvalidTitle(QuestionTitleError),
    InvalidExternalToolLaunchSessionAuthentication,
    VerificationRefused,
    Provider(ProviderFailure),
    ObjectStore(ObjectStoreError),
    QuestionSourceResolution(QuestionSourceResolutionError),
}

impl std::fmt::Display for ImathasAdapterError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::UnsupportedSource => f.write_str("question source is not iMathAS"),
            Self::InvalidDraft => f.write_str("invalid private iMathAS draft locator"),
            Self::UnsupportedProfile => f.write_str("unsupported iMathAS integration profile"),
            Self::SourceChecksumMismatch => f.write_str("iMathAS snapshot checksum mismatch"),
            Self::UntrustedSource => {
                f.write_str("iMathAS source was not resolved through its immutable object")
            }
            Self::SourceDoesNotMatchQuestion => {
                f.write_str("iMathAS source does not match its published question")
            }
            Self::InvalidCache => f.write_str("invalid iMathAS render cache"),
            Self::InvalidProviderRender => f.write_str("invalid iMathAS provider render"),
            Self::InvalidTitle(error) => write!(f, "invalid iMathAS question title: {error}"),
            Self::InvalidExternalToolLaunchSessionAuthentication => f.write_str(
                "invalid server-held iMathAS External Tool Launch Session authentication",
            ),
            Self::VerificationRefused => {
                f.write_str("iMathAS verified grade did not match its server-held binding")
            }
            Self::Provider(_) => f.write_str("iMathAS provider unavailable or rejected request"),
            Self::ObjectStore(value) => value.fmt(f),
            Self::QuestionSourceResolution(value) => value.fmt(f),
        }
    }
}

impl std::error::Error for ImathasAdapterError {}
